### ISSUE TITLE
AuthorizeResponse handle both query and hash fragment

### ISSUE THREAD

**Issue by brockallen** [DuendeArchive/IdentityModel#10]
This response url:

https://code_client/callback?error=invalid_request#_=_

does not parse properly.

**Comment by brockallen** [comment]
Hmm, this is tricky since it's not clear if the payload should be after the ? or after the # without a hint.

**Comment by leastprivilege** [comment]
We need to look into this together

**Comment by leastprivilege** [comment]
We should look into that @brockallen

**Comment by leastprivilege** [comment]
done
