### ISSUE TITLE
Newtonsoft.Json >= 11 (is it really necessary?)

### ISSUE THREAD

**Issue by MonDeveloper** [DuendeArchive/IdentityModel#100]
I know I'm going to be blasted, so, sorry guys for this 99% stupid question. (but since there is a 1% of chance...)

We always try to stay up to date as much as possible with your IdentityServer & IdentityModel libraries and few days ago we noticed that starting from IdentityModel 3.* you increased the minimum version for Newtonsoft.Json library from 10.* to 11.*

We are facing a noisy situation, our base libraries rely on Newtonsoft 10.x and my "base library team" told me they will take at least 1 or 2 months (or even more) to release a version of that libraries compatible with 11.x because of 2 main reasons:
- coding+testing
- third party packages not yet compatible
I guess our scenario is not so rare.

Unfortunately you have been so fast in update your mandatory dependency that it is impossible to me to stay update to your library (because you declared the 11 as minimium dep) and my other third party are still bounded with the 10.

I think many implementers are suffering my problem because the 10.x was out for a long time and the 11.x introduced some breaking changes so i think many third party libraries will take time to update...

Do you confirm the 11.* is really the minimum version of the Newtonsoft.Json library for you library?
Do you have any other suggestion I missed to stay on synch with your lib?

Thanks in advance and, blast me with no regard, I know I deserve it,
Marco

**Comment by leastprivilege** [comment]
My main motivation was that it now finally supports netstandard2 and reduces the amount to dependencies.

It sucks that .net is limited to loading only a single version of an assembly.

**Comment by MonDeveloper** [comment]
Afaik, it should be possible to add 2 different reference for the same lib
(but different version) depending on the framework, I mean, if you use
<targetFrameworks> instead of <targetFramework> you could pack your library
with many flavors.
So you could use a dependency on 11.x for the netstandard2 and the 10.x for
all the other frameworks.
By the way, I would prefer to use always the same version so, if you like
more the 11.x keep it for any Target, just be aware that many users could
be in troubles with this choice.

My personal suggestion is to revert the dependency to 10.x for a period of
time ( 3/6 months) and publish an alert informing the users that starting
from **/**/**** the dependency will be upgraded.


Il Sab 17 Mar 2018, 13:39 Dominick Baier <notifications@github.com> ha
scritto:

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
