### ISSUE TITLE
Request for a TokenClient.RequestResourceOwnerPasswordAsync without Client Credentials

### ISSUE THREAD

**Issue by MonDeveloper** [DuendeArchive/IdentityModel#101]
One of our scenario start with an authenticated client (the client authenticate itself with a piece of code like that):
```c#
var tokenClient = new TokenClient(disco.TokenEndpoint, clientId, clientSecret);
var tokenResponse = await tokenClient.RequestClientCredentialsAsync(scope, extra: extraParameters);
```
and it returns a valid JWT to the client.

At a certain point the client needs to authenticate a User using the "resource owner password" flow (yes, we know it is only for legacy & trusted apps).
In order to do that we are currently using a piece of code like this:
```c#
var tokenClient = new TokenClient(disco.TokenEndpoint, clientId, clientSecret);
var tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync(username, password, scope, extra: extraParameters);
```
and it works.

Since the client has a valid JWT (generated by the first `RequestClientCredentialsAsync`) we are wondering if there is a way to pass that JWT to the TokenClient instead of the ClientId & ClientSecret.

We know that this technique will not give any bit of security more then your approach but doing this way (generating a valid Client JWT and use it anyway instead of ClientId & ClientSecret) will allow us to reach 2 important points:
- We will have one single "AllowAnonymous" Api to generate the client JWT and all the others Api will be authomatically protected by the Bearer Authorization.
- We will have less "Secret"/"Password" parameters flowing through the network and it will be easier keep safe all the log & trace we are writing

**Comment by MonDeveloper** [comment]
Digging into the code I discovered the potential enhancement is not strictly related to the client side but also the Token Endpoint should be able to accept the JWT as an alternative form of client credentials, and, in case validate it.
I'm going to open an Issue also in IdentityServer4 linking this one

**Comment by leastprivilege** [comment]
There's even a "standard" for that - you can pass a JWT like this:

https://github.com/IdentityServer/IdentityServer4.Samples/blob/712534ce4825eae93ac00180e17bcab7106dff3a/Clients/src/ConsolePrivateKeyJwtClient/Program.cs#L37-L43

IdentityServer has a parser for that - you would need to add some custom validation I guess for your scenario.

parser:
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/JwtBearerClientAssertionSecretParser.cs

sample validator:
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/PrivateKeyJwtSecretValidator.cs

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
