### ISSUE TITLE
Query parameters encoding (+ vs %20)

### ISSUE THREAD

**Issue by Dissimilis** [DuendeArchive/IdentityModel#102]
`IdentityModel/Client/RequestUrl.cs` uses `WebUtility.UrlEncode` to encode query parameters. So, for example, scope "_openid profile_" ends up being "_openid+profile_" (_application/x-www-form-urlencoded_).
This may lead to incompatibility in some cases, more appropriate way would be to encode space to `%20` (rfc3986) instead of `+`.
At least an override of encoding should be possible.

**Comment by leastprivilege** [comment]
@blowdart What's the best way these days to do URL encoding in .NET?

**Comment by blowdart** [comment]
Full or Core?

cc @grabyourpitchforks

**Comment by GrabYourPitchforks** [comment]
The UrlEncoder that ships with aspnet core should be preferred when possible. It produces output that is acceptable for the path and the query string.

**Comment by Dissimilis** [comment]
```
var data = "a b";
Console.WriteLine(Uri.EscapeDataString(data));
Console.WriteLine(System.Net.WebUtility.UrlEncode(data));

a%20b
a+b
```
IMHO more compliant way is to encode space to %20.  
And using EscapeDataString would be more idiomatic way, since you encode not a whole URL, but individual values:
```
var qs = string.Join("&", dictionary.Select(kvp => string.Format("{0}={1}", WebUtility.UrlEncode(kvp.Key), WebUtility.UrlEncode(kvp.Value))).ToArray());
return string.Format("{0}?{1}", _baseUrl, qs);
```

But in the end you should provide a way to do escaping manually, or injecting some `Func<string,string>`, because URL encoding is not well standardized.

**Comment by GrabYourPitchforks** [comment]
[`System.Text.Encodings.Web.UrlEncoder`](https://apisof.net/catalog/System.Text.Encodings.Web.UrlEncoder) is the one I was referring to. The APIs in that namespace should be considered The One True Encoder™ and should be preferred over any other encoder API in the framework. Ideally we'd slap `[Obsolete]` on every other API and direct all consumers to this namespace instead, but that would take an act of god. :(

**Comment by leastprivilege** [comment]
happy?

https://github.com/IdentityModel/IdentityModel2/commit/73830f364aab292d5e2aada78d435f14a63e6096

**Comment by GrabYourPitchforks** [comment]
:)

**Comment by leastprivilege** [comment]
done and published
