### ISSUE TITLE
RFC2617 / RFC6749  switch in IntrospectionClient

### ISSUE THREAD

**Issue by Rzpeg** [DuendeArchive/IdentityModel#103]
Hello,

I am migrating IdentityServer3.AccessTokenValidation to .net 4.6.1 / OWIN 4 / JWT 5 stack (https://github.com/Rzpeg/IdentityServer3.AccessTokenValidation) and I was having issues with IntrospectionClient not supporting RFC2617 that's being used in (now deprecated) IdSrv3. 

I have added the RFC2617 / RFC6749 switch support by deriving from IntrospectionClient, but I think it would be great to have it integrated into the main project, just like the TokenClient

If you are fine with my implementation I can make a pull request.
(https://github.com/Rzpeg/IdentityServer3.AccessTokenValidation/blob/master/source/AccessTokenValidation/Plumbing/Rfc2617IntrospectionClient.cs)

Best regards

**Comment by leastprivilege** [comment]
Good idea. Done for 3.4.0

**Comment by Rzpeg** [comment]
Is there an ETA for 3.4.0 nuget ?

**Comment by leastprivilege** [comment]
it's already published

**Comment by Rzpeg** [comment]
Thanks!
Already updated my fork of [IdentityServer3.AccessTokenValidation](https://github.com/Rzpeg/IdentityServer3.AccessTokenValidation)
