### ISSUE TITLE
Client Secret with special characters encode differently than expected. 

### ISSUE THREAD

**Issue by fredmaremyob** [DuendeArchive/IdentityModel#104]
Hi

When I use the latest version of Identitymodel my client secrets with special characters get encoded differently than expected causing my authentication to fail. 

The UrlEncode method encodes the special characters with a different value.

The + character is the only character that is not changed.

Thank you very much
 
```
private static string UrlEncode(string value)
        {
            if (String.IsNullOrEmpty(value))
            {
                return String.Empty;
            }
            
            return Uri.EscapeDataString(value).Replace("%20", "+");
        }
```

**Comment by leastprivilege** [comment]
Yes - this was a bug in older versions 

https://tools.ietf.org/html/rfc6749#section-2.3.1

On TokenClient there is a flag to use the legacy encoding.

**Comment by fredmaremyob** [comment]
Dear Dominick

Thank you for the feedback.

Regards
Fred Mare
