### ISSUE TITLE
TokenClient's innerHttpMessageHandler gets disposed specially while doing unit testing.

### ISSUE THREAD

**Issue by muzammilkm** [DuendeArchive/IdentityModel#105]
TokenClient's innerHttpMessageHandler gets disposed & having difficult to manage multiple message handler specially while doing unit testing. If we have another constructor overload of TokenClient to take disposeHandler (bool) and pass on to HttpClient (HttpMessageHandler, Boolean), so that it wouldn't get disposed.

**Comment by leastprivilege** [comment]
I don't follow...

**Comment by muzammilkm** [comment]
What i meant was, we cannot use same message handler in TokenClient & HttpClient. Since messageHandler which is passed through TokenClient is getting disposed by internal HttpClient of TokenClient. Because of this below code will always throws exception. And the main purpose behind the messageHandler was to get the Unit Testing done by mocking the HttpMessageHandler. 

 ```csharp
// Get the Access Token
using (var tokenClient = new TokenClient("", "", "", messageHandler))
{
     tokenResponse = await tokenClient.RequestClientCredentialsAsync("");
}
// Get the response from API using access token
using (var client = new HttpClient(messageHandler, false))
{
     // throws an exception due to messageHandler got disposed by internal HttpClient of TokenClient
     client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenResponse.AccessToken);
     response = await client.GetAsync("");
}
```
There seems to be two options 
1. Maintain separate HttpMessageHandler for TokenClient. But this would still have a drawback when we want to refresh expired token(call the same logic to get access_token again).

2. Don't use TokenClient instead use HttpClient. 

Or 

Have the another constructor overload or add disposeHandler:bool parameter with default true in TokenClient, and pass disposeHandler to HttpClient. Later, We can explicitly set this flag to false & reuse the same MessageHandler across.

Hope this make sense.

**Comment by leastprivilege** [comment]
And why are you disposing the Token/HttpClient at all?

**Comment by muzammilkm** [comment]
The above code was just to illustrate the problem with TokenClient. And i agree that if we don't dispose the TokenClient things will work, But does't that force users to create & maintain all TokenClient's in entire application in certain way & make sure they don't get disposed. And also we want to get access_token from multiple server's based on dynamically configuration.

**Comment by leastprivilege** [comment]
When you look at our source code we don't explicitly dispose the handler. This is just the way it is supposed to work.

Maybe you shouldn't share handler instances between clients.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by klioqc** [comment]
I also see problem here.
When shared innerHttpMessageHandler is set in the TokenClient constructor, it will be disposed along with TokenClient.Dispose.
This is because you create **Client = new HttpClient(innerHttpMessageHandler);** without using second possible parameter public HttpClient(HttpMessageHandler handler, bool disposeHandler).
So when HttpClient is disposed, it disposes HttpMessageHandler as well and it cannot be reused anymore.
I think there should be a possibility to specify the following option in TokenClient constructor:  Client = new HttpClient(innerHttpMessageHandler, **false**).

**Comment by muzammilkhajamohammed** [comment]
Yes, Agreed. 
And adding bool disposeHandler parameter with default value to true will help both existing consumer as well as those who want the innerHttpMessageHandler not get disposed.

**Comment by leastprivilege** [comment]
@damianh do you have an opinion on this?

**Comment by damianh** [comment]
Few things here

1. `TokenClient` should either take an `HttpClient` as a ctor or act as an extension method over `HttpClient`. HttpClient lifecylce, and the handlers inside it, should be managed outside of IdentityModel (i.e. via HttpClientFactory). In either case there is no dispose operation. See #114 

This code:

    using (var tokenClient = new TokenClient("", "", "", messageHandler))
    {
        tokenResponse = await tokenClient.RequestClientCredentialsAsync("");
    }

would become this code (if implementation remains it's own class):

    var tokenClient = new TokenClient(httpClient, "", "", "");
    var tokenResponse = await httpClient.RequestClientCredentialsAsync()

2. HttpClient in a using block is an antipattern. Don't do that. Minimally make them singleton with respect to the lifecyle of your application (combined with BaseAddress & DefaultHeaders). Better still, use HttpClientFactory (but yeah, those deps...).

3. HttpMessageHandlers/DelegatingHandlers are not meant to be reused across HttpClient instances. It's why the new HttpClientFactory's builder specifically checks for reuse and activates new instances when recreating the handler pipeline. 
![image](https://user-images.githubusercontent.com/57436/41036900-e36c6146-6991-11e8-96f2-defa9580a469.png) See discussion over at #110

From IdentityModel's perspective, I'd mark this issue as wontfix and implement alternative design as indicated #114 

_edit: typos_

**Comment by leastprivilege** [comment]
thanks! closing.
