### ISSUE TITLE
Method not found: 'Void IdentityModel.Client.IntrospectionClient..ctor

### ISSUE THREAD

**Issue by chazt3n** [DuendeArchive/IdentityModel#107]
Hey there! I'm seeing this in a .NET Core 2.1 app only once deployed to IIS

It is the only thing logged by the app and I get 500's back quite quickly

using these versions:
![image](https://user-images.githubusercontent.com/3843179/38754924-6ebda7a2-3f29-11e8-9db4-c92bc16af5b2.png)

Is this a common issue that I'm doing something silly to bring about? It works perfectly when running locally on Kestrel

Please let me know what I can provide to help resolve

Startup.cs

![image](https://user-images.githubusercontent.com/3843179/38755041-e366d966-3f29-11e8-89da-3c8154ed765e.png)

**Comment by leastprivilege** [comment]
I published new nugets. Give that a try. Thanks

**Comment by chazt3n** [comment]
@leastprivilege works perfectly thank you so much
