### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by cosminstirbu** [DuendeArchive/IdentityModel#108]
Hello,

It would be helpful to include a RELEASE_NOTES.txt file in the repo as well, so we could understand what changed from one version to another (especially that in the last 11 days, 5 different versions were released).

Thank you,
Cosmin

**Comment by leastprivilege** [comment]
I totally agree - feel free to contribute.

**Comment by cosminstirbu** [comment]
I understand the hint and I think it's fair to ask for a contribution in this direction.

However, doing this retroactively would be quite painful, going through the git history and trying to make sense of what's relevant form a higher level perspective to be included in the release notes.

However, my suggestions is that for any future development that will happen, any contributor would have to also include a high level / low level (depending on the change) entry in the release notes - and this could be "enforced" via the contribution guidelines.

I can create a PR with an empty RELEASE_NOTES.txt if you want, but I think this should be part of the next real change that will be added to the project.

Regards,
Cosmin

**Comment by leastprivilege** [comment]
It's OK - there is a semi-automated solution to this - like we do here

https://github.com/IdentityServer/IdentityServer4/releases

I just didn't have the time to set it up yet.

**Comment by leastprivilege** [comment]
OK - I will try to be more disciplined in the future

**Comment by octocat-mona** [comment]
@leastprivilege Would be nice if this can be done just like at IdentityServer4 indeed!
