### ISSUE TITLE
Make clients HttpClientFactory friendly

### ISSUE THREAD

**Issue by leastprivilege** [DuendeArchive/IdentityModel#114]
probably by accepting an HttpClient as a ctor parameter...

**Comment by Jetski5822** [comment]
Please!! +1

**Comment by damianh** [comment]
Agreed. TokenClient should work with an HttpClient and not create one internally.

💭 Could the TokenClient logic be exclusively implemented as an extension method over httpclient?

**Comment by damianh** [comment]
When externalizing the activation of the HttpClient you'll lose some control over some aspects such as defining BaseAddress and the DefaulRequestHeaders. No sure how library authors whose users use HttpClientFactory can dictate such things.

**Comment by leastprivilege** [comment]
Extension methods are an interesting idea.

**Comment by Jetski5822** [comment]
HttpClientFactory has configuration extensions for this when you add it to DI

**Comment by leastprivilege** [comment]
@damianh prototype https://github.com/IdentityModel/IdentityModel2/commit/73a3f60efc9fc779a4279c90afdaa9cbfdf6ea83

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2018/06/18/making-the-identitymodel-client-libraries-httpclientfactory-friendly/

Feel free to weigh in
