### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by topfunet** [DuendeArchive/IdentityModel#115]
I am building a WPF program, AllowedGrantTypes is set to GrantTypes.ResourceOwnerPassword, and in my program installed IdentityModel.
I can use this code get access token:
var tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync();
var token = tokenResponse.AccessToken;
But i want to logout and end session when i close program, so HOW can i do it?

**Comment by brockallen** [comment]
> I am building a WPF program, AllowedGrantTypes is set to GrantTypes.ResourceOwnerPassword, and in my program installed IdentityModel.

Resource owner password flow is OAuth2, and that spec has no concept of signout. You can use the token revocation endpoint from the client app to revoke any refresh tokens or reference access tokens you have. That would be the equivalent since it cleans up.

**Comment by topfunet** [comment]
YES, this is exactly what i need.
Thank you very much!
