### ISSUE TITLE
Problem with .Net 4.7.2

### ISSUE THREAD

**Issue by hansbrowser** [DuendeArchive/IdentityModel#116]
I was using IntrospectionClient and TokenClient from the IdentityModel v3.6.1.<br> But when I upgraded the project from .Net 4.7.1 to 4.7.2 I got build errors:

>"Error	CS0012	The type 'HttpMessageHandler' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

The project is already referencing "System.Net.Http" v4.3.3 via NuGet.

Possibly it has got to do with this issue: [https://github.com/Microsoft/dotnet/blob/master/releases/net472/KnownIssues/613745%20-%20Single-name%20references%20are%20removed%20by%20the%20SDK%20when%20targeting%204.7.2.md](https://github.com/Microsoft/dotnet/blob/master/releases/net472/KnownIssues/613745%20-%20Single-name%20references%20are%20removed%20by%20the%20SDK%20when%20targeting%204.7.2.md)
But the workaround suggested here was not working for me.

**Comment by leastprivilege** [comment]
Try

https://www.nuget.org/packages/IdentityModel/3.7.0-preview1

**Comment by hansbrowser** [comment]
Ok, this worked! Thanks.
