### ISSUE TITLE
EpochTime extensions - why not `DateTimeOffset.ToUnixTimeSeconds()` and `DateTimeOffset.FromUnixTimeSeconds()`

### ISSUE THREAD

**Issue by icistrate** [DuendeArchive/IdentityModel#122]
Is there any advantage using your extensions over the already existing `DateTimeOffset.ToUnixTimeSeconds()` and `DateTimeOffset.FromUnixTimeSeconds()` methods? 

I already noticed you are not using these methods in the code.

**Comment by leastprivilege** [comment]
The Microsoft ones are fairly new - mine were first, that why my code uses them.
