### ISSUE TITLE
Why reference System.Text.Encodings.Web when targeting NET452

### ISSUE THREAD

**Issue by adraut** [DuendeArchive/IdentityModel#125]
It appears that when targeting NET452 that the `System.Uri.EscapeDataString` method could be used instead of the `System.Text.Encodings.Web.UrlEncoder`.  Doing so would prevent full framework projects from having to pull in netstandard assemblies.  Furthermore it appears that the `System.Uri.EscapeDataString` method could be used for the netstandard targets also, and eliminate the need for the dependency altogether.  See https://github.com/adraut/IdentityModel2/commit/fa74e5de06caaab39ca039c5dec993ff3e932d56.

Is there a particular reason for using System.Text.Encodings.Web.UrlEncoder?

**Comment by leastprivilege** [comment]
because https://github.com/IdentityModel/IdentityModel2/issues/102#issuecomment-379847713

**Comment by adraut** [comment]
Understood.  Thank you.
