### ISSUE TITLE
Make RefreshTokenDelegatingHandler easier to reuse

### ISSUE THREAD

**Issue by poke** [DuendeArchive/IdentityModel#126]
I’m currently using `RefreshTokenDelegatingHandler` in combination with `HttpClientFactory` in an ASP.NET Core application to ensure I have an access token for the current user to query an API. For this purpose, I have the refresh token available (securely) as a claim value, so I can just register a delegating handler for the client which in turn delegates to the `RefreshTokenDelegatingHandler`. That looks like this:

```
services.AddHttpClient<MyClient>(options =>
{
    options.HttpMessageHandlerBuilderActions.Add(b =>
    {
        var tokenClient = new TokenClient(_tokenEndpoint, _clientId, _clientSecret);
        b.AdditionalHandlers.Add(new UserRefreshTokenDelegatingHandler(tokenClient, _httpContextAccessor));
    });
});

// UserRefreshTokenDelegatingHandler
public class UserRefreshTokenDelegatingHandler : DelegatingHandler
{
    private readonly TokenClient _tokenClient;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public UserRefreshTokenDelegatingHandler(TokenClient tokenClient, IHttpContextAccessor httpContextAccessor)
    {
        _tokenClient = tokenClient;
        _httpContextAccessor = httpContextAccessor;
    }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var refreshToken = _httpContextAccessor.HttpContext.User.GetRefreshToken();
        var handler = new RefreshTokenDelegatingHandlerWrapper(_tokenClient, refreshToken, InnerHandler);
        return handler.SendInternalAsync(request, cancellationToken);
    }

    // internal wrapper to allow calling the `SendAsync` from the outside
    internal class RefreshTokenDelegatingHandlerWrapper : RefreshTokenDelegatingHandler
    {
        public RefreshTokenDelegatingHandlerWrapper(TokenClient client, string refreshToken, HttpMessageHandler innerHandler)
            : base(client, refreshToken, innerHandler)
        { }

        internal Task<HttpResponseMessage> SendInternalAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            => SendAsync(request, cancellationToken);
    }
}
```

This works but it has three problems:
1. If I have multiple requests for the same user within the same request, I essentially have to request the access token over and over. I cannot directly reuse the access token I retrieved for a user.
2. I should actually dispose of the `RefreshTokenDelegatingHandler`. Because it internally uses a [`SemaphoreSlim`, I should generally dispose it](https://stackoverflow.com/q/32033416/216074). However, disposing it also means that the inner handler will be disposed (by the base `DelegatingHandler`) which is problematic since I actually want to reuse that within the parent `UserRefreshTokenDelegatingHandler`.
3. `RefreshTokenDelegatingHandler`, while thread-safe on its own, probably does not support a multi-user environment where different tokens are concurrently required.

I can work around the first problem by simply storing the retrieved access token, or even the full delegating handler instance somewhere. This won’t allow me to reuse it across multiple incoming requests (which is fine) but at least I can reuse it within my request scope for multiple outgoing requests. That will also save me against the third problem. But storing the handler just makes the second problem even more problematic since I now don’t even have some point in time where I could dispose of the object.

---

So what I would like to ask for is some means for reusing the handler. The primary problem that makes the instance difficult to reuse (for different users) is that the tokens are private instance state. Ideally, I would want to write something like this that moves the tokens completely out of the instance:

```
public class UserRefreshTokenDelegatingHandler : RefreshTokenDelegatingHandler
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public override string AccessToken
    {
        get
        {
            if (_httpContextAccessor.HttpContext.Items.TryGetValue("_AccessToken", out var token))
                return (string)token;
            return null;
        }
        set
        {
            _httpContextAccessor.HttpContext.Items["_AccessToken"] = value;
        }
    }

    public override string RefreshToken
        => _httpContextAccessor.HttpContext.User.GetRefreshToken();

    public UserRefreshTokenDelegatingHandler(TokenClient tokenClient, IHttpContextAccessor httpContextAccessor)
        : base(tokenClient)
    {
        _httpContextAccessor = httpContextAccessor;
    }
}
```

Obviously, that doesn’t work right now, so I am wondering what you would think about this idea. Whether it would be something worth to invest in, or whether you have alternative ideas. I’m currently considering just implementing everything myself by copying most of the existing logic, but I would much rather reuse the existing logic, and instead contribute to the upstream `RefreshTokenDelegatingHandler` to make it reusable.

**Comment by leastprivilege** [comment]
Yea - this design pre-dates the factory approach. Need to re-think it.

I am currently focusing on updating the endpoint client libs and want to release that soon.

**Comment by ghost** [comment]
We would also be very interested in this. Unless I'm mistaken this feature is not available in any .NET Core library (multi-user automatic/transparent use of refresh tokens). Thank you Patrick for pointing out problems I was about to face.

**Comment by poke** [comment]
Hey, I’m currently rewriting part of an application to to migrate away from `TokenClient` to the new `HttpClient`-based extension methods. I previously used the `AccessTokenDelegatingHandler` and the `RefreshTokenDelegatingHandler` for this but the handlers still use the `TokenClient` as the underlying way to retrieve tokens.

Is there any forward plan for the handlers? I am currently considering rewriting them completely myself to get the functionality on top of the extension methods since I still think there is an interest in having a transparent way to retrieve and store tokens for client situations.

If there is interest in this, then I would be open to contributing this back. Or do you have other plans for this, or maybe you want to follow a different approach?

**Comment by leastprivilege** [comment]
The handlers will be removed. They were originally designed for native client apps - not for web applications.

I am open having something better in the future but I need to finalize IdentityModel 4 first before I can think about ASP.NET Core specific extensions.

**Comment by danielmeza** [comment]
@leastprivilege there is a issue to track the handler?
