### ISSUE TITLE
RefeshTokenHandler will block new requests when a refresh is in progress

### ISSUE THREAD

**Issue by richardszalay** [DuendeArchive/IdentityModel#13]
RefeshTokenHandler uses lock.WaitAsync in RefreshTokensAsync, but SendAsync accesses the lock.Wait()-using AccessToken. This would cause the request originator to be blocked since DelegatingHandlers are not called on a background thread.

Adding a GetAccessTokenAsync would solve the problem. I'm happy to submit a PR if I get the time.

**Comment by leastprivilege** [comment]
Right - which is the desired behavior - the access token is not good anymore at this point - and refresh has to be tried first.

Or did I misunderstand you?

**Comment by richardszalay** [comment]
My point is that it will block the calling thread. In a ui application, it would block the ui.

**Comment by leastprivilege** [comment]
Ah I see - yea send me a PR.

**Comment by richardszalay** [comment]
Done. 

I'd also recommend allowing the timeout to be supplied in the constructor - the 2 second default would certainly elapse if it reached a .NET (full) endpoint that was cold.

**Comment by leastprivilege** [comment]
The timeout can be set on the TokenClient

**Comment by leastprivilege** [comment]
..and thanks!
