### ISSUE TITLE
'UTF8' is not a supported encoding name

### ISSUE THREAD

**Issue by bakman23** [DuendeArchive/IdentityModel#131]
Hello, I get an error 'UTF8' is not a supported encoding name  when I call  this method 
`            TokenResponse response = await client.RequestAuthorizationCodeAsync(
                code,
                urlRedirection);`
Have you an idea how can I  solve it ?
Thanks

**Comment by leastprivilege** [comment]
Need more context.

**Comment by bakman23** [comment]
`public ActionResult Login(string prompt = null, string acrValues = null)
        {
            var request = new RequestUrl(ConfigHelper.IdentityServer.AuthorizeEndpoint);

            string url = request.CreateAuthorizeUrl(
                clientId: ConfigHelper.IdentityServer.ClientId,
                responseType: "code",
                scope: ConfigHelper.IdentityServer.Scopes,
                redirectUri: Request.Url.GetLeftPart(UriPartial.Authority) + Url.Action("LoginCallback", "Account"),
                state: state,
                nonce: nonce,
                acrValues: acrValues,
                prompt: string.IsNullOrEmpty(prompt) ? null : prompt);

            return Redirect(url);
        }

       public async Task<ActionResult> LoginCallback(string code, string state, string error)
        {
            TempState tempState = await GetTempStateAsync();

            var urlRedirection = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Action("LoginCallback", "Account");
            TokenResponse response = await client.RequestAuthorizationCodeTokenAsync(
                new AuthorizationCodeTokenRequest() {
                    Address = ConfigHelper.IdentityServer.TokenEndpoint,
                    Code = code,
                    ClientId = ConfigHelper.IdentityServer.ClientId,
                    ClientSecret = ConfigHelper.IdentityServer.ClientSecret,
                    RedirectUri = urlRedirection
                })`

The method .RequestAuthorizationCodeTokenAsync get from the server "Method not allowed"

**Comment by leastprivilege** [comment]
Sorry this is not helpful. I have never seen this error message before.

Which version of .NET / platform is that?

**Comment by bakman23** [comment]
.NET 4.5.2 & MVC

**Comment by leastprivilege** [comment]
Then I have no idea. This works fine for me.

**Comment by bakman23** [comment]
I found something, I called my server without https.
Now the RequestAuthorizationCodeTokenAsync method return 
Unexpected character encountered while parsing value: B. Path '', line 0, position 0.  :(

**Comment by leastprivilege** [comment]
all set?
