### ISSUE TITLE
httpClient Hangs and never returns

### ISSUE THREAD

**Issue by CraigEaston** [DuendeArchive/IdentityModel#133]
I created a simple Windows UI exe to test getting a token

This is a simple .net 4.6.1 windows forms program with a single button on it.

The call to " client.RequestClientCredentialsTokenAsync(request).Result;" never returns, it just hangs

I'm running version 3.8.0 of IdentityModel.  Is this not compatible with .net 4.6.1? 

Any thoughts would be well appreciated

The click event looks like this:
`private void button1_Click(object sender, EventArgs e)
      {
         var client = new HttpClient();

         IdentityModel.Client.ClientCredentialsTokenRequest request = new ClientCredentialsTokenRequest();
         request.Address = "https://[MyIdentityServer3Implmentation]/connect/token";
         request.ClientId = "[MyClientID]";
         request.ClientSecret = "[MyAwesomePasswordForMyClient]";
         request.Scope = "MyAwesomeScope";
         var response = client.RequestClientCredentialsTokenAsync(request).Result;

         if (response.IsError) throw new Exception(response.Error);
         var token = response.AccessToken;
      }`

**Comment by leastprivilege** [comment]
It's a known issue that usage of `.Result` can lead do deadlocks - especially in UIs. Use async/await instead.

**Comment by CraigEaston** [comment]
Uhhhh..
THANK YOU !!!!

Change it to call a private async void GetToken() method and used await client.RequestClientCredentialsTokenAsync.

Now works
Thanks again!
