### ISSUE TITLE
more problems with system.net.http

### ISSUE THREAD

**Issue by figuerres** [DuendeArchive/IdentityModel#134]
ok this sucks as it is complicated so i will just try and describe:

on a laptop i have code that works. on the server it fails, both server and laptop have matching .net versions installed.
the failure is around system.net.http.dll binding

the code is a security extension for Microsoft SSRS 2017 to make token auth work.
works on my latop!
trying to now run the same code on a server and it's making me crazy!
wishing that i had an identity model dll with no reliance on this dll!
also wishing that Microsoft had just fixed SSRS to do OpenId COnnect in the first place!!!
Sorry for the rant but i am really frustrated with having the code working on one machine but not the other!!!

**Comment by leastprivilege** [comment]
yea - it is far from ideal. But this is an issue for Microsoft. There's nothing I can do about that.
