### ISSUE TITLE
Determine claim value type from JSON rather than always assuming string

### ISSUE THREAD

**Issue by liambrown89** [DuendeArchive/IdentityModel#136]
The `ToClaims` method in JObjectExtensions.cs uses the `Claim(type, value)` constructor (https://msdn.microsoft.com/en-us/library/hh159804(v=vs.110).aspx) and `ToString`s the JSON value. As a result, "the `ValueType` property is set to `ClaimValueTypes.String`" (as the MSDN article says).

The knock on effect is that all of the resulting claims have string `ValueType`s, when in reality they may be bool, number, etc.

It would be much better if the type could be checked and determined here and then the `Claim(type, value, valueType)` constructor (https://msdn.microsoft.com/en-us/library/hh194425(v=vs.110).aspx) used instead.

**Comment by leastprivilege** [comment]
Feel free to PR if you think this is important.

**Comment by leastprivilege** [comment]
No PR. closing.

**Comment by liambrown89** [comment]
I think you should leave this open as I do think it is important to be corrected. I will try and get around to doing a PR soon.
