### ISSUE TITLE
Expiration as Int32 is capped at 2038

### ISSUE THREAD

**Issue by Jaternius** [DuendeArchive/IdentityModel#137]
Due to the change introduced with 17a26a4ec95d7067856462a5788d7dc0501043d0, tokens that are valid beyond 2038 (e.g. issued today with `int.MaxValue` as expiration) suffer from an integer overflow for their expiration and therefore are wrongly "expired" in the past.

This causes issues in some dependencies, in our case in the [IdentityModel.AspNetCore.OAuth2Introspection caching](https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/dev/src/IdentityModel.AspNetCore.OAuth2Introspection/Infrastructure/CacheExtensions.cs#L53-L56). Because IdentityModel reports `expClaim.Value` as sometime in the 1950s, the tokens are not cached and the IdentityServer is hit with every request. The token validity itself seems not directly impacted by this, i.e. the tokens are still accepted by the authentication middleware (although I am not sure why).

In my scenario, the tokens are issued to embedded devices which are expected to run for years. It's been a requirement that such tokens must "work indefinitely until revocation", hence the int.MaxValue approach. As a workaround, we'll re-issue all existing tokens with a hardcoded expiration of 2038, but that's not exactly pretty (although I must admit that issuing reference tokens for 68 years isn't exactly either).

**Comment by leastprivilege** [comment]
Yep - that's a know problem.

https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by Jaternius** [comment]
Yupp, I'm familiar with it. My problem is that this library isn't Y2038-safe, which causes the aforementioned headaches down the line. Is there any chance to change it back to long, or add at least support long in some way?

**Comment by leastprivilege** [comment]
Well - epoch time is not Y2038 safe. The JWT handler from MS e.g. will not validate tokens beyond 2038.

Unless something has changed recently.

**Comment by Jaternius** [comment]
The usual implementation using 32bit numbers isn't Y2038 safe, but epoch time itself isn't necessarily tied to an Int32.

Microsoft's JWT handler doesn't handle those tokens... which strikes me as odd, considering I believe that the code in aspnet/security that deals with token creation will happily create tokens with an expiration time way beyond 2038.

Now I'm intrigued though... Why isn't the token rejected? If the expiration is clearly in the past, shouldn't it be denied?

**Comment by Jaternius** [comment]
After digging around a bit, I've found out that the "issue" is stretched across our whole authentication/authorization architecture.

- The introspection endpoint of IdentityServer4 is returning the exp as a `ClaimValueTypes.Integer` ([src](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Validation/TokenValidator.cs#L453)), therefore it will already be negative at introspection time. This creates an odd situation where the introspection returns an active token which already expired fifty years ago. Still, I suppose that's within the specification. However, this also means that no client could possibly recover from this.
- As to why the reference token is still accepted: IdentityModel.AspNetCore.OAuth2Introspection will accept any token as long as `active` is set to `true`. nbf and exp claims are ignored. This is the reason why this setup could work (until now).

As a work around, I've adjusted our `IClientStore` in the IdentityServer to dynamically throttle down the expiration, if it would exceed 2038. This isn't exactly nice, but it's as good of a workaround as I can probably get in the near future:

```csharp
private static readonly DateTime Y2038 = new DateTime(2038, 1, 1);

// ...

public async Task<Client> FindClientByIdAsync(string clientId)
{
    var client = GetClients().FirstOrDefault(c => c.ClientId == clientId);

    // ...

    if (DateTime.Now.AddSeconds(client.AccessTokenLifetime) >= Y2038)
        client.AccessTokenLifetime = (int)(Y2038 - DateTime.Now).TotalSeconds;
```

So the only question I have left before this issue can be closed would be the choice of ClaimValueTypes.Integer, and not ClaimValueTypes.Integer64 for this claim in general. I'm not familiar with any of the relevant security specs, sadly. Is it an actual requirement to have a 32bit integer or was this a design choice (for compatibility reasons I suppose)?

**Comment by leastprivilege** [comment]
The first step is, that I removed the epoch helpers in v4. And obsoleted them in v3.

We are in the process of switching everything over to the .NET built-in unix time helpers which use long. But this will take some time.

thanks for reporting!
