### ISSUE TITLE
Allow overriding the discovery endpoint url

### ISSUE THREAD

**Issue by jachin84** [DuendeArchive/IdentityModel#140]
Would it be possible to change this line https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/Old/DiscoveryClient.cs#L85 to provide a getter and setter?

I have hit the issue a couple of times where a test environment provides a discovery url that is non-standard. It would be nice to have a way of overriding the Url. 

An example is Intuit who use the following:
```
Sandbox: https://developer.api.intuit.com/.well-known/openid_sandbox_configuration
Prod: https://developer.api.intuit.com/.well-known/openid_configuration
```

**Comment by leastprivilege** [comment]
these endoint names are not spec compliant - so I will not accomodate for that.

But you can make the GET request yourself and pass the returned string to `DiscoveryResponse` for parsing.

**Comment by jachin84** [comment]
I agree that it’s not spec complaint. Unfortunately you can imagine what happens when I you tell an OpenID Connect provider they are not spec compliant....silence. 

Making the get request using my own HttpClient isn’t a horrible fix however I don’t think changing that getter to be both a getter/setter necessarily violates the spec. It just enables some flexibility when the provider doesn’t do the right thing. And unfortunately there are a lot who don’t do the right thing.

Don’t punish consumers of your library for mistakes by third parties they have no possibility to influence or control.

**Comment by brockallen** [comment]
@jachin84 Did you send them a request to fix their issue? In doing so, you let them that they're hurting you as well, given that non-spec compliance hurts interoperability, and costs your company money in trying to find work-arounds.

**Comment by jachin84** [comment]
I did indeeded attempt to get them to fix it. In this specific case the argument is the prod URL is compliant but the sandbox is not. Given the sandbox is for testing they won’t change it. In fact in their own client library they have a modified version of IdentityModel dropped into their code that fixes the issue. We don’t use their client library though.

Have a look if you like: 
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient/Client/DiscoveryClient.cs

It’s not a major issues I just figure it was such a minor change it might be worth asking.

**Comment by brockallen** [comment]
Yea, I hear your pain. It boils down to whose time and money is being used up to accommodate their decision to be non-spec compliant.

**Comment by brockallen** [comment]
Huh... makes me wonder why they stripped our copyright headers. I'll have to look into it.

**Comment by brockallen** [comment]
For what it's worth: https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/43
