### ISSUE TITLE
Policy to turn off endpoint validation

### ISSUE THREAD

**Issue by jchannon** [DuendeArchive/IdentityModel#142]
Executing the below against AWS the response returns an error because the uris are different.

In the OIDCClient repo/lib you can pass a policy to disable validating endpoints. How can I do this with this library?

```
 var disco = await client.GetDiscoveryDocumentAsync("https://AWS_URI");
 if (disco.IsError) throw new Exception(disco.Error);
```

Thanks

**Comment by jchannon** [comment]
Ah ok, using the DiscoveryClient explicitly not the HttpClient extensions

**Comment by brockallen** [comment]
Call the version that lets you pass the options and policy: https://github.com/IdentityModel/IdentityModel2/blob/58218bc33bc3ebb4414372196c6e38cd199e3f93/src/IdentityModel/Client/New/HttpClientDiscoveryExtensions.cs#L37

**Comment by jchannon** [comment]
👍
