### ISSUE TITLE
.NetFramework 4.7.1 not found “Void IdentityModel.Client.TokenClient..ctor(System.String, System.String, System.String, System.Net.Http.HttpMessageHandler, IdentityModel.Client.AuthenticationStyle)

### ISSUE THREAD

**Issue by wuyanxo** [DuendeArchive/IdentityModel#143]
![image](https://user-images.githubusercontent.com/29368020/44513386-c9edce80-a6ef-11e8-8247-815c44c7d26b.png)
by 3.9.0

我是直接Nuget 安装的IdentityModel3.9.0 于是便出了刚才的错误，切好为3.0.0时提示我多安装了几个包就可以了，但是我不明白为什么要安装那几个不相干的包，而且在1.9.2也是不需要安装那些包的
I installed Identity Model 3.9.0 directly from Nuget, so I made the mistake of prompting me to install a few more packages when I cut it to 3.0.0, but I didn't understand why I had to install those unrelated packages, and I didn't need to install those packages in 1.9.2.

**Comment by andrewvanbeek-okta** [comment]
I am also having this issue!  Any guidance would be helpful!

**Comment by leastprivilege** [comment]
Sorry - not enough info. If you have a better repro, feel free to open a new issue.
