### ISSUE TITLE
Intuit's QBO V3 SDK (OAuth2PlatformClient) implementation details

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#144]
Hi Brock and Team,

I'm reaching out to you for the issue raised here- https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/43
When we earlier released an updated version of IdentityMode2 source code for Intuit, following is the brief summary of changes we did for Intuit’s server side Oauth2 implementation. 
1) We required custom discovery url handling, custom scope values, custom authorize url creation, custom function names to help 3rd party devs integrate easily, custom handling token response for extra params like realmid, having one single revoke method for access and refresh token, helper classes for idtoken, userinfo. We made changes for these in the modified mode.
2) Since, it was an implementation only for server side apps, having all code for diff Oauth2 workflows was redundant for our use case and we removed many such functions from the code.
3)We later added a wrapper OAuth2Client so as to help devs who did not want to use different clients for getting tokens, refreshing, revoking, validating idtokens etc.
4) We also have a requirement to add additional logging for intuit specific header values in error response in a future release.
After analyzing atleast 12 diff open source projects in Jan 2017, we felt that IdentityModel2 was really a good start for us to extend and provide our developer community a really good Oauth2 client lib. 
Currently, we see that IdentityModel2 source code changed a lot since the first time we used it’s code base which might be good for us to extend using the binaries after requesting for certain enhancements. But in 2017, we weren’t sure as these were a lot of changes to ask from any open source project and therefore we extended the original source and misunderstood the open source licensing requirements. We regret that.

Hopefully, you can help us out to see if these enhancements can be made and if we can use the binaries going forward for the Oauth2 SDK. The only catch here is that we would not like to break any existing devs using the Oauth2 lib/implementation we have provided them. Do let us know how we can go about this or if we can keep using the code as is?
Note: We would also like to understand how refresh token handler can be used to regenerate tokens in case of token expiry instead of using TokenClient for the same task.

Thanks for a really awesome SDK and the great work you have done on simplifying the Oauth2 workflows on different clients.

**Comment by leastprivilege** [comment]
Hi, 

I would recommend you have a look at the current state and check if anything is missing. 
If this is the case, please open an issue for each feature request so we can discuss that.

**Comment by nimisha84** [comment]
Sure, will add individual enhancements requests soon. Thanks!

**Comment by brockallen** [comment]
Any update on this @nimisha84?

**Comment by nimisha84** [comment]
Sorry, I haven't been able to open the requests on time due to some tie ups.
Opening the issues now one by one.
