### ISSUE TITLE
Intuit's Oauth2 support- Request 1- HttpClient /DiscoveryClient

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#145]
Need support/extra param for 'appEnvironment' in HttpClient extension. If that is not possible then DiscoveryClient needs to support this as we want to support one wrapper client similar to httpClient for Oauth2 calls.
appEnvironment will support 2 value sandbox and prod as Discovery urls are diff for both.

**Comment by leastprivilege** [comment]
Again - I would recommend simply building your own extension method on top of ours. Would that work for you?

**Comment by leastprivilege** [comment]
Also - it seems all you need is parsing of the response. You could try to make the HTTP GET request yourself and and feed the response into `DiscoveryResponse`.

**Comment by nimisha84** [comment]
I am actually writing down all Intuit's req here to get your advice to see if your team will be creating the extensions or I should it.

Yes, I can do any of the above.  Thanks for the suggestion.

**Comment by nimisha84** [comment]
Reopening it as you might be tracking it under your feature reqs
