### ISSUE TITLE
Intuit's Oauth2 support- Request 2 - OIDC scopes - Standard values needed

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#146]
Need support for passing in OIDC standard values for scopes as constant values defined in developer.intuit.com spec and also this class should be extensible for adding more standard scopes in future.
Spec link- https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect#prerequisites

scopes - com.intuit.quickbooks.accounting, com.intuit.quickbooks.payments, openid, phone, profile, address, email.

**Comment by leastprivilege** [comment]
Our `OidcConstants` class would be the place to do that. It's missing right now - but we can add it.

**Comment by nimisha84** [comment]
Thanks!

**Comment by leastprivilege** [comment]
done. Will be in next build.

**Comment by nimisha84** [comment]
Thanks. Closing this!
