### ISSUE TITLE
Intuit's Oauth2 Support- Request 4- Create Token using Tokenclient or HttpClient- issues because of _

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#148]
POST https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer HTTP/1.1
Accept: application/json
Authorization: Basic UTM0dVBvRDIwanp2OUdxNXE1dmlMemppcTlwM1d2
   NzRUdDNReGkwZVNTTDhFRWwxb0g6VEh0WEJlR3dheEtZSlVNaFhzeGxma1l
   XaFg3ZlFlRzFtN2szTFRwbw==
Content-Type: application/x-www-form-urlencoded
Host: oauth.platform.intuit.com
Body: grant_type=authorization_code&
code=L3114709614564VSU8JSEiPkXx1xhV8D9mv4xbv6sZJycibMUI&
redirect_uri=https://www.mydemoapp.com/oauth-redirect

Grant_type and redirect_uri are custom format for the granttype and redirectUri params if I use TokenClient separately. I can use extra object too but code and redirectUri mandatory param. 

I would prefer to use one client->httpclient instead with method RequestTokenAsync but that totally diff params passed in TokenRequest than what Intuit's imple uses -https://identitymodel.readthedocs.io/en/latest/client/token.html

**Comment by leastprivilege** [comment]
Again - this library uses the parameters are defined in the spec.

**Comment by nimisha84** [comment]
@leastprivilege - Coming back to this again after checking with engineering team. They mentioned that Intuit's implementation follows this version of OpenId Connect spec-
https://openid.net/specs/openid-connect-basic-1_0.html#RFC6749 
So, the underscores in the names for all requests follow the expected naming conventions. Can you confirm which version of the spec this lib follows?

**Comment by leastprivilege** [comment]
We are fully spec compliant with RFC6749 and OpenID Connect. Underscores are correct - that's what we do.

**Comment by leastprivilege** [comment]
Maybe I misunderstand your issue.

**Comment by nimisha84** [comment]
Now that I look at OIDCConstants class, maybe I reported a non issue. Please ignore.
