### ISSUE TITLE
Intuit's Oauth2 support-Request 5- Authorize Response, Token Response, Id Token ->claims - need support for extra param

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#149]
Authorize response- need support for RealmId param( I believe dictionary  values or raw param should be used?)
Token response- Need support for "refresh token expiry" param (raw param should be used for further getting this field's value?)
Id token->claims parser class? is this supported in the IdentityModel? We need to support extra claim for Realmid(our domain specific)
Also, can you confirm if there is a helper for validating idtoken or do we need to provide it as we currently do through our SDK?

**Comment by leastprivilege** [comment]
You can parse extra response parameters via the JSON property. IdentityModel does not validate tokens, this is something you need to do yourself.

**Comment by nimisha84** [comment]
Thanks! Please close.
