### ISSUE TITLE
Intuit' Oauth2 support-Request 6- Issues because of _ in Refresh Token request and need support for RefreshTokenClient/HttpClient method for Refresh Token

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#150]
POST /oauth2/v1/tokens/bearer HTTP/1.1
Accept: application/json
Authorization: Basic UTM0dVBvRDIwanp2OUdxNXE1dmlMemppcTlwM1d2
   NzRUdDNReGkwZVNTTDhFRWwxb0g6VEh0WEJlR3dheEtZSlVNaFhzeGxma1l
   XaFg3ZlFlRzFtN2szTFRwbw==
Content-Type: application/x-www-form-urlencoded
Host: oauth.platform.intuit.com
Cache-Control: no-cache
Body: grant_type=refresh_token&
refresh_token=Q311488394272qbajGfLBwGmVsbF6VoNpUKaIO5oL49aXLVJUB

Body params use _ and refresh token is passed along with grant type
I see RefreshTokenDelegatingHandler as an option but our devs need the support for a Refresh token 
 or http client method for refresh token too.

**Comment by leastprivilege** [comment]
The HttpClient extensions methods have a method to manually refresh tokens.
