### ISSUE TITLE
Exception swallowing in refresh token handler

### ISSUE THREAD

**Issue by jochenz** [DuendeArchive/IdentityModel#151]
The RefreshTokenDelegatingHandler exposes this event:

https://github.com/IdentityModel/IdentityModel2/blob/409f2493d333d3921586a20fce88971e4d019041/src/IdentityModel/Client/RefreshTokenDelegatingHandler.cs#L77-L80

But when I implement an event subscriber, I'll never now that my subscriber is buggy, because my exceptions will be swallowed (empty catch all statement) and nobody will know about it:

https://github.com/IdentityModel/IdentityModel2/blob/409f2493d333d3921586a20fce88971e4d019041/src/IdentityModel/Client/RefreshTokenDelegatingHandler.cs#L259-L266

**Comment by leastprivilege** [comment]
OK - good point. IIRC i wanted to shield the handler from errors in the subscriber...

**Comment by leastprivilege** [comment]
@damianh OK to change?

**Comment by damianh** [comment]
This is run on a background non-awaited task though https://github.com/IdentityModel/IdentityModel2/blob/409f2493d333d3921586a20fce88971e4d019041/src/IdentityModel/Client/RefreshTokenDelegatingHandler.cs#L257 . Removing the try-catch here would mean the task just dies if the subscriber throws and nobody will know about it either (and any subsequent `del`'s from the invocation list will not be called until next refresh).

Also there is a possibility of race conditions for subscribers whereby even though there is a lock to synchronize token refreshing https://github.com/IdentityModel/IdentityModel2/blob/409f2493d333d3921586a20fce88971e4d019041/src/IdentityModel/Client/RefreshTokenDelegatingHandler.cs#L242 the the lock may be released at https://github.com/IdentityModel/IdentityModel2/blob/409f2493d333d3921586a20fce88971e4d019041/src/IdentityModel/Client/RefreshTokenDelegatingHandler.cs#L275 while the background task is still 'running'. Concurrent events may be raised where a subscriber may not expect to have to handle re-entrency.

I am of the opinion `event` and `EventHandler<T>` is not the right mechansim for _async_ fire'n'forget signalling / notifications and dealing with subscribers erroring in multi-threaded async components. As an example of alternative design for subscriptions, you can take a look at https://github.com/SQLStreamStore/SQLStreamStore/blob/master/src/SqlStreamStore/IReadonlyStreamStore.cs#L161-L168 where the caller registers two callback delegates, one for the event `StreamMessageReceived` and one for when the subscription goes wrong `SubscriptionDropped` which can be for [multiple reasons](https://github.com/SQLStreamStore/SQLStreamStore/blob/master/src/SqlStreamStore/Subscriptions/SubscriptionDroppedReason.cs). The implementation behind this uses a [TaskQueue](https://github.com/SQLStreamStore/SQLStreamStore/blob/master/src/SqlStreamStore/Infrastructure/TaskQueue.cs) to serialize notifications from async & concurrent sources. (Also this is a richer subscription interface for functional reasons...).

So I don't think changing this will be of any benefit. Instead I would suggest a redesigned component. Actually, I have a need for such a component to handle multiple Access/Refresh Tokens with a single HTTP Client and multiple endpoints / hosts...

**Comment by leastprivilege** [comment]
I am all for a re-designed handler.

**Comment by leastprivilege** [comment]
Working on v4 right now - there'a a `v4` branch as well. Now's the time for a new design..
