### ISSUE TITLE
AccessTokenDelegatingHandler do not have a default inner handler

### ISSUE THREAD

**Issue by martintro** [DuendeArchive/IdentityModel#155]
Both AccessTokenDelegatingHandler and RefreshTokenDelegatingHandler do not have a default inner handler when the constructors without the inner handler parameter is used.

Shouldn’t they default to the same inner handler HttpClient defaults to when null is provided?

**Comment by leastprivilege** [comment]
That's by design - you have to compose the pipeline yourself.
