### ISSUE TITLE
Could not load file or assembly IdentityModel, Version=3.7.0.0

### ISSUE THREAD

**Issue by mpaine-act** [DuendeArchive/IdentityModel#156]
I just upgraded from IdentityModel 3.9.0 to 3.10.0 and received this error.   I am running the Okta-Hosted Login @ https://github.com/okta/samples-aspnet.  When I back down to 3.9.0, the sample website logon works fine.

**Comment by leastprivilege** [comment]
You have to re-compile the host - did you do that?
