### ISSUE TITLE
RefreshTokenHandler obsolete attribute documentation incorrect

### ISSUE THREAD

**Issue by maskati** [DuendeArchive/IdentityModel#157]
`RefreshTokenHandler` [Obsolete](https://github.com/IdentityModel/IdentityModel2/blob/97d134bcdfd967f0ee702ee6aca1be09d6a356f3/src/Client/Old/RefreshTokenHandler.cs#L17) attribute is incorrectly suggesting to use `AccesTokenDelegatingHandler` instead of `RefreshTokenDelegatingHandler`.

**Comment by leastprivilege** [comment]
thanks. Feel free to PR.

**Comment by leastprivilege** [comment]
done
