### ISSUE TITLE
DiscoveryCache stores failed attempt to get the document.

### ISSUE THREAD

**Issue by peterwjmorris** [DuendeArchive/IdentityModel#158]
If there is a transient error in fetching the discovery document the DocumentCache will store this and return the failure for whatever the `CacheDuration` is. We could check for failure and call `Refresh` on failure, but at the risk of spamming the OP with requests for the duration of the downtime, which the cache should protect from.

Is this intended behaviour?

Our preferred solution is to have a short cool off period, before the cache automatically retries a failed attempt.

**Comment by leastprivilege** [comment]
You can pass in an HttpClient with something like Polly to give you retry semantics.

But I agree that we should not store faulted responses.

**Comment by leastprivilege** [comment]
Feel free to draft a PR.

**Comment by leastprivilege** [comment]
@brockallen

**Comment by brockallen** [comment]
Sorry -- didn't see this issue until now. I'll have a look, unless you already have a proposal/PR?

**Comment by leastprivilege** [comment]
fixed in v3. Will publish a new nuget soon.

**Comment by yuanfei05** [comment]
- - 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
