### ISSUE TITLE
In RequestClientCredentialsAsync the response is always 200

### ISSUE THREAD

**Issue by ghost** [DuendeArchive/IdentityModel#159]
My endpoint is returning a bad request 400 but tokenResponse is showing a 200, the error is in the body but the HttpCode is lost

    var tokenClient = new TokenClient(disco.TokenEndpoint, ClientId, ClientSecret);
    var tokenResponse = await tokenClient.RequestClientCredentialsAsync(TheScopes);

In Old/TokenClient and in New/HttpClientTokenRequestExtensions (and the other extensions)

    if (response.StatusCode == HttpStatusCode.OK || response.StatusCode == HttpStatusCode.BadRequest)

This code is returning a BadRequest as a OK. In my implementation of IdentityServer4 I have a call (example above) that throws a 400 because there is a claim missing that I expect, but this is returning a 200 instead.

**Comment by leastprivilege** [comment]
Thanks - I can have a look when I find time.

If you want to speed up that process - add a test that proves the behavior and then fix it if possible.

**Comment by leastprivilege** [comment]
OK - I had a look. I distinguish between OK and Bad Request on the fact that the response has an error in the body...is that not the case for you?

https://github.com/IdentityModel/IdentityModel2/blob/master/test/UnitTests/HttpClientExtensions/HttpClientTokenRequestExtensionsResponseTests%20-%20Copy.cs#L44-L63

**Comment by leastprivilege** [comment]
any update?
