### ISSUE TITLE
Support Windows.Web.Http form Windows Runtime / UWP

### ISSUE THREAD

**Issue by xperiandri** [DuendeArchive/IdentityModel#16]
So I tried to add support for `Windows.Web.Http` and it requires to create counterparts for:
- BasicAuthenticationHeaderValue
- HttpClientExtensions
- IntrospectionClient
- RefreshTokenHandler
- TokenClient
- TokenClientExtensions
- TokenRevocationClient
- TokenRevocationClientExtensions
- UserInfoClient

Which is not a big deal for me.
However as you expose `public HttpStatusCode HttpErrorStatusCode { get; }` from `TokenResponse` and `UserInfoResponse` they cannot be universal. As HttpStatusCode in WinRT is absolutely different enum.

What do you think? Let us change it to int?

**Comment by xperiandri** [comment]
And with this change we can no longer leave `IdentityModel.Client` for mentioned classes.
Do yoг have any ideas of how to name them?

I think that it would be reasonable to use `System.Net.Http` and `Windows.Web.Http`

**Comment by leastprivilege** [comment]
And what would be the benefit of that?

The .NET world is moving towards netstandard. One .net class library for all platforms - where the optimal implementation for a give platform is done by platform "vendor" and not by the library author.

**Comment by xperiandri** [comment]
Benefit - I will not do a copy of `TokenRevocationResponse` and `UserInfoResponse` for WInRT because of one property.
If I try to transform WinRT `HttpErrorStatusCode` to .NET `HttpErrorStatusCode` I will have a conflict of names as both `System.Net.Http` and `Windows.Web.Http` have `HttpClient` etc

**Comment by leastprivilege** [comment]
I really meant what the benefit of the Windows.Web.Http namespace is?

**Comment by xperiandri** [comment]
How would you suggest to solve naming conflicts between `System.Net.Http` and `Windows.Web.Http`?
Imagine that you want to use `IdentityModel.Client` in WinRT but use `Windows.Web.Http` version of HttpClient.
You write `using IdentityModel.Client;` and got all the stuff for `System.Net.Http` opened. But you don't need `System.Net.Http` related stuff, only `Windows.Web.Http` related.

**Comment by leastprivilege** [comment]
I don't follow sorry. 

Can you explain what the benefit is of using Windows.Web.Http at all?

**Comment by xperiandri** [comment]
It is a native API. It has some enhancements comparing to .NET version like device wide caching.
And it is faster as it is native.
You can also consume common part of logic from other languages and proivide to other languages like C++ and JS when creating WinRT or UWP.

**Comment by xperiandri** [comment]
I always prefer Windows.Web.Http in my projects if possible

**Comment by leastprivilege** [comment]
Well - identitymodel targets netstandard - and that supports WinRT.

I would expect that the WinRT version of the netstandard HttpClient would use the native WinRT implementation under the covers. But I don't know for sure.

In any case - I have no plans to change identitymodel to specifically support WinRT APIs.

**Comment by xperiandri** [comment]
No, it will not. Because `Windows.Web.Http` is not a .NET.
Then I will have to release my own mods of `IdentityModel` and `IdentityModel.OidcClient` as I want to use OpenId Connect within UWP using native HttpClient

**Comment by leastprivilege** [comment]
So can you prove that the UWP version does not use the native API?

And I still don't get what that buys you for the OIDC communication?

**Comment by xperiandri** [comment]
UWP gives you 2 options:
1. .NET HttpClient to reuse existing .NET libraries.
2. Windows Runtime native HttpClient, that have some enhansments and able to interoperate with other WinRT languages and libraries.

I prefere second one as it is faster and gives you additional benefits.

**Comment by leastprivilege** [comment]
I think you are misunderstanding me - I am not targeting either of those - I am targeting netstandard.

To which implementation this translates I don't know. But it is not my job to use different platform specific implementations anymore.

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by xperiandri** [comment]
You misundersanding me to.
Because I tell you that if you use the same namespace for generic stuff and for HttpClient stuff you create a problem of using WinRT stuff with your library.
This is a main point.

**Comment by leastprivilege** [comment]
So what **exactly** do you want me to do?

**Comment by xperiandri** [comment]
Tell me which namespace would you prefer for IdentityModel stuff for .NET and for IdentityModel stuff for WinRT. And I will prepare a pull request soon.

**Comment by xperiandri** [comment]
Made a draft pull request at https://github.com/IdentityModel/IdentityModelv2/pull/17

**Comment by leastprivilege** [comment]
OK - I finally understand.

This is exactly what I wanted to avoid. I also don't want to maintain multiple versions of the API. I also still don't see the benefits.

Feel free to fork IdentityModel and do your own WinRT specific implementation.
