### ISSUE TITLE
Intuit's Oauth2 support-Request 7- AuthorizeReponse and RefreshTokenResponse blockers

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#164]
HI Team,

I am back from my parental leave and was working on releasing the changes in our Oauth2 SDK using the IdentityModel binary. 
We have a bit of a catch situation here which I would like to discuss with you first in using AuthorizeResponse and RefreshTokenResponse.
Our existing implementation exposes AuthorizeResponse->RealmId property, eg: authorizeResponse.RealmId
and 
RefreshTokenResponse->RefreshTokenExpiry(x_refresh_token_expires_in) property.

All our devs are currently using these properties in their code and if I create extension methods for GetRealmId on AuthorizeResponse and GetRefreshTOkenExpiry on RefreshTokenResponse, it would mean breaking all the developer sample apps.
I can create a local version of the AuthorizeResponse and RefreshTokenResponse to overcome this prob of adding additional properties to avoid breaking their code but that would defeat the purpose of using the IdentityModel binaries. 
Are there any other options I can use? ANy suggestions? Thanks in advance.

Nimisha

**Comment by leastprivilege** [comment]
Hi, 

i understand. We cannot put proprietary properties on our classes. And unfortunately C# has no extension properties.

So either do a breaking change - or internalize the relevant classes for the time being (and then make a breaking change when you can).

**Comment by nimisha84** [comment]
Thanks, let me do that. I will hopefully be able to release this change by Nov 15th most probably as we have our QBC 2018 until next week and we cannot deploy any change.
