### ISSUE TITLE
Intuit's Oauth2 support-Request 8- Support required for response headers for diff response types.

### ISSUE THREAD

**Issue by nimisha84** [DuendeArchive/IdentityModel#165]
This is more of an enhancement request and not a requirement for releasing Intuit's Oauth SDK using IdentitModel2 binaries. Can you expose Response Header values for each Response type as we have additional headers returned in response which we would like to track?

Thanks!

**Comment by leastprivilege** [comment]
OK - feel free to do an example PR for one of the responses. So we can discuss.

**Comment by leastprivilege** [comment]
Headers support will be in v4.

There's a branch called `v4` - have a look if you want - now is the time to discuss features.
