### ISSUE TITLE
Dictionary property for non-standard extensions

### ISSUE THREAD

**Issue by vanillajonathan** [DuendeArchive/IdentityModel#166]
The `RegistrationRequest` class could have a `IDictionary` property for adding key-values to be sent along with the request for non-standard extensions.

Example:
```cs
var request = new RegistrationRequest
{
    ClientName = "example",
    // ...
};
request.Extensions.Add("scope", "openid profile billing");
```

**Comment by leastprivilege** [comment]
Good idea. Feel free to PR - including tests please. thanks!

**Comment by vanillajonathan** [comment]
This would need the addition of a public property to the  `RegistrationRequest` model.
```cs
[JsonProperty(PropertyName = "extensions", DefaultValueHandling = DefaultValueHandling.Ignore, NullValueHandling = NullValueHandling.Ignore)]
public IDictionary<string, object> Extensions { get; set; }
```

Since this just ends up getting serialized anyways, another way for the user to accomplish this would be through inheritance.
Example:
```cs
public class MyRegistrationRequest : RegistrationRequest
{
    [JsonProperty(PropertyName = "claims", DefaultValueHandling = DefaultValueHandling.Ignore, NullValueHandling = NullValueHandling.Ignore)]
    public IDictionary<string, string> Claims { get; set; }

    [JsonProperty(PropertyName = "scope", DefaultValueHandling = DefaultValueHandling.Ignore, NullValueHandling = NullValueHandling.Ignore)]
    public string Scope { get; set; }
}
```

**Comment by leastprivilege** [comment]
I actually like the sub-classing approach since it gives you much more control.

**Comment by vanillajonathan** [comment]
It might not be obvious that subclassing is an approach, since I had to look at the source code to see the whole object just gets serialized. While this is a valid approach, perhaps this could be documented.

**Comment by leastprivilege** [comment]
Good point....I just realized that there are no docs at all about client reg

https://identitymodel.readthedocs.io/en/latest/

**Comment by leastprivilege** [comment]
I updated the docs. Feel free to do a PR if more information is needed

https://identitymodel.readthedocs.io/en/latest/client/dynamic_registration.html

**Comment by vanillajonathan** [comment]
I saw that the `DynamicClientRegistrationRequest` class inherits from the [`ProtocolRequest`](https://github.com/IdentityModel/IdentityModel/blob/master/src/Client/Messages/ProtocolRequest.cs) class which have a `Parameters` property that is a `Dictionary<string, string>`, maybe that could be used as an alternative to adding non-standard extensions through sub-classing/inheritance.
