### ISSUE TITLE
Swagger - Open Api scaffolding

### ISSUE THREAD

**Issue by AlbertoLeon** [DuendeArchive/IdentityModel#167]
Hi,
I´ve used a swagger generated c# client for an api offering swagger specification recently.
It uses RestSharp in a very weird way and without any good pattern between RestSharp for .Net or .Net Core. If you try to modify the code to support .Net Core by your own the number of updates needed are prohibitive.

I think that to count with a TokenClient integrated instead RestSharp in the Swagger Generator could benefit a lot the automation of a csharp REST Client generated and help IdentityModel to spread it´s usage:
1. Easy way to support REST apis protected by Bearer Token in C#
2. Promotion of the usage of TokenClient, that It´s better than RestSharp (In security meaning).

Are there any approaches currently? What do you think about that?

**Comment by leastprivilege** [comment]
Hey, 

token client is just a helper to request tokens - everything else is out of scope for IdentityModel. Go an build something great with that ;)
