### ISSUE TITLE
ClientCredentialsHelper should check if ClientId or ClientSecret are not yet added to request

### ISSUE THREAD

**Issue by mantasaudickas** [DuendeArchive/IdentityModel#171]
Hello,

I am using HttpClientTokenRequestExtensions from IdentityModel v3.10.0.
For method RequestTokenAsync I am passing clientId and clientSecret by my self like:

```
var parameters = new Dictionary<string, string>
{
    {"grant_type", "delegation"},
    {"client_id", clientId},
    {"client_secret", clientSecret},
    {"token_hint", userAccessToken},
};

var tokenResponse = await _client
    .RequestTokenAsync(new TokenRequest
    {
        Address = tokensEndpoint,
        ClientId = clientId,
        ClientSecret = clientSecret,
        GrantType = "delegation",
        Parameters = parameters
    }, cancellationToken)
    .ConfigureAwait(false);
```

I am aware that I am duplicating stuff.. however having the code like above will throw exception:

```An item with the same key has already been added. Key: client_id```

Short investigation showed that ClientCredentialsHelper does not check if parameters are already added which causes this exception:
https://github.com/IdentityModel/IdentityModel2/blob/master/src/Internal/ClientCredentialsHelper.cs#L32

However its fine with GranType, which is checked and added in RequestTokenAsync method:
https://github.com/IdentityModel/IdentityModel2/blob/master/src/Client/New/HttpClientTokenRequestExtensions.cs#L115
```
if (!request.Parameters.ContainsKey(OidcConstants.TokenRequest.GrantType))
{
    request.Parameters.AddRequired(OidcConstants.TokenRequest.GrantType, request.GrantType);
}
```

I guess should be the same also with other arguments.

**Comment by leastprivilege** [comment]
And why are you doing that?

**Comment by leastprivilege** [comment]
and what should have precedence in your opinion - the properties on the class or the dictionary values?

**Comment by mantasaudickas** [comment]
Well.. I was just migrating code away from obsolete TokenClient class and simply replaced RequestTokenAsync call with new HttpClient extension method which obviously was wrong and caused exception.

**Comment by mantasaudickas** [comment]
Not sure about precedence here.. but if I understand right, values from dictionary are added first and later goes values from request, so only check is missing to avoid dictionary error (which means priority goes to parameters dictionary).
However I am fine with any of these, I already remove these values from properties dictionary, but from library API perspective maybe it should not cause the error, or should be better described.

**Comment by leastprivilege** [comment]
and what should have precedence in your opinion - the properties on the class or the dictionary values?

**Comment by leastprivilege** [comment]
I am doing a more defensive check now. thanks for reporting.
