### ISSUE TITLE
System.ArgumentException when calling RequestClientCredentialsTokenAsync twice on the same HttpClient instance

### ISSUE THREAD

**Issue by marcelstuder** [DuendeArchive/IdentityModel#173]
After switching from the obsoleted TokenClient class to the new extension methods the second call to RequestClientCredentialsTokenAsync on the same HttpClient instance fails with an exception:  System.ArgumentException: "An item with the same key has already been added. Key: scope".

I was able to reproduce the behaviour by adding the code below to the https://github.com/IdentityServer/IdentityServer4.Samples project:

```
public static async Task Main()
{
	Console.Title = "Console Client Credentials Flow";

	await PossibleBugRepro();
}

static async Task PossibleBugRepro()
{
	using (var tokenClient = new TokenClient(address: $"{Constants.Authority}/connect/token", clientId: "client", clientSecret: "secret"))
	{
		var t1 = await tokenClient.RequestClientCredentialsAsync("api1");
		Console.WriteLine(t1.AccessToken);
		var t2 = await tokenClient.RequestClientCredentialsAsync("api1");
		Console.WriteLine(t2.AccessToken);
	}

	using (var client = new HttpClient { BaseAddress = new Uri(Constants.Authority)})
	{
		var tokenRequest = new ClientCredentialsTokenRequest {
			Address = "/connect/token",
			ClientId = "client",
			ClientSecret = "secret",
			Scope = "api1"
		};

		var t1 = await client.RequestClientCredentialsTokenAsync(tokenRequest);
		Console.WriteLine(t1.AccessToken);
		// the second call fails with the following exception: 'An item with the same key has already been added. Key: scope'
		var t2 = await client.RequestClientCredentialsTokenAsync(tokenRequest);
		Console.WriteLine(t2.AccessToken);
	}
}

```

The side-by-side comparison shows that the obsoleted TokenClient class can handle two successive calls to obtain an access token without any issues whereas the new extension method produces an exception on the second call.

Side note: some of the projects I'm working on haven't yet been migrated to ASP.NET Core 2.1 so we can't make use of the newly introduced HttpClientFactory yet. But we still try to avoid socket exhaustion by reusing http clients where possible.
See: https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore
and: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

**Comment by leastprivilege** [comment]
Hi, 

thanks for reporting. I never tested it like this because I don't use it like this myself.

I will fix it - for now, don't re-use the TokenRequest instances to fix it.

**Comment by marcelstuder** [comment]
Hi

Your suggestion (not re-using TokenRequest instances) just saved my day :-)

Thank you for taking the time to look into this issue so quickly!

**Comment by leastprivilege** [comment]
all checked in. will do a patch release soon.
