### ISSUE TITLE
Blocking from new HttpClient extensions

### ISSUE THREAD

**Issue by dbrink** [DuendeArchive/IdentityModel#174]
I'm getting timeouts due to blocking when calling HttpClientTokenRequestExtensions.RequestClientCredentialsTokenAsync via synchronous code higher in the call stack.  Shouldn't the convenience methods for the various grant types also have .ConfigureAwait(false)?  If so, it also looks like HttpClientDiscoverExtensions may have the same issue.

`        
            return await client.RequestTokenAsync(clone, cancellationToken).ConfigureAwait(false)
`

**Comment by leastprivilege** [comment]
I'll have a look.

**Comment by leastprivilege** [comment]
I just published an update to nuget. Please give it a try.

**Comment by dbrink** [comment]
Thanks, after a bit of smoke testing it looks like this does the trick.
