### ISSUE TITLE
Could not load type 'IdentityModel.Client.DiscoveryResponse'

### ISSUE THREAD

**Issue by markns** [DuendeArchive/IdentityModel#175]
Using the WinForms sample with the "bowmore" pre-release, I run into the following exception. 

System.TypeLoadException: 'Could not load type 'IdentityModel.Client.DiscoveryResponse' from assembly 'IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'.'

.Net Framework 4.6.1

Trying to get more details from the Assembly Binding Log Viewer, but I've not used this tool before, and nothing is showing up at the moment.

(ps. using pre-release to get the `DelegatingHandler` change)

**Comment by leastprivilege** [comment]
Why are you using IdentityModel 4.0 ?

**Comment by markns** [comment]
Sorry, I updated my comment a few moments ago to address that:
> using pre-release to get the DelegatingHandler change

If it's really not ready, please just close the issue. I just was struggling to convert the HttpMessageHandler to a DelegatingHandler, saw a few issues and the work on v4 and thought I'd give it a go...

**Comment by leastprivilege** [comment]
Which sample are you talking about - and which bowmore release of which package?

**Comment by markns** [comment]
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView
https://www.nuget.org/packages/IdentityModel.OidcClient/3.0.0-bowmore
https://www.nuget.org/packages/IdentityModel/4.0.0-bowmore

**Comment by leastprivilege** [comment]
Exactly my point - 

OidcClient 3 has a dependency on IdentityModel 3. That's the combination that works.
IdentityModel 4 has breaking changes, that does not work.

So I suggest you don't update to the latest IdentityModel.

**Comment by markns** [comment]
Aha, thanks - working perfectly now! Apologies for the misunderstanding.
