### ISSUE TITLE
Cancellation exception shouldn't be wrapped in a TokenResponse

### ISSUE THREAD

**Issue by thomaslevesque** [DuendeArchive/IdentityModel#176]
Currently, `TokenClient` [wraps all exceptions in a `TokenResponse`](https://github.com/IdentityModel/IdentityModel2/blob/1a0e6ba202ef034a20062359f8e997606ea216a7/src/Client/Old/TokenClient.cs#L177-L184). However, certain exceptions should be allowed to bubble up until caught, in particular `OperationCanceledException`. It's really counter-intuitive to have to inspect the `TokenResponse.Exception` to detect if the operation was canceled.

So the code should probably be something like this:

            try
            {
                response = await Client.SendAsync(request, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception ex) when (!(ex is OperationCanceledException))
            {
                return new TokenResponse(ex);
            }

On a more general note, I think wrapping exceptions at all is a mistake, because:
- it adds no value
- the exception can't be caught and/or filtered, it has to be examined via the `TokenResponse.Exception` property
- users typically won't expect that, and will try to catch an exception that will never actually be thrown (especially since it's not documented, users will probably assume the method can throw)

Of course, I realize that changing that would be a breaking change, but it would be nice to consider changing this for the next major version.

**Comment by leastprivilege** [comment]
I've been thinking about this recently - and considering it for a future version. I will leave this issue open.

thanks!

**Comment by The-Futurist** [comment]
@leastprivilege @MattewSteeples @thomaslevesque 

I'm looking at an older use of this library and when I updated to the latest version of IdentityModel (6.0.0) I find the following problems:

1. The constructor for `TokenResponse(Exception)` has gone, so what is the replacement logic/pattern?
2. `CryptoRandom.CreateRandomKeyString(int)` has gone, so what is the replacement logic/pattern?

Thanks in advance!

**Comment by The-Futurist** [comment]
OK I see that `CreateRandomKeyString `can be replaced with `Base64Url.Encode(CryptoRandom.CreateRandomKey(32))`.
