### ISSUE TITLE
Rename TokenClientExtensions.Request*Async

### ISSUE THREAD

**Issue by thomaslevesque** [DuendeArchive/IdentityModel#177]
`TokenClient` has several extension methods whose names are misleading:
- `RequestAuthorizationCodeAsync`
- `RequestRefreshTokenAsync`
- `RequestClientCredentialsAsync`
- `RequestResourceOwnerPasswordAsync`
- etc

The method names seem to imply that the method "requests an authorization code" or "requests a refresh token", which is not true. It actually requests a token using an authorization code, or a refresh token.

Since I see there's a new major version in the works, it could be an opportunity to take the breaking change and rename those methods to something more accurate.

**Comment by leastprivilege** [comment]
TokenClient is deprecated.

If you want to review code, use the v4 branch.

thanks!

**Comment by thomaslevesque** [comment]
Thanks @leastprivilege 

> TokenClient is deprecated.
> 
> If you want to review code, use the v4 branch.

What is used instead of `TokenClient` then? I still see it in the v4 branch. It looks like the extension methods I mentioned are now instance methods, but they still have misleading names.

**Comment by leastprivilege** [comment]
All client logic has been moved to extension methods for HttpClient. TokenClient in v4 currently is a prototype

**Comment by leastprivilege** [comment]
Well - naming is hard. I guess we have to agree to disagree here ;)

**Comment by thomaslevesque** [comment]
> Well - naming is hard

Indeed it is. But don't you think something like `RequestTokenUsingAuthorizationCode` would be less confusing?
Maybe ask around you and see what people think :wink:
