### ISSUE TITLE
Abstractions to support HttpClient-incompatible platforms

### ISSUE THREAD

**Issue by Brice-xCIT** [DuendeArchive/IdentityModel#178]
Hello. I integrated this great lib into Unity3d in order to support various auth flows such as client credentials and OpenID connect. Sadly, not all platforms that Unity3d targets support HttpClient: although the class is indeed part of the available API surface, HttpClient methods throw exceptions at runtime because of their internal use of forbidden threading methods (to precise: any kind of multithreading, e.g. Timer, cannot work on WebGL, and HttpClient happens to use just that).

My strategy was to fork IdentityModel2 and add a class abstracting an HttpClient, and replace most instances of HttpClient in the code with this AbstractHttpClient. A default implementation of AbstractHttpClient is provided for backward compatibility with platforms which do support HttpClient. But on platforms which don't, it is possible to extend this AbstractHttpClient to integrate with other networking stacks (e.g. UnityWebRequest).

You will find the fork at https://github.com/xcit-lab/IdentityModel2.Abstract/tree/v4. My question is would you be interested to integrate this feature into the main lib? In terms of API design, is that something that you feel would be relevant?

**Comment by brockallen** [comment]
Does Microsoft have anything along these lines already?

**Comment by Brice-xCIT** [comment]
Within Netstandard 2.0 the only thing I could find was implementing my own HttpMessageHandler.
I could almost have gone away with implementing an HttpMessageInvoker and use the lib's extensions methods, sadly I needed to use a couple of methods that you implemented to use HttpClient explicitly (as far as I can see, in order to set timeouts and default request headers).
Was that your question?

**Comment by leastprivilege** [comment]
Besides the discovery extension methods where thing are bit trickier - all the new extensions use HttpMessageInvoker.

The old client classes like e.g. TokenClient are already deprecated and will be removed in v4.

**Comment by Brice-xCIT** [comment]
Right. I'm already using the extensions of v4 (I implemented the abstractions within the v4 branch). But I also need the discovery extension methods, precisely where it's tricky...
The AbstractHttpClient class does extend HttpMessageInvoker so that the extensions could be used easily.

Talking about these discovery extensions, why do they need HttpClient specifically? Could there be a variant of those targetting HttpMessageInvoker directly?

**Comment by leastprivilege** [comment]
Discovery is tricky because it requires some state. This might be fixable with heavier re-factoring. I didn't have the time yet.

I don't feel like adding an HTTP client abstraction beyond HttpMessageInvoker. NetStandard should fix that.

**Comment by Brice-xCIT** [comment]
> NetStandard should fix that.

I agree.
I'd be fine ditching the abstractions if the discovery extensions would be invokable on HttpMessageInvoker directly.

**Comment by leastprivilege** [comment]
Have a look yourself...

**Comment by Brice-xCIT** [comment]
> Have a look yourself...

If I figure something out without the abstractions, I will open a pull request then.

**Comment by Brice-xCIT** [comment]
So, it turns out after updating the v4 branch that this refactor was much easier than it used to. I submitted a pull request.

**Comment by Brice-xCIT** [comment]
Fixed in v4 branch. Thanks!
