### ISSUE TITLE
Split library into 2 packages

### ISSUE THREAD

**Issue by xperiandri** [DuendeArchive/IdentityModel#18]
To continue our discussion about WinRT support.
What if we split a library into two parts:
1. Common classes that are not relay on `System.Net.Http`
2. Your logic specific to `System.Net.Http`

In this case I will be able to provide my own package for WinRT with logic specific to `Windows.Net.Http`

Only 2 changes required except splitting into 2 projects:
1. Specify sub namespace for classes specific to `System.Net.Http`
2. Expose HttpCode as a number but not Enum. And an extension method that return enum from number.

**Comment by leastprivilege** [comment]
Sorry - I like the simplicity of IdentityModel the way it is.

And I'll say it for one last time - I don't see any benefits in using the WinRT specific APIs for OAuth (e.g. there isn't even any caching involved). Netstandard works fine on UWP.

Feel free to fork it.
