### ISSUE TITLE
Error calling GetDiscoveryDocumentAsync 

### ISSUE THREAD

**Issue by fawadali123** [DuendeArchive/IdentityModel#183]
I am trying to deploy IDS4 on the server. everything works fine both on http and https. but when i try to access client.GetDiscoveryDocumentAsync(IDPBaseURL). it returns error. if it is on http is says https required. if on https it gives error The remote certificate is invalid according to the validation procedure. 
for some reason, I have to get token using Client Credentials.

I am calling /connect/token from within the IDS and it was unable throwing this error. but calling /connect/token from any outside origin (added in allowed Origin) still works fine.

Thanks,

**Comment by leastprivilege** [comment]
You can change the HTTPS requirement on the policy settings.

But the real problem is that your certificates are not correctly configured. You don't seem to trust the server certificate on the machine that makes the call.

**Comment by fawadali123** [comment]
It does not even work on the server itself.  

here is the code :
CODE :
     `private HttpClient GetAuthorizationContext()`
        `{`
            `string IDPBaseURL = configuration["endpoints:Base_Address"];`
            `var client = new HttpClient();`
            `var disco = client.GetDiscoveryDocumentAsync(IDPBaseURL).Result;   // ERROR HERE`
           ` if (!disco.IsError)`
           `{`
                `var response = client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest`
                `{`
                   ` Address = disco.TokenEndpoint,`
                    `ClientId = "MyClient",`
                   ` ClientSecret = "MyClient_secret",`
                    `Scope = "api"`
               ` }).Result;`
               ` if (!response.IsError)`
               ` {`
                    `client.SetBearerToken(response.AccessToken);`
               ` }`
           ` }`
           ` return client;`
        `}`

**Comment by leastprivilege** [comment]
Which isn't mutually exclusive with what I said above.

**Comment by fawadali123** [comment]
Ok. I will check the HTTPS.

but Let try to explain in a bit more:
I have the following project structure
1- API 
2- Angular App
3. IDP (IdentityServer4)
4. Legacy Apps

same code mentioned above is accessible from the Legacy Apps and it returns a token. it just don't work when i call it from within the IDP Project to get a token using Client Credentials.

**Comment by leastprivilege** [comment]
> The remote certificate is invalid according to the validation procedure.

Is a very clear error message. It's about your HTTPS setup.

I can't help you with that.
