### ISSUE TITLE
Missing default port should not affect issuer name validation

### ISSUE THREAD

**Issue by Dreamescaper** [DuendeArchive/IdentityModel#191]
When we wan't to get discovery response, we use Uri object for address, and call .ToString() when passing it to DiscoveryDocumentRequest. 

Now problem is that Uri.ToString() does not output default port (see [here](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWAChjUBmbHANmwCZKB2TAb2M3ewtxtQBZMAsgEMAllAAUAShZsOcqAFMA7pgCqYEeIBEAC2DAADiAD0xkXAC0AZwVgAbiAAc6LZIB0AFQD2AZWAaoAHMpNwBJKCsDBQBjYClCIjk5cUUVdU1dfSNTc2tbB2dXTABeYsxUtQ1tPUMTM0sbe2NXd3DImLjJBLkAX2IeoA==)). Therefore, issuer name validation fails, as `http://id-serv/` != `http://id-serv:80`, according to current validation logic.

Question is - should it be taken into account? Should those be considered equal?

**Comment by leastprivilege** [comment]
Thanks for reporting. 

I can look into that. Or you.

**Comment by leastprivilege** [comment]
If you want to fix that, please go ahead.

**Comment by Dreamescaper** [comment]
I can see that described case _is_ handled already. 
Apparently, my issue is something else. 
Looking...

**Comment by Dreamescaper** [comment]
OK, I found the issue, and it's completely unrelated, sorry for confusion.

Thing is that we use Uri object, and call .ToString() when passing it to DiscoveryDocumentRequest. Now problem is that Uri.ToString() does not output default port (see [here](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWAChjUBmbHANmwCZKB2TAb2M3ewtxtQBZMAsgEMAllAAUAShZsOcqAFMA7pgCqYEeIBEAC2DAADiAD0xkXAC0AZwVgAbiAAc6LZIB0AFQD2AZWAaoAHMpNwBJKCsDBQBjYClCIjk5cUUVdU1dfSNTc2tbB2dXTABeYsxUtQ1tPUMTM0sbe2NXd3DImLjJBLkAX2IeoA==)).

Question is - should it be taken into account?
I can submit PR to compare `Issuer` and `policy.Authority` as `Uri` objects to fix that, but that will lead to issue - AuthorityNameComparison property will make no sense then - it will always be ignoring case.

**Comment by leastprivilege** [comment]
The specs always use the word "match" - and not "semantically match" - so I rather think of string comparisons. Hence we don't use the URI class...
