### ISSUE TITLE
AccessTokenHandler+ HttpClientFactory + Microsoft Graph

### ISSUE THREAD

**Issue by Artourou** [DuendeArchive/IdentityModel#192]
Hi,
I just discovered your library yesterday and I wonder how to use it with Microsoft Graph,
in fact, I had a httpClient configured with to access Graph this way :

 var provider = CreateProvider();  // do some stuff to get token bearer and update header
var _httpClient = new HttpClient(new AuthenticationHandler(provider , new HttpClientHandler()));

I want to use HttpClientFactory Instead  (an httpClientFactory that can produce an authenticated HttpClient)  : 

 services
 .AddHttpClient("MicrosoftGraphClient")
 .AddHttpMessageHandler(() => new AccessTokenDelegatingHandler(
"https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token",
 "client",
 "secret",
 "scope"));

But this return always 401 unauthorized.

I followed the answer in this issue  https://github.com/IdentityModel/IdentityModel2/issues/109 but it didn't resolve my my problem.

I wonder if I missed something  or Identity2 doesn't support Microsoft Graph,

Thanks in advance.

**Comment by leastprivilege** [comment]
The access token handler is not really compatible with the HTTP client factory because it holds internal state. It was not designed for that.
