### ISSUE TITLE
code is getting excited while calling GetDiscoveryDocumentAsync(_authorityUrl) using HttpClient

### ISSUE THREAD

**Issue by gittadesushil** [DuendeArchive/IdentityModel#193]
using (var discoveryClient = new HttpClient())
            {
                var discoveryResponse = await discoveryClient.GetDiscoveryDocumentAsync(_authorityUrl);
                var codests = discoveryResponse.StatusCode;

                if (discoveryResponse.IsError)
                {
                    throw new InvalidOperationException("Token endpoint can not be discovered");
                }
                _tokenEndpoint = discoveryResponse.TokenEndpoint;
                return discoveryResponse.TokenEndpoint;
            }

When _await discoveryClient.GetDiscoveryDocumentAsync(_authorityUrl);_ executes rest of the lines are not getting executed. GetDiscoveryDocumentAsync method call is coming outside.

**Comment by leastprivilege** [comment]
I don't follow.

**Comment by kolbasik** [comment]
Hi @gittadesushil , I have made an example app with your code and it works fine.
```csharp
using System;
using System.Net.Http;
using System.Threading.Tasks;
using IdentityModel.Client;

namespace IdentityModel2App
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            var tokenEndpoint = GetTokenEndpointAsync("https://demo.identityserver.io/").GetAwaiter().GetResult();
            Console.WriteLine($"tokenEndpoint: {tokenEndpoint}");

            Console.WriteLine("Press any key...");
            Console.ReadKey(true);
        }

        private static async Task<string> GetTokenEndpointAsync(string authority)
        {
            using (var discoveryClient = new HttpClient())
            {
                var discoveryResponse = await discoveryClient.GetDiscoveryDocumentAsync(authority);
                if (discoveryResponse.IsError)
                {
                    throw new InvalidOperationException("Token endpoint can not be discovered");
                }
                return discoveryResponse.TokenEndpoint;
            }
        }
    }
}
```

The biggest chance is that the real issue with `SynchronizationContext` which `.net` captures by default during `await` operation until you say it explicitly not to do it by using `.ConfigureAwait(false)`.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
