### ISSUE TITLE
Allow setting the HttpRequestMessage.Properties from all IdentityModel requests

### ISSUE THREAD

**Issue by kevinlo** [DuendeArchive/IdentityModel#194]
Polly has the execution [Context ](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/) and the HttpClientFactory has the [HttpRequestMessageExtensions ](https://github.com/aspnet/HttpClientFactory/blob/master/src/Microsoft.Extensions.Http.Polly/HttpRequestMessageExtensions.cs) to set the context to the HttpRequestMessage.Properties.

It is great that each Request under IdentityModel.Client provide the Properties property so that the HttpClient extension can populate the Properties to the HttpRequestMessage to pass the context to the Polly Policies.   One usage of it is to [pass the ILogger to the Polly Policies](https://www.stevejgordon.co.uk/passing-an-ilogger-to-polly-policies).

**Comment by leastprivilege** [comment]
I don't follow.

**Comment by kevinlo** [comment]
Ok.  Let me give an example of it.

The following codes in Startup.ConfigServices setup the named HttpClient "MyHttpClient" with the Polly retry policy where it logs the warning in each retry

```
services.AddHttpClient("MyHttpClient")
    .AddTransientHttpErrorPolicy(builder => builder.WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(i * 2), (result, timeSpan, retryCount, context) =>
    {
        _logger.LogWarning($"Client request failed status code {(int)result.Result.StatusCode}. Waiting {timeSpan} before next retry. Retry attempt {retryCount}");
    }))
    .AddPolicyHandler(timeoutPolicy);
```
Because it is using the _logger in the Startup class, it will be logged like this with the [Startup] category:

>2019-03-11 15:27:09,290 -07:00 WARN  [Startup] client request failed status code 500. Waiting 00:00:10 before next retry. Retry attempt 3 - [0HLL6E2MPVLP3:00000002 11928:3  ]

It is better to log it under the category of the class/controller using that "MyHttpClient".  

So, in the controller using that "MyHttpClient", it can create a Polly Context and set the _logger to it and the set this Context to the HttpRequestMessage's Properties by calling the SetPolicyExecutionContext.

```
public MyController(ILogger logger, IHttpClientFactory httpClientFactory)
{
    _logger = logger;
    _httpClientFactory = httpClientFactory;
}                    
    
public async Task<string> SendAsync(string httpMethod, string strReqUrl)
{
    // Set the MyController logger to the Polly Context
    HttpRequestMessage requestMessage = new HttpRequestMessage(httpMethod, strReqUrl);
    var context = new Polly.Context();
    context["MyLogger"] = _logger;
    requestMessage.SetPolicyExecutionContext(context);
    
    var client = _httpClientFactory.CreateClient("MyHttpClient");
    HttpResponseMessage response = await client.SendAsync(requestMessage).ConfigureAwait(false);
    response.EnsureSuccessStatusCode();
    return await response.Content.ReadAsStringAsync();
}

```

In the Startup.ConfigServices,  it get the ILogger from the Polly context to the the message using the MyController's ILogger.

```
services.AddHttpClient("MyHttpClient")
        .AddTransientHttpErrorPolicy(builder => builder.WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(i * 2), (result, timeSpan, retryCount, context) =>
        {
            ILogger logger = context["MyLogger"] as ILogger;
            if (logger == null)
            {
                logger = _logger;
            }
            logger.LogWarning($"Client request {result.Result.RequestMessage} failed status code {(int)result.Result.StatusCode}. Waiting {timeSpan} before next retry. Retry attempt {retryCount}");
        }))
        .AddPolicyHandler(timeoutPolicy);
```
The message will be logged under the MyController category:

>         2019-03-11 15:27:09,290 -07:00 WARN  [MyController] client request failed status code 500. Waiting 00:00:10 before next retry. Retry attempt 3 - [0HLL6E2MPVLP3:00000002 11928:3  ]

So, I expect the IdentityModel requests (e.g. DiscoveryRequest, ClientCredentialsTokenRequest...etc_) provide a Properties field and/or the Polly SetPolicyExecutionContext/GetPolicyExecutionContext function so I can do something like this:

```
internal static readonly string PolicyExecutionContextKey = "PolicyExecutionContext";

var context = new Polly.Context();
context["MyLogger"] = _logger;
    
var discoveryDocumentRequest = new DiscoveryDocumentRequest()
{
    Address = myUri,
    Policy = discoveryPolicy,
    Properties[PolicyExecutionContextKey] = context
};

var discoveryClient = _httpClientFactory.CreateClient(Constants.IDENTITYSERVER_HTTPCLIENT);
var disco = await discoveryClient.GetDiscoveryDocumentAsync(discoveryDocumentRequest);
```

Does it make sense?   Let me know if you know any workaround to do it now.

**Comment by kolbasik** [comment]
Hi @kevinlo, I would not suggest to pass the logger through all layers of the application. It might easily make your code complicated to support in future.
If you need to find related logs, the best way is to use Logger Context and CorrelationID like here: https://nblumhardt.com/2016/08/context-and-correlation-structured-logging-concepts-in-net-5/. 
But it you really need to do it you can use AsyncLocal to store your Logger and use it later during code execution without modifying all third party libraries: https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netframework-4.7.2

**Comment by kevinlo** [comment]
@kolbasik Thanks for your reply.  Firstly, passing the Logger to the Context is suggested by Steve Gordon at [pass the ILogger to the Polly Policies](https://www.stevejgordon.co.uk/passing-an-ilogger-to-polly-policies).   I don't get what's wrong with passing the Logger to the Context.  One purpose of the context is to passing data around.

Can you give an example how you use the Logger Context and CorrelationID to work with Polly?

Secondly, passing logger is just an example.  It can be passing other data around.  The current IdentityModel HttpClient extention does not provide a way to set the HttpRequestMessage.Properties.

**Comment by leastprivilege** [comment]
OK - will add a way to propagate properties.

**Comment by leastprivilege** [comment]
v3 is done. Will be added in v4

**Comment by kevinlo** [comment]
@leastprivilege Can you also propagate the headers in the request and response too?   I want to add the "X-Request-Id" or "X-Correlation-Id" header.

**Comment by leastprivilege** [comment]
You would do that using HTTP message handlers.

**Comment by leastprivilege** [comment]
I made a fundamental change that will enable all of these scenarios I think. Have a look 

https://github.com/IdentityModel/IdentityModel2/pull/205

**Comment by kevinlo** [comment]
@leastprivilege You do make some big change since 3.10.0 that I am using.  I need some time to understand what you are doing.    

For the HTTP message handlers suggestion, do you mean ConfigurePrimaryHttpMessageHandler to my custom HttpMessageHandler and override the SendAsync to set the headers?

**Comment by leastprivilege** [comment]
yes. something like that.

Closing as this is fixed in v4.
