### ISSUE TITLE
Setting the StatusCode on a TokenResponse does not set IsError

### ISSUE THREAD

**Issue by grantbowering** [DuendeArchive/IdentityModel#196]
If one does, say,
`var tokenResponse = new TokenResponse(HttpStatusCode.Unauthorized, "", "");`
then `tokenResponse.IsError` is **_FALSE_**, which I think is unexpected.
`var tokenResponse = new TokenResponse(HttpStatusCode.Unauthorized, "reason must also be set for IsError to be true", "");`
It's not a big deal, but it was confusing for writing unit tests, in which I didn't care what the reason being returned was (and have no way of confirming that the reason is always set by the IdentityServer being mocked).

**Comment by leastprivilege** [comment]
OK - I see. I have no plans to change that anymore in 3.x - we will soon switch to 4.x

If you have time, have a look if the 4.x model would work for your tests.

**Comment by leastprivilege** [comment]
I won't change any behavior anymore for v3. Will switch to v4 very soon.
