### ISSUE TITLE
IdentityModel 3.10.8 Assembly Version Downgrade

### ISSUE THREAD

**Issue by jadanah** [DuendeArchive/IdentityModel#199]
Since updating to IdentityModel 3.10.8 it seems the Assembly Version has been set to 3.0.0.0 which makes it incompatible with IdentityModel.OidcClient 2.9.0

Build Error:
'IdentityModel.OidcClient' with identity 'IdentityModel.OidcClient, Version=2.9.0.0, Culture=neutral, PublicKeyToken=null' uses 'IdentityModel, Version=3.10.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f' which has a higher version than referenced assembly 'IdentityModel' with identity 'IdentityModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'

**Comment by brockallen** [comment]
Oh shit. We'll look into it.

**Comment by leastprivilege** [comment]
3.10.9 will show up soon. This fixes the problem.

**Comment by jadanah** [comment]
Cheers guys, tested 3.10.9 and it resolves the issue. Thanks for the quick turnaround and keep up the good work :)
