### ISSUE TITLE
Discovery Endpoint caching not working

### ISSUE THREAD

**Issue by majco333** [DuendeArchive/IdentityModel#201]
I follow this demo: https://identitymodel.readthedocs.io/en/latest/client/discovery.html

But when I use cache for HttpClient, discovery request always goes to the IdentityServer. I use Fiddler for it.

**Comment by leastprivilege** [comment]
Can't repro. Send me a gist that repros it against https://demo.identityserver.io

**Comment by leastprivilege** [comment]
Any update?

**Comment by majco333** [comment]
I didn't have time to create a demo :-(

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by flarocca** [comment]
Hello! 

I was able to reproduce the issue. It happens that the DiscoveryCache is not thread safe, then when the app starts under heavy load, there might be cases where multiple threads would await on GetAsync, resulting on multiple request made.
After that, it works as expected.

I tested this scenario under 2 different conditions:
* IIS 10.0 and .Net Framework 4.8: using Autofac registering the service as Singleton
* Docker and .Net Core 3.1: again, registering the service as Singleton

Looking at the code, I see why this is happening:

    public Task<DiscoveryDocumentResponse> GetAsync()
    {
        // If multiple threads get to this point while 
        // the request is being made, a new task per
        // thread will be returned
        if (_nextReload <= DateTime.UtcNow)
        {
            Refresh();
        }

        return _lazyResponse.Value;
    }

    public void Refresh()
    {
        _lazyResponse = new AsyncLazy<DiscoveryDocumentResponse>(GetResponseAsync);
    }
    
Any suggestions?

I really appreciate your help.
Thank you very much!!
