### ISSUE TITLE
Question about jwt validation vs. token introspection 

### ISSUE THREAD

**Issue by rafanoronha** [DuendeArchive/IdentityModel#202]
Hey!
First of all thanks, for all the hard work towards Identity Server and Identity Model, it has been helping me and my customers in different scenarios.
Was wondering if you could help me with guidance on the following decision point:
When I have an authorization server emitting a signed JWT token. As the resource server. Do I have any benefit asking the auth server to introspect the given token instead of barely validating, for example with `JwtSecurityTokenHandler.ValidateToken`?

**Comment by leastprivilege** [comment]
JWTs are designed for validating them independently of the token service. so no benefit.
