### ISSUE TITLE
Why do the discovery endpoints have to be on the same DNS?

### ISSUE THREAD

**Issue by EarthDragon88** [DuendeArchive/IdentityModel#204]
According to the  [documentation](https://identitymodel.readthedocs.io/en/latest/client/discovery.html) the following parts are validated about the discovery response.

1. Enforce that HTTPS is used (except for localhost addresses)
Makes sense, as specified [here](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) in the spec; this has to be https.
2. Enforce that the issuer matches the authority
Makes sense, as specified [here](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation) in the spec; issuer must match authority, that means if the discovery url is `https://example.com/.well-known/openid-configuration` then the issuer must be `https://example.com/`
3. Enforce that the protocol endpoints are on the same DNS name as the authority
I can't find anything about validating endpoints in the spec, why is this done?
4. Enforce the existence of a keyset
Makes sense, as specified [here](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) in the spec, jwks_uri is required.

So, my question is, why are protocol endpoints tested? and why is it enabled by default? did I miss something in the spec or is there something else going on?

**Comment by leastprivilege** [comment]
This was the result of a penetration test one of our customers did. It's just the default, you can disable that validation feature.
