### ISSUE TITLE
IdentityModel use with Xamarin Forms?

### ISSUE THREAD

**Issue by jhunterdfly** [DuendeArchive/IdentityModel#21]
I am looking to evaluate IdentityModel2 for use within a Xamarin Forms application but am running into issues installing the corresponding nuget package due to PCL profile issues.

Issue = "Could not install package 'IdentityModel 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Can you provide me with any direction on how this may have been resolved already, or give me some pointers on how I may resolve this on my own?

**Comment by jhunterdfly** [comment]
as further information, I've checked out the code and am exploring the option of building it in PCL projects to see if that helps.

**Comment by leastprivilege** [comment]
v2 is netstandard - i was under the impression this is working with Xamarin.

v1 is PCL - you can try that

**Comment by jhunterdfly** [comment]
Thanks, reverting to v1 installs correctly.   

I think it'll be more a matter of how to get my Xamarin Forms app PCL projects to work with the netstandard libraries.

Thanks for your quick response!

**Comment by weitzhandler** [comment]
@leastprivilege reading the docs, I can't find the `DiscoveryClient` class in the PCL version (1.13.1).
Is there an alternative to the `DiscoveryClient`?

**Comment by leastprivilege** [comment]
that is true. Feel free to backport it and PR.

**Comment by weitzhandler** [comment]
[There](https://github.com/IdentityModel/IdentityModel/pull/66) you go.

- Will you accept it?
- When can I expect a new version on NuGet?
