### ISSUE TITLE
Documentation for Dynamic Client Registration is wrong

### ISSUE THREAD

**Issue by vanillajonathan** [DuendeArchive/IdentityModel#219]
The documentation mentions a `Document` property on the `DynamicClientRegistrationRequest` class. This property does  not exist, however a `RegistrationRequest` property exists.

The documentation also mentions a `DynamicClientRegistrationDocument` class, but this class does not exist. However a `RegistrationRequest` class exists.

https://identitymodel.readthedocs.io/en/latest/client/dynamic_registration.html

IdentityModel version: 3.10.10

**Comment by leastprivilege** [comment]
The names have been changed slightly between 3 and 4.

Will keep this open to double check once v4 is released.

**Comment by mpyclikcorp** [comment]
So how to use it???
OAuth 2.0 standard says that we have to send POST www-url-encoded request, new client send something else...

**Comment by leastprivilege** [comment]
The tests should have some usage examples...

**Comment by mpyclikcorp** [comment]
Nope... New client send application/json :( So contrary to what the standard says...

**Comment by leastprivilege** [comment]
https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest

**Comment by mpyclikcorp** [comment]
Yes, I've confused couse rest of endpoints are application/x-www-form-urlencoded.
