### ISSUE TITLE
sample RefreshTokenHandler

### ISSUE THREAD

**Issue by mdissel** [DuendeArchive/IdentityModel#22]
What is the purpose of the RefreshTokenHandler? Should I expect something like refreshing the access token when it is expired using the refreshtoken?

**Comment by leastprivilege** [comment]
That's the idea - yes.

**Comment by mdissel** [comment]
But how should I use this function? any sample? i don't see any validation of the expire date time in this handler.

**Comment by leastprivilege** [comment]
It's a handler for an HttpClient.

**Comment by leastprivilege** [comment]
No expiration check needed - when a 401 is returned - that means the token is invalid.
