### ISSUE TITLE
RequestTokenAsync should check client_assertion also when client_id is not int he body

### ISSUE THREAD

**Issue by jaanclaeys** [DuendeArchive/IdentityModel#221]
https://github.com/IdentityModel/IdentityModel/blob/715a9dca23a18a7d38a53e3ca4b02f929c0dfcd8/src/Client/Extensions/HttpClientTokenRequestExtensions.cs#L153

RequestTokenAsync (The clientextension helper) throws invalid operation exception when not presenting client_id, but instead presenting client_assertion 
However in IdentityServer the validation of client_assertion works by getting the client_id from the sub claim of the JWT token. This should also be a valid clientIdentification, and the token request should not have a client_id. Presenting your tokenrequest straight without the extension method to identityserver works.

**Comment by leastprivilege** [comment]
I need to re-read a couple of specs. Maybe IdentityServer is doing it wrong...

**Comment by jaanclaeys** [comment]
I can help you with the part where it states it is optional:
https://tools.ietf.org/html/rfc7521#section-4.2

And this one is referenced in the openid connect spec
So I think IdentityServer is right IMO

**Comment by leastprivilege** [comment]
You are right. I will look into it.

**Comment by leastprivilege** [comment]
done
