### ISSUE TITLE
IdentityServer4 and URL with Uppercase combination

### ISSUE THREAD

**Issue by asharda1** [DuendeArchive/IdentityModel#222]
HI,

We have implemented Identity server 4 and till yet everything was working good, On with the New server the Name of server is Abc.xyz.com, So if this url is used I am getting error "Issuer does not match"
I saw some post related to same and some work is being done for this issue, But by all those post I am not clear where I need to make changes,
I have started with the code sample provided and also implemented  - ProfileServices, RedirectURLvalidator classes

**Comment by leastprivilege** [comment]
This would be an issue for the IdentityServer repo.

**Comment by asharda1** [comment]
I didn't get you "leastprivilege",

Can you please give me code sample where I can make the changes to solve this issue?
Did you mean wrong thread?
