### ISSUE TITLE
DiscoveryPolicy: Issuer/authority name validation is too strict

### ISSUE THREAD

**Issue by eric-b** [DuendeArchive/IdentityModel#226]
The discovery document I consume exposes an issuer name in the form of `https://domain:443/oauth2/`. 

The validation fails when the string comparison is based on `HttpClient` base URL `https://domain/oauth2`. When comparison occurs, the `HttpClient` base URL seems to be simplified. I didn't verified if it's a behavior of `HttpClient` or `DiscoveryEndpoint` (maybe a combination of both), but I cannot currently force the compared URL to `https://domain:443/oauth2/`) without setting explicitly `DiscoveryPolicy.Authority` . I think it would be inconvenient and fragile because I have to have two configuration values (authority base URL *and* a reference string to compare) instead of one (the authority base URL).

I would like to propose a PR with following changes:

- Add a property `AuthorityNameComparisonStrategy`:`IAuthorityNameComparisonStrategy` to `DiscoveryPolicy`.
- Mark the property `DiscoveryPolicy.AuthorityNameComparison` obsolete.
- Implement `StrictAuthorityNameComparisonStrategy` with the current default (`StringComparison.Ordinal`) and use it as default strategy.
- Implement `UrlAuthorityNameComparisonStrategy` to provide a way to validate equivalence between two URLs (based on `URI` equality method plus trailing slash removal).
- Add method `DiscoveryDocumentResponse.ValidateIssuerName(string issuer, string authority, IAuthorityNameComparisonStrategy strategy)`
- Update `DiscoveryDocumentResponse.Validate(DiscoveryPolicy)` to use the strategy for issuer name validation.

Are you ok with this ?

**Comment by leastprivilege** [comment]
If the list also includes

* document at https://identitymodel.readthedocs.io/en/latest/client/discovery.html

Then I am ok with that

**Comment by leastprivilege** [comment]
Oh.   And tests of course :)

**Comment by eric-b** [comment]
Ok, I'll try to push it before the end of the week. :)

**Comment by leastprivilege** [comment]
closing - working on it in PR...
