### ISSUE TITLE
refresh_expires_in is missing in TokenResponse

### ISSUE THREAD

**Issue by mdissel** [DuendeArchive/IdentityModel#23]
The OAuth2 provider can also return a **refresh_expires_in** value to indicate when the RefreshToken expires.

see http://www.keycloak.org/docs/javadocs/index.html?org/keycloak/representations/AccessTokenResponse.html

**Comment by brockallen** [comment]
I don't see that response parameter in here: https://tools.ietf.org/html/rfc6749

**Comment by mdissel** [comment]
Correct, but in keycloak it's implementated and here's another sample:
http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.7/Integration/Web_Services/v10/Endpoints/oauth2token_POST/

**Comment by leastprivilege** [comment]
sure - still it is not part of the spec.

You can read non-standard response elements though.

**Comment by mdissel** [comment]
Can you give a sample how we can read other elements?

**Comment by leastprivilege** [comment]
There is a Json property

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/TokenResponse.cs#L60 

and a couple of extensions methods on that.

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/JObjectExtensions.cs
