### ISSUE TITLE
DynamicClientRegistrationDocument and RegistrationRequest confuse

### ISSUE THREAD

**Issue by mpyclikcorp** [DuendeArchive/IdentityModel#234]
I'm quite confused...
You use DynamicClientRegistrationDocument at 3.9 version.
RegistrationRequest at 3.10 and now again back to DynamicClientRegistrationDocument...

Why resign with RegistrationRequest? I have using it... :-|

**Comment by mpyclikcorp** [comment]
What whorst, it's not compatible with IS4, couse thare we have Endpoints expect a form HTTP not json.
So I added another endpoint with dynamic client registration...

**Comment by leastprivilege** [comment]
IS4 does not have a client registration endpoint - so it can't be incompatible.

https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest

**Comment by mpyclikcorp** [comment]
Ok, you're right. My mistake.

But what with Request Object? With one is final? DynamicClientRegistrationDocument or RegistrationRequest?

**Comment by leastprivilege** [comment]
Depends on the version - I think I renamed it from v3 to v4 preview
