### ISSUE TITLE
Why there is no "scope" field in RegistrationResponse class?

### ISSUE THREAD

**Issue by mpyclikcorp** [DuendeArchive/IdentityModel#235]
https://tools.ietf.org/html/rfc7591#page-16

 scope
      String containing a space-separated list of scope values (as
      described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client
      can use when requesting access tokens.  The semantics of values in
      this list are service specific.

**Comment by leastprivilege** [comment]
I can't remember - but first of all I was using the OpenID dynamic client reg spec - not the OAuth one.

https://openid.net/specs/openid-connect-registration-1_0.html

I wouldn't be surprised if you find gaps - this protocol is not very often used. If you feel there is stuff missing - please send a PR.

**Comment by leastprivilege** [comment]
I will release v4 soon - if you think this is a bug, I need more details.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
