### ISSUE TITLE
Is their any plan to support "urn:ietf:params:oauth:grant-type:jwt-bearer" grant-type in IdentityModel libary ?

### ISSUE THREAD

**Issue by madhub** [DuendeArchive/IdentityModel#238]

**Comment by madhub** [comment]
Specifically to support JWT grant-type in HttpClient extension (HttpClientTokenRequestExtensions)

**Comment by leastprivilege** [comment]
you can use any grant type you want. There is no need for special support.

**Comment by madhub** [comment]
What I meant was , how do I use **IdentifyModel** library to talk to any Identity provider which require to use `urn:ietf:params:oauth:grant-type:jwt-bearer` grant. Existing `TokenRequest`  does not have a way to pass `key ` (symmetric or PKI )  which can be used for signing the JWT. Also I do not see any code to in library to generate & sign the  JWT .
Is **IdentityModel** Library expects that to user to `create & sign JWT` outside the library & pass type & value via `ClientAssertion` class ?

**Comment by leastprivilege** [comment]
Yes. That’s the intention.

**Comment by madhub** [comment]
Ok,Thanks
