### ISSUE TITLE
Invalid Client with TokenClient on Cunstructor without ClientId , ClientSecret

### ISSUE THREAD

**Issue by LukasTomalla** [DuendeArchive/IdentityModel#24]
Hey Guys,

The Tokenclient returns with the Constructor `TokenClient(string address)` and `TokenClient(string address, HttpMessageHandler innerHttpMessageHandler);`  "invalid_client" as response

invalid example
`            var invalid = new TokenClient(AppConstants.TokenEndpoint, new NativeMessageHandler())
            {
                ClientId = AppConstants.ClientId,
                ClientSecret = AppConstants.ClientSecret
            };`

using 
`var tokenClient = new TokenClient(AppConstants.TokenEndpoint, AppConstants.ClientId,AppConstants.ClientSecret);`

works fine 

My guess is that you use the private fields in the Class methods and not the the Properties.

hope I could help

**Comment by leastprivilege** [comment]
thanks for reporting - I will look into it.

**Comment by leastprivilege** [comment]
fixed. give it a try please.
