### ISSUE TITLE
Shouldn't HttpResponseMessage be disposed?

### ISSUE THREAD

**Issue by inbarbarkai** [DuendeArchive/IdentityModel#243]
Hello,
I looked over the implementation of the `HttpClientDiscoveryExtensions`.
I recently encountered an issue in a project I'm working on, where many client sockets were left at a CLOSE_WAIT state.
All of those sockets were the connections to my IdentityServer.
While searching for a solution I can accross this [.NET Core Issue](https://github.com/dotnet/corefx/issues/35698).

My question is shouldn't HttpResponseMessage be disposed?

Thanks

**Comment by leastprivilege** [comment]
Don't think so

https://github.com/dotnet/corefx/issues/35698#issuecomment-470161189
