### ISSUE TITLE
General architecture for using IdentityModel

### ISSUE THREAD

**Issue by nobba75** [DuendeArchive/IdentityModel#244]
We are looking at your libraries having had a quite difficult time trying to use the adal libraries. Our SP i currently ADFS (2016 and above) but might of course be Azure as well in the future.

We build products on several .net platforms, like standard .NET, aspnet core and dotnet core. The applications are both older WinForms client/server and web clients as SPA apps. The final goal is to provide a user friendly SSO-implementation for our users that might use any combination of above products on their pc. Note that we also have scheduled services that need to login using username/pwd.

By looking at the different parts of IdentityModel it seems like you have most parts covered, although we are quite unfamiliar with using oidc, oauth and ADFS-based security. So although this is really a question for advice and not an issue with the libraries, I hope that you can give me a short answer.

My understanding of IdentityModel given our needs are that we should:
- Use oidc-client-js for the SPA apps. I have implemented this and it seems to work well.
- Use the .net standard helper library to manage silent logins using user/pwd for our scheduled services that run without user interaction.

My main concern is what to use for the WinForms-clients. From what I can see, the helper library (IdentityModel package) doesn't support UI-interaction with the login page? So for these clients I guess that Oidc-Client2-package is the way to go with the implementation resembling that in the WinForms example?

Finally, what is the best way to support SSO using the IdentityModel packages? How to share the tokens between the different types of applications?

Hope that you can give med some advice and perhaps there are other users that can share their thoughts of how they have solved similar architectural challenges.

**Comment by leastprivilege** [comment]
IdentityModel is the base library for .NET - OidcClient adds the UI interaction parts.

**Comment by nobba75** [comment]
Yes, I know that, I just wanted to describe our situation. So I´ll try to be more precise. 

We can leave the services that use the user/password out of the discussion since they won´t be included in SSO. That was just part of my description of how we are trying to fit your libraries into our architecture.

I guess it all boils down to how SSO will work between the SPA and the native clients. Will this work if using the system browser and the browser cache or do your libraries have some other recommended way of solving this (implementation of distributed cache)?

Thank you for your time and response!

**Comment by leastprivilege** [comment]
Yes - you need to share browsers - IOW use the system browser for both client types.

**Comment by nobba75** [comment]
Ok, thanks!

**Comment by nobba75** [comment]
Does oidc-client have an implementation similar to the Token Cache of adal.net? For some of our deployment scenarios it might be easier to use an encrypted file for storing tokens.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.tokencache?view=azure-dotnet

**Comment by leastprivilege** [comment]
No - token storage is up to you. That's pretty platform specific, and I didn't feel abstracting that.

**Comment by nobba75** [comment]
Yes I can understand that, thank you for answering.
