### ISSUE TITLE
Add support for non-JSON responses from UserInfo endpoints

### ISSUE THREAD

**Issue by sliekens** [DuendeArchive/IdentityModel#247]
Currently there is a hard-coded assumption that UserInfo responses will always contain JSON. That's okay most of the time, but it's incompatible with some providers.

From OpenID Connect Core:
https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse
 - the UserInfo Endpoint MUST return the JSON Serialization of the UserInfo [...] **unless a different format was specified during Registration.** The UserInfo Endpoint MUST return a content-type header to indicate which format is being returned.
- If the UserInfo Response is signed and/or encrypted, **then the Claims are returned in a JWT** and the content-type MUST be application/jwt.

Is it feasible to modify _ProtocolResponse.FromHttpResponseAsync_ in a way that takes the Content-Type response header into consideration?

**Comment by leastprivilege** [comment]
So - IOW - if the response type is not JSON - then only set the Raw?

**Comment by sliekens** [comment]
Ideally the Claims collection would also be initialized. I imagine a system where I can provide a callback function.

```csharp
// signature
(string contentType, string raw) => ICollection<Claim>
```

**Comment by leastprivilege** [comment]
OK - I will think about it..

**Comment by jkerrwilson** [comment]
Any update on this? Returning JWT user info seems to be fairly common in high security environments. The change shouldn't be super difficult to implement, it should be straight forward to toggle JSON response parsing vs JWT claims parsing based on response content type.

**Comment by leastprivilege** [comment]
I do not have time for that right now. Feel free to propose a PR.

**Comment by leastprivilege** [comment]
@josephdecock maybe only set Raw in this case and let the consumer materialize the real data?

**Comment by josephdecock** [comment]
Note that we will only set the Raw and not validate and parse the jwt for simplicity and to avoid a dependency on the JWT library.
