### ISSUE TITLE
ConfigureAwait(false) missing from TokenClient.RequestAsync()

### ISSUE THREAD

**Issue by SteveGuidi** [DuendeArchive/IdentityModel#25]
Hi there!

It looks like a `ConfigureAwait(false)` directive was erroneously removed when the TokenClient code was recently refactored for release 2.1.0 of IdentityModel.  The following statement creates a deadlock when I call `RequestAsync()` (indirectly from `RequestClientCredentialsAsync()`) from a non-async ASP.NET method, using `.Result` or `.Wait()` to block on the resulting task.

`response = await _client.SendAsync(request, cancellationToken);`

(line 88 from TokenClient.cs, from [this commit](https://github.com/IdentityModel/IdentityModel2/commit/5bb95fbe820dbb9657a5efdd4101b52b96e9c9af))

**Comment by brockallen** [comment]
PR?

**Comment by SteveGuidi** [comment]
Pull request created and has been merged.  Closing issue.
