### ISSUE TITLE
RequestCustomGrant Extension

### ISSUE THREAD

**Issue by ddrdoubled** [DuendeArchive/IdentityModel#251]
Hi,

i am trying to migrate to the new extension methods of HttpClient and remove the old TokenClient class. I am trying to construct a "RequestCustomGrantType" Extension like for the old TokenClient class:
`var tokenResponse = tokenClient.RequestCustomGrantAsync("custom_grantType")`
because there is nothing like that in the new extension methods. But i tried a couple of like:
`var tokenRequest = new TokenRequest {
                                        GrantType = "custom_granType"
                                        }`

or like:
`var tokenRequest = new TokenRequest {
                                       Parameters = { 
                                           { OidcConstants.TokenRequest.GrantType, "custom_grantType" }
                                         }
                                        }`

but always getting the same invalid grant type result. Is there a special reason why there has not been an RequestCustomGrantType extension in the new version?

Thx a lot. If i should move this to stackoverflow instead please give me a short notice.

**Comment by leastprivilege** [comment]
Not sure what your specific problem is - but this works for me:

https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Clients/src/ConsoleCustomGrant/Program.cs#L42-L55

**Comment by ddrdoubled** [comment]
Yes sorry, problem was in the IExtensionGrantValidator implementation. Thx a lot anyway
