### ISSUE TITLE
Some parameters generate invalid HTTP request for UserInfo

### ISSUE THREAD

**Issue by fogzot** [DuendeArchive/IdentityModel#255]
Specifing some parameters like `ClientId` or `ClientSecret` in `UserInfoRequest` result in a `GET` HTTP request with a body. This is wrong and is a problem, especially for applications hosted on services like Google Cloud that refuse to route GET/DELETE HTTP requests with a body.

Calling `GetUserInfoAsync()` with extra parameters should probably ingore them or throw an exception.

**Comment by leastprivilege** [comment]
Will look into it for v5. Why are you setting those parameters?

**Comment by fogzot** [comment]
Sorry for the late response. It was an error in my code and I lost a lot of time before discovering that the generated request was "invalid". There is no real reason for calling `GetUserInfoAsync()` with extra parameters, that's why I suggested to ignore them or return an error.

**Comment by leastprivilege** [comment]
feel free to PR

**Comment by brockallen** [comment]
What's our status on this request?

**Comment by josephdecock** [comment]
I had some feedback on the linked PR, and then it was closed by the submitter.

**Comment by josephdecock** [comment]
As to what we do with this now, I'm not sure, but I don't think this is a high priority. Maybe keep the issue around in case someone wants to take another crack at it?

**Comment by josephdecock** [comment]
Closing, as this issue has been migrated to the new repo: https://github.com/DuendeSoftware/foss/issues/42.
