### ISSUE TITLE
netcoreapp3.0 upgrade error

### ISSUE THREAD

**Issue by devna13** [DuendeArchive/IdentityModel#258]
I have a web application that is referencing a nuget package from another project that is a class library in netstandard2.0.
after upgrading the asp .net web app from 2.2 to netcoreapp3.0 I'm getting this exception
`System.AggregateException HResult=0x80131500 Message=One or more errors occurred. (Could not load type 'System.Net.Http.HttpRequestMessageExtensions' from assembly 'IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'.) Source=System.Private.CoreLib`

![66681609-e61c3a00-ec27-11e9-852a-9893a3e62be4](https://user-images.githubusercontent.com/4080343/66687143-95600d80-ec36-11e9-8484-94ced0868833.png)

**Comment by leastprivilege** [comment]
I guess the "other" package is referencing a 3.x version of identitymodel?

**Comment by devna13** [comment]
Correct

**Comment by devna13** [comment]
yes 
I've upgraded to     `<PackageReference Include="IdentityModel" Version="4.0.0" />` . it's working now
