### ISSUE TITLE
BadRequest no longer considered an error in TokenResponse.

### ISSUE THREAD

**Issue by schummbo** [DuendeArchive/IdentityModel#265]
I don't know if this was intentional or not, but I wanted to point it out just in case.

Back in this commit: https://github.com/IdentityModel/IdentityModel/commit/d95fd0713b4d2d93ee3a81c78ac970a76421294b

The way TokenResponse.IsError gets decided changed slightly when the class began to inherit from ProtocolResponse instead of Response.  It looks like a BadRequest used to cause IsError to be true and now that it inherits from ProtocolResponse, BadRequest is explicitly excluded and IsError will be false for a bad request.

Perhaps this was intentional, but it caused issues for our application so I thought I'd mention it!

**Comment by leastprivilege** [comment]
hm - I have a test that says otherwise

https://github.com/IdentityModel/IdentityModel/blob/master/test/UnitTests/HttpClientExtensions/HttpClientTokenRequestExtensionsResponseTests.cs#L44

Can you please run that and tell me what's different to your scenario?

**Comment by schummbo** [comment]
I think figured it out.  In ProtocolResponse.FromHttpResponseAsync, if the StatusCode is BadRequest and there is no response content, Error ends up null because ErrorMessage is not present, the ErrorType is Protocol, there's no exception, and the fallback of getting the error from the the response content doesn't work.

Probably an unrealistic scenario and we're doing something wacky.  You can most likely ignore.
