### ISSUE TITLE
Bug with typed TokenClient when using custom parameters

### ISSUE THREAD

**Issue by gorgi** [DuendeArchive/IdentityModel#268]
We have updated IdentityServer4.AccessTokenValidation to 3.0.1, which depends on IdentityModel 4.0.0.

In this version, the TokenClient was changed and no longer provides RequestCustomGrantAsync (thanks for that :] ), so now we are trying to use RequestTokenAsync in the following way:

```

var parameters = new Dictionary<string, string>
{
    {"scope", "new_scope" },
    { "token", userToken }
};
var response = await tokenClient.RequestTokenAsync("delegation", parameters);

```
in order to implement extensions grants (last section from here: http://docs.identityserver.io/en/latest/topics/extension_grants.html).

The very first time when this is called, it works as expected. However, the second and the rest of the times, we get the following exception: **An item with the same key has already been added. Key: scope.**

Digging in the code, I found that this line is the cause of the bug: https://github.com/IdentityModel/IdentityModel/blob/master/src/Client/TokenClient.cs#L55
The request object is getting direct reference of the _options.Parameters, so the parameters for the current request are _saved_ in the _options object as well. 

We have been following this example to setup the typed client: https://github.com/IdentityModel/IdentityModel/blob/master/samples/HttpClientFactorySample/WebApplication1/Startup.cs#L38

As you can see here, the TokenClientOptions object is reused for all instances of TokenClient. 

A workaround that we use is to create new TokenClientOptions in that line, instead getting the singleton value from IOptions.

**Comment by leastprivilege** [comment]
So in essence - the options.Parameters needs a clone, right?

**Comment by gorgi** [comment]
I would say that **request.Parameters** needs a clone of **_options.Parameters**.

**Comment by leastprivilege** [comment]
Exactly - want to send a PR?
