### ISSUE TITLE
Check issuer against base address in DiscoveryClient

### ISSUE THREAD

**Issue by leastprivilege** [DuendeArchive/IdentityModel#27]
Issuer name should (per spec) be equal to the base addresss.

Optional - but on by default

**Comment by leastprivilege** [comment]
done

**Comment by Dissimilis** [comment]
http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation

Just adding a reference to the documentation, because this issue was somehow easier to find :)
