### ISSUE TITLE
Where is UserInfoClient?

### ISSUE THREAD

**Issue by EdLichtman** [DuendeArchive/IdentityModel#270]
I'm trying to implement IdentityServer4 with Webforms and everywhere I look all the examples use "UserInfoClient" I can't seem to find any documentation of when it was deprecated, or how to replace it. Could you please direct me towards it?

It looks like perhaps it was removed from being it's own class and is instead an extension of HttpClient, but I would like confirmation, and to make sure to open this question for future viewing in case anyone else is having just as much trouble finding it.

Thanks,
Eddie

**Comment by leastprivilege** [comment]
yes - please use the extension methods instead.

**Comment by slaneyrw** [comment]
Please generate a sample using NET 4.x.   IHttpClientFactory is not available in full framework

**Comment by leastprivilege** [comment]
https://identitymodel.readthedocs.io/en/latest/client/userinfo.html
