### ISSUE TITLE
Missing methods vs IdentityModel

### ISSUE THREAD

**Issue by olonga** [DuendeArchive/IdentityModel#28]
IdentityModel 1.9.2 had ProtocolHelperExtensions & HashStringExtensions methods.  Now IdentityModel2 does not seem to have those?  Have these methods been moved to another project?

**Comment by leastprivilege** [comment]
I just didn't port them over because they did not seem to be used very often.

What exactly are you doing with these?

**Comment by olonga** [comment]
I am using these to generate verifer challenge for native app security with Pkce. Thanks. For now, i reverted back to 1.x.x version.
