### ISSUE TITLE
ProtocolResponse doesn't implement IDisposable

### ISSUE THREAD

**Issue by leealexander** [DuendeArchive/IdentityModel#283]
Whilst having a look around the code I noticed that ProtocalResponse.FromHttpResponseAsync stores the HttpResponseMessage in a HttpResponse property and HttpResponseMessage implements IDisposable..

Since ProtocalResponse stores the HttpResponseMessage shouldn't it implement IDisposable?

Regards
Lee

**Comment by leastprivilege** [comment]
We discussed this in an older issue already. No . this is not necessary.

**Comment by leealexander** [comment]
OK could you give me a link to this older issue so i can understand why it isn't necessary?

**Comment by leastprivilege** [comment]
Short version is that HttpResponseMessage IDisposable really only triggers the Dispose of the HttpContent it wraps - which really only does something if it is a stream, which does not appply to us.
