### ISSUE TITLE
Feature request: ditch Newtonsoft.Json in favor of System.Text.Json

### ISSUE THREAD

**Issue by AroglDarthu** [DuendeArchive/IdentityModel#286]
Do you foresee any major compatibility issues or would it be totally feasible to switch to System.Text.Json?

NewtonSoft.Json has a nasty [bug](https://github.com/JamesNK/Newtonsoft.Json/issues/862) that, according to the author, is `by design` . This bug ripples through to each and every package that uses it.

**Comment by leastprivilege** [comment]
Well - you could give it a try and PR

**Comment by leastprivilege** [comment]
oh well - System.Text.Json in netcore only - right?

**Comment by AroglDarthu** [comment]
![Screenshot_20200124-130726_Chrome](https://user-images.githubusercontent.com/5527014/73068072-97c73a00-3eaa-11ea-98ab-45df230063c9.jpg)

**Comment by AroglDarthu** [comment]
> Well - you could give it a try and PR

I would be happy to, but I guess it will be a breaking change. Would be pointless to start if you're not open to the idea ;-)

**Comment by leastprivilege** [comment]
Well - you are right. It would be a breaking change. I still think it would be a worthwhile exercise to find out if the new JSON APIs are feature complete for what IdentityModel uses them for...

**Comment by leastprivilege** [comment]
will happen in v5

**Comment by codermrrob** [comment]
it doesn't do half of what Json.Net is capable of, its way beyond serialization/deserialization - the date issue is real but not significant, once you understand it.
