### ISSUE TITLE
Does it support implicit flow

### ISSUE THREAD

**Issue by p-ideal** [DuendeArchive/IdentityModel#287]
Not an issue: Need information

I have already web application which is authenticating and authorizing using organisation oauth provide using implcit flow. As setting below for oidc-oauth:
oauth: {
    issuer: 'xyz',
    loginUrl: 'xyz',
    logoutUrl: 'xyz',
    redirectUri: 'xyz',
    silentRefreshUri: 'xyz',
    clientId: 'CM_DEV',
    responseType: 'id_token token',
    scope: 'openid profile address email phone',
    acr_values: 'AAL1_MS-AD-Kerberos',
    autoRefresh: true
  }, 

I want to implement console application using implicit flow. Could I implement using same using Identity Model without opening any browser window inside application. Please let me know.
Thank you in advance.

**Comment by leastprivilege** [comment]
no.
