### ISSUE TITLE
AuthoriseResponse constructor throws InvalidOperationException on a query string with a trailing ampersand (&)

### ISSUE THREAD

**Issue by blushingpenguin** [DuendeArchive/IdentityModel#288]
e.g. https://localhost/callback?a=b&

due to:

```csharp
 var parts = param.Split('=');

if (parts.Length == 2)
{
    Values.Add(parts[0], parts[1]);
}
else
{
    throw new InvalidOperationException("Malformed callback URL.");
}
```
in
https://github.com/IdentityModel/IdentityModel/blob/master/src/Client/Messages/AuthorizeResponse.cs

I can see that this might be deliberate (and I can sanitise the input before passing it on to avoid this), but would ignoring empty key/value pair entries, e.g. with

```csharp
var qparams = fragments[1].Split('&', StringSplitOptions.IgnoreEmptyEntries);
```

be a reasonable change here?

(I have seen the trailing "&" from one actual OIDC implementation).

**Comment by leastprivilege** [comment]
thanks! Could you send a PR including tests?

**Comment by leastprivilege** [comment]
?

**Comment by blushingpenguin** [comment]
yep sure, i'll send a PR on

**Comment by leastprivilege** [comment]
?

**Comment by blushingpenguin** [comment]
Done, eventually:

https://github.com/IdentityModel/IdentityModel/pull/306

Thanks!
