### ISSUE TITLE
Provide Strongname for IdentityModel2 for net45

### ISSUE THREAD

**Issue by CoRlfKrl** [DuendeArchive/IdentityModel#29]
If you use IdentityModel2 from an assembly which is signed with a strong name all referenced assemblies have to have a strong name.
Please "give" the net45 assembly with a strong name.

**Comment by leastprivilege** [comment]
We don't provide strong named versions of our assemblies.

Maybe this will help you:
https://github.com/dsplaisted/strongnamer
