### ISSUE TITLE
No MtlsEndpointAliases on Discovery response model

### ISSUE THREAD

**Issue by snothub** [DuendeArchive/IdentityModel#295]
To facilitate for [mTLS documentation](https://identityserver4.readthedocs.io/en/latest/topics/mtls.html#using-a-client-certificate-to-authenticate-to-identityserver), mTLS endpoint aliases should be added to the discovery response.

Currently, `.TryGetValue(OidcConstants.Discovery.MtlsEndpointAliases)` gets no content.

https://github.com/IdentityModel/IdentityModel/blob/master/src/Client/Messages/DiscoveryDocumentResponse.cs

**Comment by leastprivilege** [comment]
Are you talking about a "strongly typed" accessor?

what do mean with

> Currently, .TryGetValue(OidcConstants.Discovery.MtlsEndpointAliases) gets no content.

```
Address = disco
                        .TryGetValue(OidcConstants.Discovery.MtlsEndpointAliases)
                        .Value<string>(OidcConstants.Discovery.TokenEndpoint)
                        .ToString(),
```

works fine for me...

**Comment by snothub** [comment]
Never mind, it's working after all. Sorry for the fake alarm.
