### ISSUE TITLE
Proper refresh token approach

### ISSUE THREAD

**Issue by dominikjeske** [DuendeArchive/IdentityModel#298]
In version 4.0 RefreshTokenDelegatingHandler and AccessTokenDelegatingHandler was removed with comment in release notes “I never was happy with their design, and they also did not work for some common scenarios”. I have a question what is the problem with that implementation and what is suggested approach to do that in ASP.NET Core with IdentityModel?

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/IdentityModel.AspNetCore

**Comment by leastprivilege** [comment]
cu there ;)

**Comment by bugproof** [comment]
@leastprivilege what about console apps? should we make our own refresh token handler ? I see there's a handler in https://github.com/IdentityModel/IdentityModel.OidcClient but it's only for OIDC and not for OAuth 2.0
