### ISSUE TITLE
Question: can i provide also the KeyId ?

### ISSUE THREAD

**Issue by TrabacchinLuigi** [DuendeArchive/IdentityModel#303]
is there a simple way to provide to ids4 also the key id instead of just the RsaKey ? 
I'd like to use the same certificate and mechanism (include the key id in the signed data) to sign some other stuff, so i won't need to generate two keys, and store them in the clients...

Or

Is there a way to generate the same key starting from the certificate ?

**Comment by leastprivilege** [comment]
Hi, 

this sounds like an IdentityServer question?

**Comment by TrabacchinLuigi** [comment]
Wopz, It is.
