### ISSUE TITLE
Remove frameworkAssembly reference to System.Net.Http

### ISSUE THREAD

**Issue by aggieben** [DuendeArchive/IdentityModel#31]
It should be sufficient to have a dependency on the `System.Net.Http` nupkg.

The `frameworkAssembly` reference breaks downstream packages that target `net461` but have other dependencies that target `netstandardx.x` and depend on `System.Net.Http` via NuGet because the assembly versions in the GAC (for both 4.5.x and 4.6.x) differ from the latest published via NuGet.

**Comment by leastprivilege** [comment]
PR?

**Comment by aggieben** [comment]
I will try to submit one before the weekend.

**Comment by suddenelfilio** [comment]
My first PR on github, hope I did it right :-)

**Comment by leastprivilege** [comment]
thanks - done!

**Comment by aggieben** [comment]
Thanks, @suddenelfilio.  Life intervened for me, unfortunately, so I'm grateful that you picked up the slack.

**Comment by leastprivilege** [comment]
I moved to the new csproj

Could you try the dev branch - and if this fixes your scenarios?

Just call the build.ps1 in the root - it will produce a nuget

**Comment by MikaelGRA** [comment]
I think this 'fix' is causing problems when using it in the full .NET Framework since "System.Net.Http" is a part of the .NET Framework already.

When I install IdentityModel2 in my full .NET framework (net461) project and target this package in 2.5.0 or above (the version from which this dependency was introduced), I am getting a lot of errors regarding missing references if I try to use the the classes defined in System.Net.Http.

Aren't you supposed to ONLY put the dependency on System.Net.Http for the netstandard version and keep it as a framework reference for .NET framework?

**Comment by leastprivilege** [comment]
I don't know - open a new issue please.

**Comment by MikaelGRA** [comment]
Been investigating this a bit more by trying to: 

1. Create new project. 
2. Ensure the project targets net461.
3. Add nuget dependency to System.Net.Http.
4. Create class that inherits from HttpClientHandler.
5. Build and watch it fail or succeed.

I tried this for project types: [project.json/xproj], [new csproj], [old csproj]. It was ONLY a problem for the [project.json/xproj] build system. All other attempts succeeded just fine.

Basically, when targeting the OOB nuget packages (System.Net.Http) that are also a part of the .NET framework in a project which targets net46 or greater while using project.json the problem may occur. If you target net45 it also works, even for [project.json/xproj].

I think the same issue is described here https://github.com/dotnet/corefx/issues/14445

I'm not going to open a new issue, unless you feel it is important. But not having a dependency on OOB nuget packages for the net46+ version of this library would fix the problem.

**Comment by leastprivilege** [comment]
> It was ONLY a problem for the [project.json/xproj] build system.

IOW - this is not an issue anymore since project.json is deprecated. right?

**Comment by MikaelGRA** [comment]
That would be correct.

**Comment by leastprivilege** [comment]
OK - thanks for researching that. Since project.json and the other combinations seem to work - we can leave it as it is.
