### ISSUE TITLE
ASP.NET Core 3.1 : Alternate to DiscoveryResponse

### ISSUE THREAD

**Issue by TechAspirant** [DuendeArchive/IdentityModel#310]
What will be the Alternate to below code in Asp.Net core 3.1
Code in .Net Core 2.1
`var discResponse = new DiscoveryResponse(HttpStatusCode.OK, "", discoveryDocument);`
Code I am trying to use is
```
var discResponse = new DiscoveryDocumentResponse();
discResponse.HttpResponse.StatusCode = HttpStatusCode.OK;
discResponse.HttpResponse.ReasonPhrase = discoveryDocument;
```
But is is resulting into error as Object reference not set to an instance of an object

**Comment by leastprivilege** [comment]
Don't know - I never used it that way.
