### ISSUE TITLE
Api SecurityTokenExpiredExceptions in App Insights logs

### ISSUE THREAD

**Issue by waynethompson** [DuendeArchive/IdentityModel#311]
We have an angular application that gets an access token from identity server and uses it to connect to an aspnetcore api application.

I have added the authentication to the API application with
`authenticationBuilder.AddJwtBearer()`

In Azure Application Insights logs for the Api i get a lot of Microsoft.IdentityModel.Tokens.SecurityTokenExpiredExceptions but they don't affect the functionality.
IDX10223: Lifetime validation failed. The token is expired. ValidTo: '03/30/2020 02:28:05', Current time: '04/01/2020 22:26:59'.
Does anyone know why this happens or how to remove the chatter from the logs?

Is it possibly because someone has left the browser open for a day and it still has the old access token? Should I poll the Api after a period of time and then make it get a new access token?

**Comment by leastprivilege** [comment]
Sorry - wrong repo.

**Comment by waynethompson** [comment]
sorry
