### ISSUE TITLE
RequestResourceOwnerPasswordAsync: When IdentityServer throws exception, it is not in TokenResponse

### ISSUE THREAD

**Issue by MattyBoy4444** [DuendeArchive/IdentityModel#32]
If an exception is thrown in my class which implements IResourceOwnerPasswordValidator, the TokenResponse exception field is NULL.  All I get is an "Internal Server Error".  I am using IdentityServer4, FYI.

**Comment by leastprivilege** [comment]
Please open an issue in IS4. thanks!

**Comment by leastprivilege** [comment]
Well - thinking about it, this is the expected behavior. The exception cannot occur on the client - all the client sees is an internal server error.

**Comment by MattyBoy4444** [comment]
My uses for throwing exceptions would be.
1.) Invalid username/pw
2.) Invalid secondary parameter
3.) Could not connect to backend server
etc....

**Comment by leastprivilege** [comment]
Well - that's up to you. Exceptions translate to internal server errors.

You can set an error code on the response if you want to give the client more info.

**Comment by MattyBoy4444** [comment]
K.
