### ISSUE TITLE
RequestTokenAsync don't care about expiration time of JWT Token

### ISSUE THREAD

**Issue by rlanhellas** [DuendeArchive/IdentityModel#325]
Hello Guys, I noted that every time I call the RequestTokenAsync() method, always a new token is generated. My token is valid for 24 hours, but this is ignored by IdentityModel library. 

Reading this method: 

```
 internal static async Task<TokenResponse> RequestTokenAsync(this HttpMessageInvoker client, ProtocolRequest request, CancellationToken cancellationToken = default)
        {
            request.Prepare();
            request.Method = HttpMethod.Post;
            
            HttpResponseMessage response;
            try
            {
                response = await client.SendAsync(request, cancellationToken).ConfigureAwait();
            }
            catch (Exception ex)
            {
                return ProtocolResponse.FromException<TokenResponse>(ex);
            }

            return await ProtocolResponse.FromHttpResponseAsync<TokenResponse>(response).ConfigureAwait();
        }
```

It is easy to see that exists no treatment about the expiration time of tokens. Is there any roadmap to add this feature in the library ?

To solve this I'm using IMemoryCache, in this way:

```
if (!_memoryCache.TryGetValue(KEY_JWT_TOKEN, out token))
      {
        var clientCredentialsRequest = new ClientCredentialsTokenRequest
        {
          Address = (await _discoveryCache.GetAsync()).TokenEndpoint,
          ClientId = _configuration["Authorization:ClientId"],
          ClientSecret = _configuration["Authorization:ClientSecret"],
          Parameters = new Dictionary<string, string>() { { OidcConstants.TokenRequest.Audience, _configuration["Api:Auth0ApiManager"] } }
        };
        var httpClient = _httpClientFactory.CreateClient();
        var response = await httpClient.RequestClientCredentialsTokenAsync(clientCredentialsRequest);
        token = response.AccessToken;
        _memoryCache.Set(KEY_JWT_TOKEN, token, DateTimeOffset.Now.AddSeconds(response.ExpiresIn).AddMinutes(-10));
      }
```

But I really think that this code should be inside the library.

**Comment by leastprivilege** [comment]
This library is a protocol wrapper only. Adding caching semantics specific to your environment is out of scope.

**Comment by rlanhellas** [comment]
I understand your point but look for frameworks like Spring Security 5, it controls all OAuth2 flows, including Caching mechanisms, you just say what API call should have Bearer token and the magic is done. 

I think we can start at least with a caching mechanism. It is not possible in this library today I can see two options:

1. Request a pull request to add this feature, if you agree (@leastprivilege).
2. Create a fork from this project and add these features.

What do you think @leastprivilege  ?

**Comment by leastprivilege** [comment]
You cannot compare this to Spring - this is a protocol library. That's it.

The right thing to do would be to create your own higher level library that uses this one for the protocol work - like e.g. 

https://github.com/IdentityModel/IdentityModel.AspNetCore

**Comment by rlanhellas** [comment]
Good to know that exists it: https://github.com/IdentityModel/IdentityModel.AspNetCore. I will try to contribute.

Thanks.
