### ISSUE TITLE
Support for resource indicators

### ISSUE THREAD

**Issue by poke** [DuendeArchive/IdentityModel#326]
Back in 2017, issue #74 was closed because it was asking for adding support for parameters that were non-standard at the time. Fast forward to today, [RFC 8707: Resource Indicators for OAuth 2.0](https://tools.ietf.org/html/rfc8707) is a _Proposed Standard_, making the `resource` parameter somewhat safe thing to support.

Right now, one can work around it by passing a resource as an additional parameter to the token requests, e.g.:

```c#
var response = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
{
    Address = "https://fs.contoso.com/adfs/oauth2/token",
    ClientId = "client",
    ClientSecret = "secret",
    Scope = "scope1",
    Parameters =
    {
        ["resource"] = "https://api.contoso.com",
    },
});
```

The [spec explicitly allows](https://tools.ietf.org/html/rfc8707#section-2) multiple resource values, something that isn’t possible with the custom dictionary right now: _“Multiple ‘resource’ parameters MAY be used to indicate that the requested token is intended to be used at multiple resources.”_ By making the resource an explicit property of the token request, this could be supported as well.

Prominent servers that support, and somewhat even require, this `resource` parameter are AAD and AD FS, but I hear that other auth servers do have support for this as well. And since this is being standardized, it would make sense to adopt this functionality. I would offer my help in that case too.

**Comment by leastprivilege** [comment]
Good idea. Will look into it.

**Comment by leastprivilege** [comment]
Oh snap - now I realize that everything internally is based on a dictionary ... ;)

Why would you need to pass in 2 resource parameters? The spec advises against it...

**Comment by leastprivilege** [comment]
> Although multiple occurrences of the "resource" parameter may be
   included in a token request, using only a single "resource" parameter
   is encouraged.

https://tools.ietf.org/html/rfc8707#section-3

**Comment by poke** [comment]
Well… it’s not that I actually need to do that. I was just looking for another argument why adding “full support” (by a separate property) would be a good idea :joy:

I am personally totally fine with just having a single-value `resource` parameter and would just like to see that being added to the request objects 😊 

So yeah, if this is a dictionary internally anyway, then the theoretical requirement to specify multiple resources is probably not enough reason to change the implementation there.

**Comment by leastprivilege** [comment]
I added this for v5. For now there is a workaround.

thanks for reporting.
