### ISSUE TITLE
Question about Signing of  Thinktecture.IdentityModel.45 

### ISSUE THREAD

**Issue by suhasiniravi** [DuendeArchive/IdentityModel#330]
Hi,

My organization is using one of your older libraries Thinktecture.IdentityModel.45 and I had some questions about signing of the dll but not sure what is a good place to post it because its been archived in github and I am not sure how to reach out to you directly. Here are some questions I have. It would be great if you can help me out with this.

1. I read in a different github post that you don't provide signed versions of the dll but suggested using strongnamer for signing the library. https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/119. I want to confirm if this is ok to do for the Thinktecture.IdentityModel.45 using my organization's key.
2. Another option we were considering is to use ildasm to decompile and then use ilasm to recompile with my organizations key This is only to be able to sign it with our key because our organization requires all our dlls to be signed. Is this permissible?

This is a commercial product so the signed dll will be redistributed with out product. Any advice on this is appreciated.

Thanks,
Suhasini Ravi

**Comment by leastprivilege** [comment]
Have you considered just copying the source code of the library, and then do whatever you want? - I mean it is like 10 years old?

**Comment by suhasiniravi** [comment]
We could do that as long as you are ok with us signing it with our key.

Are you opposed to us using ildasm?

Just making sure we are incompliance with the license is all.

**Comment by suhasiniravi** [comment]
We have a legal requirement in our organization that we obtain written
permission from the author in this case where we are changing a third party
library.

**Comment by leastprivilege** [comment]
I am fine with that.
