### ISSUE TITLE
Support claims of type DateTime

### ISSUE THREAD

**Issue by botondbotos** [DuendeArchive/IdentityModel#336]
## Problem
A claim with a value containing `DateTime` information (e.g. `2020-07-12T23:53:03.0000000Z`) will be deserialized as `"2020-07-12T23:53:03.0000000Z"`, with extra quotation marks.

The issue seems to be caused by `JObjectExtensions.ToClaims` method, which is **stringifying** DateTime values as well.

**Comment by leastprivilege** [comment]
Hi, 

OK - please send a PR with tests

thanks!

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
