### ISSUE TITLE
After upgrading identity model to 4.3, I am facing this issue.

### ISSUE THREAD

**Issue by skmrinal** [DuendeArchive/IdentityModel#337]
{"Could not load type 'IdentityModel.Client.DiscoveryClient' from assembly 'IdentityModel, Version=4.3.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'.":"IdentityModel.Client.DiscoveryClient"} while running the API. I am using .net core 2.1 version and IdentityServer4.AccessTokenValidation is 2.7.

**Comment by leastprivilege** [comment]
I guess you had to apply force to upgrade your dependencies

<img width="446" alt="Screenshot 2020-06-29 08 56 21" src="https://user-images.githubusercontent.com/1454075/85982655-813b8680-b9e6-11ea-8874-3001d924b74d.png">

As you can see - they are not compatible.

**Comment by saluton-mundo** [comment]
Hi there,

Sorry to resurrect this one but slightly concerned with the usage of this lib within netcoreapp2.1/netstandard2.0. 

Looking at the nuget feed it seems that the _only_ viable release is **3.10.10**, however, other well known libraries have dependencies on 4.0.0. Thus, you end up in DLL hell v2. 

Is there a workaround in the event porting the host application to 3.1 is not viable?
