### ISSUE TITLE
Re-visit JSON stringification with System.Text JSON support / .NET 5

### ISSUE THREAD

**Issue by leastprivilege** [DuendeArchive/IdentityModel#338]

**Comment by erikmf12** [comment]
Do you accept PRs? This should be fairly easy, unless there are some advanced features being used in Newtonsoft.

**Comment by leastprivilege** [comment]
IIRC the v5 branch already has that work. But it is a breaking change, so I was holding back...

**Comment by leastprivilege** [comment]
Maybe when .NET 5 is released is a good time to re-visit.

**Comment by leastprivilege** [comment]
done on v5 branch
