### ISSUE TITLE
DiscoveryClient should be disposable through the HttpClient

### ISSUE THREAD

**Issue by rmja** [DuendeArchive/IdentityModel#34]
Just like TokenClient.

**Comment by leastprivilege** [comment]
why exactly do you think this is necessary?

**Comment by leastprivilege** [comment]
I just want to understand your motivation (because there are several opinions about it out there).

**Comment by rmja** [comment]
Hiding the ability to dispose the client just seems odd. I guess the same question could be asked to the implementers of HttpClient. If one needs a long lived instant, they should register it as Singleton in their DI system, and, I know that it is often recommended for HttpClient.

**Comment by leastprivilege** [comment]
Well PR then.

**Comment by leastprivilege** [comment]
no PR I guess. But complaining is always good ;)

**Comment by rmja** [comment]
Was I complaining? No. I just came with a suggestion to improve an excellent piece of OSS, as I stumpled upon a minor thing that in my opinion should be fixed. A PR was on my backlog, but the troll reference on Twitter made me lose the motivation. Sorry for reporting.

**Comment by leastprivilege** [comment]
Which troll reference?


-------
Dominick Baier

**Comment by rmja** [comment]
https://twitter.com/BrockLAllen/status/838088536033275905

**Comment by leastprivilege** [comment]
I don't think this was related to this issue.


-------
Dominick Baier

**Comment by brockallen** [comment]
@rmja I can assure that was not directed at you. IIRC my reason was because we we getting lots of questions on the IS issue tracker asking questions about how ASP.NET Core and other fundamentals work (unrelated to IdentityServer).

**Comment by rmja** [comment]
@brockallen Thank you so much for taking the time to clear things up. I clearly misinterpreted the whole thing. You and @leastprivilege do an amazing job on IS, and it is a joy to work with. Keep up the good work!

**Comment by leastprivilege** [comment]
happier now? ;) 

https://github.com/IdentityModel/IdentityModel2/commit/0ceda59c0688d79571a1c055744808f238af0849
