### ISSUE TITLE
OAuth2 via oidc protocol for Asp.net Web App 

### ISSUE THREAD

**Issue by srinivasboddu** [DuendeArchive/IdentityModel#344]
I've been trying to modify the login process of my asp.net (.net framework 4.6.1) from its classic approach by delegating the identity check to one of our identityServer (IdentityAccessManager) with OAuth2  open Id connect.

Couldnot find any sample for that is suitable for asp.net web application.
Lots of confusion oidcClient libraary

To craft my login request - am i supposed to use IdentityModel.oidcClient or IdentityModel?
There is no discoveryDocument?
How do wrap my loginrequest with OpenID protocal and get authoried and Jwt token?

**Comment by leastprivilege** [comment]
Please check the docs for an overview of what this library is (and isn't)

https://identitymodel.readthedocs.io/en/latest/
