### ISSUE TITLE
OAuth2 with open id connect for asp.net web application

### ISSUE THREAD

**Issue by srinivasboddu** [DuendeArchive/IdentityModel#345]
Hi there
I've been trying to set a single sign on identity check with the help of third party IAM (identity access manager)   with OAuth2 and OpenID connect in web application.
I saw many code samples but has not found a suitable one for me yet.

My current application is in VB.net with asp.net framework 462
I've imported standard  libraries IndenityModel, IdentityModel.oidcClient
 
App flow should be:
 Access the URL of my web client app
 While launching the app in browser, app redirect the user to IdentityAccessManager (IAM) and  key in user credentials.
 After evaluating the identity of user credentials, IAM app redirect the http request to my web client app.

Dim oAuthPolicy as Policy  = New Policy() with { .ValidateTokenIssuerName =False, .RequireAuthorizationHashCode =False}
Dim authOptions as oidcClientOptions = New oidcClientOptions() with { .Authority= "IAMURL", .ClientID= "clientID", .scope="OpenID",.ResponseMode="redirect"
                                                                                                                     .redirectURI= "myClientWebAppURL"}

Dim objState as AuthorizeState = oidcAuthClient.PrepareLoginAsync().Result
result = await oidcAuthClient.LoginAsyn()

Exception: SystemBrowser is nothing

When I read the docs, docs has extension methods for "DiscoveryDocument" and I could find any such methods with IdentityModel.oidcClient "3.1.2" 
I'm not sure , whether I'm in right track of integrating this Single sign in  identity check with OAuth with OpenID connect ....
Please help

**Comment by leastprivilege** [comment]
Please check the docs for an overview of what this library is (and isn't)

https://identitymodel.readthedocs.io/en/latest/
