### ISSUE TITLE
I got Unexpected character encountered while parsing value: e. Path '', line 0, position 0 when retrieve UserInfo

### ISSUE THREAD

**Issue by tungserver** [DuendeArchive/IdentityModel#346]
Hi,
I got the error message **Unexpected character encountered while parsing value: e. Path '', line 0, position 0.** when I try use to GetUserInfoAsync function to get user info
![2020-08-28_20-32-38](https://user-images.githubusercontent.com/8380722/91566314-aa887c80-e96d-11ea-9b58-b66005ad69cc.png)
 I use ASP NET MVC 5 and .NET Framework 4.8

**Comment by leastprivilege** [comment]
Did you ever resolve this problem?
