### ISSUE TITLE
RequestauthoizationCodeTokenAsync is unclear

### ISSUE THREAD

**Issue by amitbarkai** [DuendeArchive/IdentityModel#347]
Hi
i'm am trying to implement the client_secret_jwt option  , but something is unclear for me
i am trying to find a clear working example how to implement it without any success.
to my understanding when working with the client_secret_jwt option , you need to create a ClientAssertion object

            var request = new AuthorizationCodeTokenRequest()
            {
                Address = opEndPoint.TokenEndpoint,
                ClientId = clientID,
                ClientSecret = clientSecret,
                Code = code,
                ClientAssertion = new ClientAssertion()
                {
                    Type = OidcConstants.ClientAssertionTypes.JwtBearer,
                    Value = clientAuthJwt
                },
                RedirectUri = opEndPoint.RedirectUri,
                GrantType = OidcConstants.GrantTypes.AuthorizationCode
            };
       
            var response = client.RequestAuthorizationCodeTokenAsync(request).Result;

what i don't understand is why to i need to pass the clientid and client secret ? 
since it contradict with client_assertion idea.

in addition , how to i need to encrypt the my client_assertion ?
thanks

**Comment by leastprivilege** [comment]
what i don't understand is why to i need to pass the clientid and client secret ?

> you don't. The assertion might replace those values. Depending on the assertion type.

**Comment by amitbarkai** [comment]
unless i am still missing something
the clientID is a mandatory field when using the RequestAuthorizationCodeTokenAsync function
when passing a ClientAssertion is needs to be encrypted with one of the secrets in the OpServer ( on the application)
regarding to my issue i had to **AddJwtBearerClientAuthentication** 

and i the client secret 
    ClientSecrets =
    {
        new Secret("a valid SH256 key".Sha256())
    }

and i the the the ClientAssertion jwt object should hold the same key as well
siginingCredentials = new SigningCredentials(new SymeticSecurityKey(Encoding.UTF8.GetBytes(secret),SecurityAlgrithms.HmacSha256)

**Comment by leastprivilege** [comment]
ClientId is mandatory per OAuth spec. The client assertion replaces the client secret.

The exact shape or form of the assertion depends on the specific assertion type - these details are out of scope for this protocol library.

**Comment by amitbarkai** [comment]
thanks .. then i would like to ask another question 
in case i am using this secret for my client
ClientSecrets =
{
new Secret("mySecret".Sha256())
}

what should i use in the siginingCredentials 

// this one is not working 
siginingCredentials = new SigningCredentials(new SymeticSecurityKey(Encoding.UTF8.GetBytes("mySecret"),SecurityAlgrithms.HmacSha256)

**Comment by amitbarkai** [comment]
just to be sure that my question is clear
lets say i've configured my client on the sever side with a sharedsecret as follow
new Client 
{
  ClientId = "myClientId"
  ClientSecrets = {
    new Secret("MyVerySpecialSecret".Sha256())
}

on the client side
i would like to get an AuthorizationCode using **jwt**

            var securityToken = tokenHandler.CreateJwtSecurityToken(
                issuer: clientID,
                audience: opEndPoint.TokenEndpoint,
                subject: new ClaimsIdentity(new List<Claim>()
                {
                            new Claim(JwtClaimTypes.JwtId, Guid.NewGuid().ToString()),
                            new Claim(JwtClaimTypes.Subject, clientID),
                            new Claim(JwtClaimTypes.IssuedAt, new DateTimeOffset(now).ToEpochTime().ToString(),
                                ClaimValueTypes.Integer64)
                }),
                expires:now.AddMinutes(5),
                **signingCredentials: new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(clientSecret)), SecurityAlgorithms.HmacSha256Signature)**
            );

            var clientAuthJwt = tokenHandler.WriteToken(securityToken);
var request = new AuthorizationCodeTokenRequest()
        {
            Address = opEndPoint.TokenEndpoint,
            ClientId = clientID,
            Code = code,
            ClientAssertion = new ClientAssertion()
            {
                Type = OidcConstants.ClientAssertionTypes.JwtBearer,
                Value = clientAuthJwt
            },
            RedirectUri = opEndPoint.RedirectUri,
            GrantType = OidcConstants.GrantTypes.AuthorizationCode
        };
   
        var response = client.RequestAuthorizationCodeTokenAsync(request).Result;

i'm getting "invalid_client" , so clearly the SigningCredentials i am using is not correct
could not find anywhere an example for the sharedsecret ?

**Comment by leastprivilege** [comment]
This is really not the place to discuss protocol details or even IdentityServer configuration. So I recommend you read up the appropriate docs.

But in your above sample you simply set a client secret in IdentityServer - not key material for an assertion.
