### ISSUE TITLE
Ignored seed? Why??

### ISSUE THREAD

**Issue by lohoris-crane** [DuendeArchive/IdentityModel#348]
I was a bit shocked reading this:

```
        /// <summary>
        /// Initializes a new instance of the <see cref="CryptoRandom"/> class.
        /// </summary>
        /// <param name="ignoredSeed">seed (ignored)</param>
        public CryptoRandom(Int32 ignoredSeed) { }
```

The seed in random routines is vital for many testing purposes. Why would you ever ignore it?

_Plus, why would you also create a trick method like this one - just don't create it at all. But that's just a side-note._

**Comment by leastprivilege** [comment]
Well - this implementation does not need a seed since it is using the OS provided random number generator.
