### ISSUE TITLE
provide interfaces for mocking client calls

### ISSUE THREAD

**Issue by rethabile-dev** [DuendeArchive/IdentityModel#35]
It is possible to provide interfaces for the purpose of mocking for unit testing?

**Comment by leastprivilege** [comment]
More details please.

**Comment by rethabile-dev** [comment]
I inject `TokenClient` like this in controller:

    private readonly IRepository<Item> _repo;
    private readonly TokenClient _client;

    public MyController(IRepository<Item> repo, TokenClient client)
    {
       _repo = repo;
       _client = client;
    }

    public async Task<IActionResult> Create([FromBody]Item item)
    {
         // I'd like to mock the following and others during my unit-testing
          var tokenResponse = await _client.RequestClientCredentialsAsync(...); 

         . . .
    }

**Comment by leastprivilege** [comment]
I see - I suggest you rather use the inner handler to mock the "network".

**Comment by rethabile-dev** [comment]
thanks. i'll give that route a shot.
