### ISSUE TITLE
DiscoveryPolicy - Define IAuthorityValidationStrategy in the ValidateEndpoints and ignore the allowedHosts validation

### ISSUE THREAD

**Issue by shaisherman** [DuendeArchive/IdentityModel#351]
Hi,

I have 3 related questions about the "DiscoveryDocumentResponse.ValidateEndpoints"  :

1. In the DiscoveryPolicy, I can create and change the IAuthorityValidationStrategy for the "ValidateEndpoints" procedure. 
The problem is that before that validation of IAuthorityValidationStrategy is taking place, there is a validation over the allowedHosts. If my logic includes validation but I don't want to check the host 'Authority' by just comparing the Uri authority to the allowed hosts, is there any kind of way to do so and use the IAuthorityValidationStrategy without the "allowedHosts" validation?
(The only way that I found is to set the policy.ValidateEndpoints flag to false but in this case, the IAuthorityValidationStrategy will also not be used.)

2. There are some cases that an OpenId service provider change domains (Happened in google a few years ago). 
Using a static list of "allowedHosts" could fail in runtime if the provider will change endpoint domains.
Is there any conventional way to get the endpoints, securely, during runtime?

3. In the DiscoveryDocumentResponse, one of the element criteria for validation is that it will end with the "endpoint" string. 
Is there some alternative that will support customization and supply ability to use an ignore list for specific keys in the JSON result?

Thanks and Regards,
Shai

**Comment by leastprivilege** [comment]
Yea - it is what it is and it's too complicated.

This library is the only one I am aware that does all these extra checks. But you can also turn them off completely.

**Comment by shaisherman** [comment]
Hi Dominick.
Thanks for your replay. 

The problem is:
There are some OIDC services providers (Like Google for example) that are using a base Url for the discovery and distinct URL for the services. 
Some of them even changing their discovery URL, so even if the validation will pass by adding the discovery URL, it could fail in the future (if the OIDC provider will change the address of the discovery). 

Is there any procedure to get the discovery URL from the services and add it to the discovery policy (_DiscoveryPolicy.AdditionalEndpointBaseAddresses_)  , for _**preventing blocking failure**_ while keeping the discovery **_secure_**?

**_Is there any way to secure the discovery URL but preventing this kind of failure?_** 
What is the solution to this security issue?

**Comment by shaisherman** [comment]
Hi Dominick,

Again, Thanks for your help and support.

The IdentityModel is very suitable for our goals and needs so we are trying to find a secure solution that will work.
This issue is our main showstopper.

I will try to describe our issue clearly and accurately as possible. 
Our main issue is failures in discovery validation because of the endpoint validation. 

### Our main questions
1. Endpoint validation - why hostname validation is needed?  Why using "AuthorityValidationStrategy" is not enough?
2. How to cope with changes in endpoints hosts?  Is there any way to cope with this issue without breaking security?
(The OIDC discovery protocol could change by the providers. In most cases, new endpoints added along the way). 

**Technical Details:**
In the DiscoveryDocumentResponse->ValidateEndpoints, the validation is mostly on the jwks_uri and endpoints in the JSON discovery document.
In several cases, the endpoints hosts are different from the discovery URL host. In these cases, the discovery will not pass the endpoint validation. 
If the "AllowedHosts" will be configured in the DiscoveryPolicy, it still could fail in cases that the identity provider will add a new endpoint later on.

**Example**
A specific example for our problem is Google (We are using multiple OIDC providers)
Google discovery URL is "https://accounts.google.com/.well-known/openid-configuration" but a lot of the endpoints configured with different hosts:
* "token_endpoint": "https://oauth2.googleapis.com/token" 
* "userinfo_endpoint" : "https://openidconnect.googleapis.com/v1/userinfo".
* authorization_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
*  "jwks_uri": "https://www.googleapis.com/oauth2/v3/certs"
Google may also add new additional endpoints with different hostnames and cause the discovery validation to fail.

We appreciate your help and support. 
**Thanks a lot!**

**Comment by leastprivilege** [comment]
Endpoint validation is an optional validation check to further lock down the discovery endpoint. Feel free to turn it off if it is too restrictive.

**Comment by shaisherman** [comment]
> Endpoint validation is an optional validation check to further lock down the discovery endpoint. Feel free to turn it off if it is too restrictive.

Its not a security risk?

**Comment by leastprivilege** [comment]
It lets you lock down endpoints. E.g. for your own discovery documents. If you don't control the endpoints of the server, then you cannot use it.

**Comment by shaisherman** [comment]
> It lets you lock down endpoints. E.g. for your own discovery documents. If you don't control the endpoints of the server, then you cannot use it.

**Comment by shaisherman** [comment]
Thanks for your support! 
It was very helpful. 
We will disable the endpoint validation, as part of our DiscoveryPolicy configuration.
