### ISSUE TITLE
[Question] GetDiscoveryDocument doesn't honor redirect

### ISSUE THREAD

**Issue by joacar** [DuendeArchive/IdentityModel#354]
Hi,

First of, great job regarding Identity* (and forward with Duende).

## Problem

The extension method `GetDiscoveryDocumentAsync()` doesn't honor redirects and responds with error policy something like `Issuer doesn't match Authority <url>`. Perhaps this is intended due to security reasons. In that case, how to properly handle switching path base for `/.well-known/openid-configuration`?

### Packages used

IdentityServer: 4.0.4
IdentityModel: 4.3.0

## Background

I've an application running with IdentityServer (shared process) and new requirement is to secure the _API endpoints_ with mTLS and leave authorization as is. Current setup is IIS as public facing proxy, then nginx and finally app inside Docker, so mTLS won't be implemented but instead I'll use client certificate authentication to protect endpoint.
Back to the point; I'm in a situation where I need to change the path base from empty to `auth` and those clients correctly using the discovery endpoints should continue to do so by just following the redirect.

**Comment by leastprivilege** [comment]
A redirect is very unusual. maybe the reverse proxy should rather re-write it.

Have you found any other client library that accepts that?

**Comment by joacar** [comment]
>A redirect is very unusual. maybe the reverse proxy should rather re-write it.

This is what I'm planning to do. Reason for asking the question was I was tweaking my unit tests/application to handle this. For now I just changed that base address on the client created from the `WebApplicationFactory`.

>Have you found any other client library that accepts that?

No.

To support this scenario, the [end operation](https://github.com/IdentityModel/IdentityModel/blob/5ca6e0983a132c3cd76ca3e1561f4ce3f9df7061/src/Client/Extensions/HttpClientDiscoveryExtensions.cs#L77) need *not* to follow redirect so that the URLs can be updated or if the value is in a location header. This raises the question if only redirects within same domain should be allowed and probably many more questions.
