### ISSUE TITLE
Introspection response Claims don't have issuer assigned

### ISSUE THREAD

**Issue by putnap** [DuendeArchive/IdentityModel#357]
Even though returned scopes from introspection contain issuer, created claims use LOCAL AUTHORITY. Would it make sense to search for issuer in scopes and use it when creating claims in `TokenIntrospectionResponse.cs`?

I saw there is a similar issue #250, but for different endpoint. Any thoughts or suggestions?

**Comment by leastprivilege** [comment]
why?

**Comment by putnap** [comment]
We use access and reference tokens in the same solution with same authorization handler and that handler checks issuer on claims. 

We use it as a filter in some cases, because our solutions use several different tokens with different issuers.

**Comment by leastprivilege** [comment]
I see - what you mean with 

> Would it make sense to search for issuer in scopes

**Comment by putnap** [comment]
Based on spec one of the scopes returned is issuer. It's with `iss` name. So code could find that scope and use it's value as issuer value for all claims.

**Comment by leastprivilege** [comment]
You mean the iss claim? OK - do you want to draft a PR?

**Comment by putnap** [comment]
If it's not done yet, I'd like to do it over the weekend.

**Comment by leastprivilege** [comment]
merged. thanks!
