### ISSUE TITLE
Set tokenRequest/protocolRequest Address property with a relative address results in a invalid URI exception + FIX

### ISSUE THREAD

**Issue by mkeus** [DuendeArchive/IdentityModel#361]
When I set the address property of a TokenRequest object with a relative URL, because the httpClient has a base URI, this results in a invalid URI exception: _"System.Private.Uri: Invalid URI: The format of the URI could not be determined."_

This can be fixed in [ProtocolRequest.cs](https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Messages/ProtocolRequest.cs)
function Prepare 
line 178: 
if (Address.IsPresent())
{
     RequestUri = new Uri(Address);
}

**Change to:**

if (Address.IsPresent())
{
     RequestUri = new Uri(Address, , UriKind.RelativeOrAbsolute);
}

**Comment by leastprivilege** [comment]
Why do you want to set a relative URI? Relative to what?

**Comment by mkeus** [comment]
We have a service class with a HttpClient injected by DI. This HttpClient has a BaseAddress (our identityserver). In the service class we have multiple calls to various endpoints on the BaseAddress. One of the calls is /connect/token.

~~~~
public Task<TokenResponse> RequestToken()
{
    var passwordTokenRequest = new PasswordTokenRequest
    {
               Address = IdentityServerOptions.TokenRoute,
                ClientId = IdentityServerOptions.ClientId,
                ClientSecret = IdentityServerOptions.ClientSecret,
                Scope = IdentityServerOptions.Scopes,
                UserName = IdentityServerOptions.UserName,
                Password = IdentityServerOptions.Password
     };

    return HttpClient.RequestPasswordTokenAsync(passwordTokenRequest);
}
~~~~
- `TokenRoute = "connect/token"`
- `HttpClient.BaseAddress = new URI("https://awsomeIdentityServer.domain.tld", UriKind.Absolute); // works also without the UriKind`

This worked fine under identityModel 3.10.10 but migrating to identityModel 4.5.0, this ends in the invalidUri exception because of the new Uri(addresss in the ProtocolRequest.cs). IdentityModel 3 uses Request.cs

**Comment by leastprivilege** [comment]
I see. Do you want to send a PR?

**Comment by mkeus** [comment]
yes I will send a PR, have to dive in to that.

**Comment by leastprivilege** [comment]
done
