### ISSUE TITLE
Expose Authentication time in token response

### ISSUE THREAD

**Issue by vbjay** [DuendeArchive/IdentityModel#363]
See IdentityModel/IdentityModel.OidcClient#277.

The [TokenResponse](/IdentityModel/IdentityModel/blob/main/src/Client/Messages/TokenResponse.cs) should expose the [auth_time](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) value.

**Comment by leastprivilege** [comment]
I disagree. auth_time is a claim. TokenResponse models an OAuth token response. This is a protocol libary.

**Comment by vbjay** [comment]
Ok.  Makes sense.  So instead just fix the expires in type and update the oidc client to get the claim?

**Comment by vbjay** [comment]
I just think if you allow for [expires_in](https://github.com/IdentityModel/IdentityModel/blob/cc844704fc99d4efa116792e66d4b9d369bb58c9/src/Client/Messages/TokenResponse.cs#L74), that auth_time should be included also.

**Comment by vbjay** [comment]
I just added a fixup commit that makes it nullable.  https://github.com/IdentityModel/IdentityModel/pull/364/commits/d411689549bb8f42e1eee37270a58d561ffd0a91

**Comment by leastprivilege** [comment]
> I just think if you allow for expires_in, that auth_time should be included also.

a) expires_in is about the access token (OAuth), auth_time is the time of the user authentication (OIDC)
b) expires_in is a official specified response parameter in OAuth, auth_time is a claim in the ID token (this library would first need to validate the token before it can use values from it).

https://tools.ietf.org/html/rfc6749#section-4.1.4

**Comment by vbjay** [comment]
I see.  I'll move it to oidcclient. Thanks.

**Comment by vbjay** [comment]
I'll adjust the pull request to just do the epires_in fix.

**Comment by vbjay** [comment]
Ok.  Expires_in isn't the same as the identity token's expires_in.  I'll rework in oidc client.
