### ISSUE TITLE
Ordinal string comparison 

### ISSUE THREAD

**Issue by MentorMateYosif** [DuendeArchive/IdentityModel#37]
Hello, I have noticed that there is a ordinal string comparison when the Issuer is validated.
It this intentional? For security reasons may be?

`public bool ValidateIssuerName(string issuer, string authority)`
        `{`
           ` return string.Equals(issuer, authority, StringComparison.Ordinal);`
`        }`

Can we switch that to StringComparison.OrdinalIgnoreCase ?
The same thing I saw when the allowedAuthorities are checked.

CC: @brockallen

**Comment by leastprivilege** [comment]
That's what the spec says - yes.
