### ISSUE TITLE
ProtocolResponse properties cause NullReferenceException when HttpResponse is null

### ISSUE THREAD

**Issue by daiplusplus** [DuendeArchive/IdentityModel#370]
### Summary

`ProtocolResponse`s `HttpStatusCode` and `HttpErrorReason` do not safely dereference the `HttpResponse` property which causes a `NullReferenceException` - this happens when `ProtocolResponse` is instantiated from an `Exception`.

[Microsoft strongly recommends that property getters do not throw exceptions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property).

### Repro steps:

```
ProtocolResponse resp = ProtocolResponse.FromException<ProtocolResponse>( new InvalidOperationException( "Turboencabulator's amulite is not prefabulated." ) );
Assert( resp.HttpStatusCode != HttpStatusCode.OK ); // Throws NullReferenceException
```

### Proposed fix:

Changing the properties to return nullable-types would be breaking, but returning `default` should be acceptable as `default(HttpStatusCode)` is undefined.

```
    /// <summary>
        /// Gets the HTTP status code - or <c>0</c> when <see cref="HttpResponse" /> is <see langword="null"/>.
        /// </summary>
        /// <value>
        /// The HTTP status code.
        /// </value>
        public HttpStatusCode HttpStatusCode => this.HttpResponse?.StatusCode ?? default(HttpStatusCode);

        /// <summary>
        /// Gets the HTTP error reason - or <see langword="null"/> when <see cref="HttpResponse" /> is <see langword="null"/>.
        /// </summary>
        /// <value>
        /// The HTTP error reason.
        /// </value>
        public string HttpErrorReason => this.HttpResponse?.ReasonPhrase ?? default;

```

**Comment by leastprivilege** [comment]
thanks! If you want to do a PR, feel free. Otherwise I will update the code.

**Comment by leastprivilege** [comment]
done. thanks
