### ISSUE TITLE
Are their any practical purposes to call .GetDiscoveryDocumentAsync instead of hardcoding endpoints for major known identity providers like Microsoft?

### ISSUE THREAD

**Issue by felinepc** [DuendeArchive/IdentityModel#376]
Following the tutorials and documentations on ```IdentityModel```, I see the common pattern for common tasks such as requesting refresh tokens is to:

1. Set ```HttpClient``` base address to that of the authority, then call ```.GetDiscoveryDocumentAsync``` to obtain a meta data response.
2. Using the response object to obtain the necessary info, most likely the ```TokenEndPoint```, then proceed to perform necessary tasks such as ```.RequestRefreshTokenAsync```.

I understand this obviously was designed to properly work with any OIDC IDP. But if our target is the major well known IDPs such as Mirosoft/Google etc, is it problematic if we skip over the discovery and go straight to the request using constant endpoint URIs, saving an external http api call?

The way I see it:

1. The base authority has to be hard-coded somewhere anyway. If the base authority does not change, there is almost no chance for these providers to change their token endpoints.

2. I see that a major role of ```.GetDiscoveryDocumentAsync``` is to verify issuer/endpoint URI etc, but in reality I found that I had to disable this for many big IDPs like Microsoft because their URIs can't pass validation (is it their fault that they're not conforming to some standard?)

Your insights on this would be appreciated.

**Comment by leastprivilege** [comment]
Well - any endpoint URLs are strictly speaking implementation details. The only thing that must be kept stable is the base address. Also key material will change periodically.
