### ISSUE TITLE
System.MissingMethodException when using `new DiscoveryClient(uri)`

### ISSUE THREAD

**Issue by mshwery** [DuendeArchive/IdentityModel#38]
When executing this
```c#
[HttpGet]
public async Task<IHttpActionResult> GetOpenId(string code, string state) {
    var discoveryClient = new DiscoveryClient(issuerUri);
    // rest omitted for brevity, it breaks here
}
```

I get
>`Method not found: 'Void IdentityModel.Client.DiscoveryClient..ctor(System.String, System.Net.Http.HttpMessageHandler)'.`

Response from a Web Api 2 action:
```xml
<Error><Message>An error has occurred.</Message><ExceptionMessage>Method not found: 'Void IdentityModel.Client.DiscoveryClient..ctor(System.String, System.Net.Http.HttpMessageHandler)'.</ExceptionMessage><ExceptionType>System.MissingMethodException</ExceptionType><StackTrace>   at Admin.OpenIdController.&lt;GetOpenId&gt;d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Admin.OpenIdController.GetOpenId(String code, String state)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.&lt;&gt;c__DisplayClass12.&lt;GetExecutor&gt;b__8(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.&lt;SendAsync&gt;d__1.MoveNext()</StackTrace></Error>
```

**Comment by leastprivilege** [comment]
Try to isolate that in a simple repro - like a console app.

**Comment by mshwery** [comment]
It is already a simple example. I have a single controller with a single action (example above). I get this error when using this constructor from `IdentityModel.Client`:

```
new IdentityModel.Client.DiscoveryClient("http://issuer.example.com");
```

I've tried with the latest version `2.5.1` and `2.6.0` from nuget. Both have the same result when using the `DiscoveryClient` constructor.

**Comment by leastprivilege** [comment]
So i did this in a .NET 4.6 console app - and it worked fine.

```csharp
static void Main(string[] args)
{
    var client = new DiscoveryClient("https://demo.identityserver.io");
    var disco = client.GetAsync().Result;

    Console.WriteLine(disco.TokenEndpoint);
}
```

IOW - if you want help - we need more info how to repro. and that involves work on your side.

**Comment by mshwery** [comment]
Hm, interesting. Which version of the package?

I'll put together an example repo to see if I can repro outside of my project.

**Comment by leastprivilege** [comment]
2.6

**Comment by kveck** [comment]
I have the same problem - any solution?

*** UPDATE *** 
I got around the issue by using the static DiscoveryClient.GetAsync() method

**Comment by leastprivilege** [comment]
which under the covers calls the ctor.

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/DiscoveryClient.cs#L17

**Comment by mshwery** [comment]
@kveck the same thing resolves the issue for me as well (calling the static method). Invoking the constructor directly fails still (despite the static method calling it under the hood).

Something about that second/optional param is causing an issue when called outside of the context of the class for me, presumably. This is in a .NET 4.5 WebForms application, so there may be something going on with that.

**Comment by leastprivilege** [comment]
Nobody was able yet to give me exact repro steps.

I did a new release yesterday. Try it again in a minimal repro scenario. And tell me exactly where it is failing. Until I am closing.

**Comment by mshwery** [comment]
Figured it out. I had to add a `<runtime>` binding redirect for `System.Net.Http` for some reason...

```xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="<public key>" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

After that I could invoke the constructor without fail.

**Comment by jmoral4** [comment]
Is there presently a resolution to this problem? This MethodNotFound issue seems to appear when linking 2x (Library built against ID4, referenced by another library, ultimately being loaded by a winforms app)

**Comment by latchkostov** [comment]
I am facing the same issue.  

I have a project `IdentityServer4.Management` which has references to `IdentityServer4.EntityFramework 1.0.1` and `IdentityServer4.AccessTokenValidation 1.2.1`.

In the Startup.cs I have:

```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
	Authority = authority,
	RequireHttpsMetadata = false,
	ApiName = "apiResource1"
});
```

Standalone, that project works fine.  However, I have an integration tests project which has a reference to `IdentityServer4.Management` project.  When I try to create a TestServer in the following way:

```
Environment.SetEnvironmentVariable("AuthorityAddress", _identityServer.BaseAddress.ToString());
_managementServer = new TestServer(new WebHostBuilder()
	.UseStartup<Startup>()
	.UseEnvironment("IntegrationTest"));
_managementClient = _managementServer.CreateClient();
```

I receive the following error message in the output of my test:

> Message: System.MissingMethodException : Method not found: 'System.ValueTuple`2<System.String,System.String> IdentityModel.Client.DiscoveryClient.ParseUrl(System.String)'.

Not entirely sure what I am doing wrong.

**Comment by jmoral4** [comment]
My issue ended up being a conflict in System.Net.Http binding as alluded to by previous posters (discovered via Fusion Logs). I had a parent project linking the GAC default 4.0.0.0 version while the Identity Server project was linking the Nuget served 4.1.1.1.

As for your issue @blgrnboy I believe that is related to the host project not resolving the System.ValueTuple Nuget dependency. You'll have to look at how you're linking the projects but ultimately you will need to ensure that the parent project can find all of the dependencies. Fusion logs will give you a better idea of what paths are being searched and what is missing.

**Comment by leastprivilege** [comment]
The GAC must burn in a tire fire!

**Comment by JacekKosciesza** [comment]
@blgrnboy I had similar issue (exception was also coming from IdentityServer4):

> Message: System.MissingMethodException : Method not found: 'System.ValueTuple`2<System.String,System.String> IdentityModel.Client.DiscoveryClient.ParseUrl(System.String)'.

Solution for me was to upgrade project's target framework from .NET 4.6.1 to .NET 4.7
```
<TargetFramework>net47</TargetFramework>
```

**Comment by leastprivilege** [comment]
Probably related to this 
https://github.com/IdentityModel/IdentityModel2/issues/70

**Comment by kspearrin** [comment]
This also broke for me when updating VS 2017 to 15.4.4. I had to install .NET Framework 4.7 SDK from the VS installer and update my projects to target `net47` (previously `net461`).

**Comment by leastprivilege** [comment]
Tbh. I am sick of figuring out which part of the .net tooling is now broken again.

**Comment by robearlam** [comment]
Thanks @kspearrin, that fix worked for me, though you made a typo it should be .NET 4.7 SDK.

Painful issue to figure out though! argh!

**Comment by eric-swann-q2** [comment]
FYI, I ran into this issue recently and this framework 4.7.1 patch/update fixed it: https://support.microsoft.com/en-us/help/4054856/net-framework-4-7-1-update-kb4054856

**Comment by softarch74** [comment]
I am seeing this error with the latest nuget packages. I have a net 471 project.

System.MissingMethodException: 'Method not found: 'Void IdentityModel.Client.DiscoveryClient..ctor(System.String, System.Net.Http.HttpMessageHandler)'.'

Anyone else still seeing this? It's driving me nuts!

I am trying to use the OidcClient to login via LoginAsync. That is when I get this.

**Comment by softarch74** [comment]
Upon further investigation, this appears to be related to the fact that my dll is actually providing Powershell command list. I do not have a config file where I can do a binding redirect.

@leastprivilege I have done a clone of the repository and created a specific net471 target that does not specifically pull in the system.net.http library, since 471 now has what it needs. 

This resolve my issue. Any chance we can get an official release that has a 471 target?

**Comment by leastprivilege** [comment]
Do a PR to show me how that csproj would look like.

**Comment by kosa-gyula-77** [comment]
I have got similar issue for the constructor of IdentityModel.Client.TokenClient (in IdentityModel 3.8.0) and adding System.Net.Http to my project as package dependency resolved the issue.

Project target framework: .NET Framework 4.6.2
