### ISSUE TITLE
JsonWebTokenSet parsing causes error on iOS

### ISSUE THREAD

**Issue by leonluc-dev** [DuendeArchive/IdentityModel#382]
I am currently using preview 7 of IdentityModel.OidcClient and on iOS an issue is occurring when the client tries to load the json web keys located at the jwk_uri in the discovery document.

For example, when using the 'https://login.microsoftonline.com/common/' OIDC authority like this:

```
var options = new OidcClientOptions()
{
    Authority = "https://login.microsoftonline.com/common/",
    ClientId = "myclientid",
    RedirectUri = "myredirecturi",
    Scope = "openid",
    LoadProfile = false,
};
options.Policy.Discovery.ValidateIssuerName = false; //Required for microsoft login
var client = new OidcClient(options);
var result = await client.LoginAsync(loginRequest);
```

the following error returns from the LoginAsync call:

`Error loading discovery document: Error connecting to https://login.microsoftonline.com/common/discovery/keys. The type initializer for 'System.Text.Json.JsonSerializer' threw an exception.`

After pulling the source code to my project and jumping into it deeper it seems the issue occurs in IdentityModel. 
To be precise this bit of code here:

https://github.com/IdentityModel/IdentityModel/blob/eb656074df1e5162036b3cdc5dd53d7af0753442/src/Jwk/JsonWebKeySet.cs#L55

The JsonSerializer does not properly initialize on iOS. This could potentially be related to this issue: https://github.com/dotnet/runtime/issues/31326?

**Comment by leastprivilege** [comment]
I can reproduce it. Not sure what do about though. This used to work. Is there are workaround for JsonSerializer thing?

**Comment by leonluc-dev** [comment]
It's a weird issue. I haven't been able to consistently reproduce it across all my Xamarin.iOS projects, but I haven't been able to deduce a pattern yet between the projects were it does work and those were it doesn't.

Judging by the full exception it seems it's because of a missing method in one of the dependencies for System.Text.Json (System.Text.Encoding.Web).

```
System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception. ---> 
System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00000] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00033] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonSerializer..cctor () [0x00042] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
```

It seems to be related to the wrong platform assembly or assembly version being loaded for `System.Text.Encoding.Web` (https://github.com/dotnet/runtime/issues/31066), but I haven't been able to figure out why this happens or a workaround.

**Comment by leastprivilege** [comment]
There's a new version since today

https://www.nuget.org/packages/System.Text.Encodings.Web/5.0.1

Can you give that a try?

**Comment by leonluc-dev** [comment]
I've tried explicitly adding version 5.0.1 of the `System.Text.Encodings.Web` NuGet package to the project but to no avail.

Xamarin.iOS seems to load an older version (4.x) of the `System.Text.Encoding.Web` dependency which is still missing the method mentioned in the exception.

This might be an issue related to how NuGet or Xamarin.iOS resolves the System.Text.Json dependencies when combined with certain other NuGet packages, but I'm not 100% sure on that. I haven't been able to 100% consistently reproduce it, but having `Xamarin.Essentials` somewhere in the dependency chains seems to reproduce it most consistently.

**Comment by leastprivilege** [comment]
I have a bare bones sample and can reproduce it as well - does this ring a bell @blowdart ?

**Comment by leastprivilege** [comment]
I can try to re-compile with the explicit version set...

**Comment by blowdart** [comment]
Nope, no bells, or even whistles.

**Comment by leastprivilege** [comment]
OK - I updated IdentityModel to the 5.0.1 packages of both Json and the encoder. Same result.

https://www.nuget.org/packages/IdentityModel/5.1.0-preview.1
https://www.nuget.org/packages/IdentityModel.OidcClient/4.0.0-preview.8

@blowdart Where can I open an issue for that - it only seems to happen on iOS?

**Comment by leastprivilege** [comment]
OK - well opened an issue. Not sure what else to do.

**Comment by leonluc-dev** [comment]
Looking into the referenced issues and what has been figured out there, it seems it's a type mismatch involving the `System.Memory` and `System.Buffers` NuGet packages (indirect dependencies of `System.Text.Json`) and .NET standard. The type mismatch causes the wrong `System.ReadOnlySpan` to be loaded in certain mono environments (Xamarin.iOS included) and any method using it to break.

I've tested the temporary workaround mentioned [here](https://github.com/mono/mono/issues/20805#issuecomment-791440473).
Overriding the package dependencies and explicitly excluding the assets in the iOS app csproj file does seem to fix this problem for now.
```
<PackageReference Include="System.Memory" Version="4.5.4">
    <IncludeAssets>none</IncludeAssets>
</PackageReference>
<PackageReference Include="System.Buffers" Version="4.5.1">
    <IncludeAssets>none</IncludeAssets>
</PackageReference>
```

I don't know if there's anything that can be done to implement this workaround on the `IdentityModel` side of things, since these package dependencies need to be added to the iOS app itself (to override the .NET standard type and fix the mismatch).

**Comment by leastprivilege** [comment]
Cool. Do you know how to convert a Xamarin iOS app to the SDK style format?

Like this one:
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/main/iOS_AuthenticationServices

**Comment by leonluc-dev** [comment]
Xamarin.iOS and Xamarin.Android do not support SDK style format yet (that will be introduced in .NET 6)
They do support PackageReference based NuGet management in the old csproj style, though.

You can migrate from `packages.config` to `PackageReference` through the following steps:

* Remove dll and target references to NuGet packages from the csproj file
* Create a `<ItemGroup>` in the csproj file and add the `<PackageReferences>` you need (you can omit any indirect dependency packages since the PackageReference style will include these automatically)
* Remove packages.config from the project
* Reload the project

I've done an example migration in the iOS samples here: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/pull/95/

**Comment by leastprivilege** [comment]
Thanks! OK - I added the above workaround and now the sample runs again. Let's hope the package will be fixed soon.
