### ISSUE TITLE
Use Uri instead of string datatype

### ISSUE THREAD

**Issue by vanillajonathan** [DuendeArchive/IdentityModel#386]
Use the `Uri` datatype instead of `string` where applicable. Such as for the `ClientUri`, `LogoUri`, `PolicyUri` and `TosUri` properties in the `DynamicClientRegistrationDocument` class.

**Comment by leastprivilege** [comment]
Why?

**Comment by vanillajonathan** [comment]
Because `Uri` is strongly typed, it means it is an URI. A string can be anything. It is a dedicated data type for the explicit purpose of storing and referring to URIs. This way we have more type safety. It ensures that what is passed around is indeed a valid URI. It accurately represents what it is. It avoids unintentional misuse.

**Comment by leastprivilege** [comment]
I see.
