### ISSUE TITLE
Is there support for ID Token validation?

### ISSUE THREAD

**Issue by mshwery** [DuendeArchive/IdentityModel#39]
Implementations _should_ validate the ID Token and its authenticity (that it is indeed signed by the expected Provider).

I couldn't find any explicit methods that might assist in ID Token validation – do they exist in this lib? If not, do you have suggestions for handling this?

**Comment by brockallen** [comment]
Check the IdentityModel.OidcClient library.

**Comment by mshwery** [comment]
I think I had initially tried that lib and ran into some trouble (before I had the Provider properly configured). I should try again.

The readme suggests it is built for native app environments – will it work in a .NET WebForms app?

**Comment by brockallen** [comment]
Yes, have a look at the samples: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

**Comment by leastprivilege** [comment]
For WebForms you would use the OpenID Connect MW in Katana.

**Comment by mshwery** [comment]
I can't support owin or katana in this app.

**Comment by leastprivilege** [comment]
well - then you need to do it by hand.

similar to:
https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients/src/MvcManual

But this is only a sample - there is some stuff missing.

**Comment by mshwery** [comment]
@leastprivilege cool thanks for the reference.
