### ISSUE TITLE
Support non-standard HTTP status codes in ProtocolResponse.Error

### ISSUE THREAD

**Issue by aleskazakevich** [DuendeArchive/IdentityModel#395]
**Short description**
Starting from 4.0.0 `ProtocolResponse` class counts on real value of `HttpResponseMessage.ReasonPhrase` in case of HTTP error (e.g. Error string for 401 would be "Unauthorized"). But `HttpResponseMessage.ReasonPhrase` is `null` in case of custom implementations when custom status codes are used (e.g. 498 instead of 401). So, initialization of `UserInfoResponse : ProtocolResponse` instance leads to `NullReferenceException` because `IsError` is `false` and code tries to convert `Json` to `Claims` (but there was an error and `Json` is `null`):
```
if (!IsError) // Here IsError is false, but should be true
{
    Claims = Json.ToClaims();
}
```
But it worked fine in 3.10.10 because `Response` class just ignores `HttpResponseMessage.ReasonPhrase` value while `UserInfoResponse : Response` instance creation.

**Detailed description** (sorry this is long but hope this answers many questions 😃)
I have an issue after upgrading from 3.10.10 to 4.4.0 version. Let's take a look at the `ProtocolResponse` class:

```
public class ProtocolResponse
{
    public string HttpErrorReason => HttpResponse.ReasonPhrase;
    
    public string Error
    {
        get
        {
            ...
            if (ErrorType == ResponseErrorType.Http)
            {
                return HttpErrorReason; // Attention here
            }
            ...
        }
    }
```

It counts on `HttpResponseMessage.ReasonPhrase` which is error string for standard HTTP status codes (e.g. 401 - "Unauthorized").

But I have a case when `Authorization` header is overwritten by Windows in case of Full Windows Authentication.
So, I use my custom Authorization header and custom status code for Unauthorized: let's say this is `X-Authorization` header and `498` status code (which is non-standard status code for invalid/expired token: http://getstatuscode.com/498).

And I have a special Middleware which renames `X-Authorization` header to `Authorization` on Request, and renames `WWW-Authenticate` to `X-WWW-Authenticate` on Response (because IdentityServer/IdentityModel understand only standard headers). And in case of `401` status code the Middleware changes it to `498`:
```
public async Task Invoke(HttpContext context)
{
    HttpRequest request = context.Request;
    RenameBearerAuthenticationHeaders(request.Headers, "X-Authorization", "Authorization");

    await _next(context);

    HttpResponse response = context.Response;
    bool renamed = RenameBearerAuthenticationHeaders(response.Headers, "WWW-Authenticate", "X-WWW-Authenticate");
    if (renamed)
    {
        if (response.StatusCode == 401)
        {
            response.StatusCode = 498;
        }
    }
}
```

So, when I make a request to _UserInfo endpoint_ with an _invalid access token_, IdentityServer responds with `401`, then my Middleware is triggered and changes `401` to `498`, then UserInfo response is initialized by this IdentityModel code:
```
public class UserInfoResponse : ProtocolResponse
{
    protected override Task InitializeAsync(object initializationData = null)
    {
        if (!IsError) // Here IsError is false, but should be true
        {
            Claims = Json.ToClaims();
        }
        else
        {
            Claims = Enumerable.Empty<Claim>();
        }
    
        return Task.CompletedTask;
    }
```

`IsError` is `false` because `HttpResponseMessage.ReasonPhrase` for `498` status code is `null`. So, initialization of `UserInfoResponse : ProtocolResponse` instance leads to `NullReferenceException` because code tries to convert `Json` to `Claims` (but there was an HTTP error and `Json` is `null`).

But it worked fine in 3.10.10 because `Response` class just ignores `HttpResponseMessage.ReasonPhrase` value while `UserInfoResponse : Response` instance creation:
```
if (!response.IsSuccessStatusCode)
{
    return new UserInfoResponse(response.StatusCode, response.ReasonPhrase); // Passed null 
}
...
public UserInfoResponse(HttpStatusCode statusCode, string reason) : base(statusCode, reason) // Null goes to base
{
}
...
protected Response(HttpStatusCode statusCode, string reason, string content = null)
{
    HttpStatusCode = statusCode; // 498
    HttpErrorReason = reason; // Assign null and do not count on HttpErrorReason while object creation

    if (statusCode != HttpStatusCode.OK) ErrorType = ResponseErrorType.Http;

    if (content != null)
    {
        Raw = content;

        try
        {
            Json = JObject.Parse(content);
        }
        catch { }
    }
}
```

**Feature request**
It would be nice if we save 3.x behavior and adjust `ProtocolResponse` like this:
```
public class ProtocolResponse
{
    public string HttpErrorReason => HttpResponse.ReasonPhrase;

    public string Error
    {
        get
        {
            ...
            if (ErrorType == ResponseErrorType.Http)
            {
                if (HttpErrorReason.IsPresent()) // Add this check
                {
                    return HttpErrorReason;
                }
                // To support non-standard HTTP status codes.
                return HttpStatusCode.ToString(); // Add this line: e.g. could return just status code
            }
            ...
        }
    }
```

**Comment by leastprivilege** [comment]
Could you do a PR so I can have a better look?

**Comment by vanillajonathan** [comment]
You might want to look into [`ProblemDetails`](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Extensions/src/ProblemDetails.cs), maybe that could be used instead?
It is a in the [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) standard.

**Comment by leastprivilege** [comment]
> It is a in the RFC 7807 standard.

but not in RFC 6749 ;)
