### ISSUE TITLE
Requesting a token with client_credential grant from .Net framework app with IdentityModel version 1.13.1 ?

### ISSUE THREAD

**Issue by vsakhdeo** [DuendeArchive/IdentityModel#398]
I have a web app in .Net Framework 4.7.2 that needs to request a token with this grant type and is using IdentityModel 1.13.1.

RequestClientCredentialsTokenAsync is not available as an extension method on httpclient in this version, is that correct? Is there a way to make this work without having to upgrade IdentityModel? Or would I have to upgrade?

Documentation reference for what we are trying to do:
https://identitymodel.readthedocs.io/en/latest/client/token.html
Requesting a token using the client_credentials Grant Type
The RequestClientCredentialsToken extension method has convenience properties for the client_credentials grant type:

var response = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
{
Address = "https://demo.identityserver.io/connect/token",

ClientId = "client",
ClientSecret = "secret",
Scope = "api1"
});

Thank you!

**Comment by leastprivilege** [comment]
I just had a quick look. v1.13 is from 2006 ;)

The API you mention got introduced later - so either you upgrade, or do the call by hand.

https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2

**Comment by vsakhdeo** [comment]
Yes, I know :) By hand it is for now, and will plan on upgrading it soon. Thanks for the quick response.

**Comment by vsakhdeo** [comment]
> I just had a quick look. v1.13 is from 2006 ;)
> 
> The API you mention got introduced later - so either you upgrade, or do the call by hand.
> 
> https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2



> I have a web app in .Net Framework 4.7.2 that needs to request a token with this grant type and is using IdentityModel 1.13.1.
> 
> RequestClientCredentialsTokenAsync is not available as an extension method on httpclient in this version, is that correct? Is there a way to make this work without having to upgrade IdentityModel? Or would I have to upgrade?
> 
> Documentation reference for what we are trying to do:
> https://identitymodel.readthedocs.io/en/latest/client/token.html
> Requesting a token using the client_credentials Grant Type
> The RequestClientCredentialsToken extension method has convenience properties for the client_credentials grant type:
> 
> var response = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
> {
> Address = "https://demo.identityserver.io/connect/token",
> 
> ClientId = "client",
> ClientSecret = "secret",
> Scope = "api1"
> });
> 
> Thank you!
