### ISSUE TITLE
.NET Core 1.1 not supported

### ISSUE THREAD

**Issue by ksevery** [DuendeArchive/IdentityModel#40]
Hey, so here's my issue - I'm just starting out with this library, but I lost about half an hour trying to figure out why I couldn't use anything or even add IdentityModel as a using statement. Then it hit me - I changed the project's target framework to .NET Core 1.0 from .NET Core 1.1 and it started working. So, might be good to note that.

If it matters, I got this when creating a default .NET core Console application from VS 2017's templates.

**Comment by leastprivilege** [comment]
Works for me. Restart visual studio.

**Comment by leastprivilege** [comment]
This looks rather like a bug in Visual Studio.

**Comment by leastprivilege** [comment]
Did you try that?
