### ISSUE TITLE
v5.1.0 - Cleartext Storage of Sensitive Information in Memory (CWE ID 316)

### ISSUE THREAD

**Issue by nagysana** [DuendeArchive/IdentityModel#401]
The IdentityModel 5.1.0 was scanned with the Veracode static analyzer tool (it is a policy at my company for every new library).
1 issue was found: Cleartext Storage of Sensitive Information in Memory (CWE ID 316) in '/.../messages/tokenrequest.cs' (line 81).

The detailed scan report is attached.
[IdentityModel 5.1.0 - Veracode.pdf](https://github.com/IdentityModel/IdentityModel/files/6784005/IdentityModel.5.1.0.-.Veracode.pdf)

**Comment by leastprivilege** [comment]
OK ;)

https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Messages/TokenRequest.cs#L81

..and what am I supposed to do about this?

**Comment by nagysana** [comment]
I do not know. I just reported what Veracode reported.

Using the .NET SecureString there is not real solution, but Veracode may be happy with it.

**Comment by leastprivilege** [comment]
There is nothing to do here. You can tell that Veracode ;)

**Comment by nagysana** [comment]
Answer was accepted.
