### ISSUE TITLE
Does this library support MVC 4 ? 

### ISSUE THREAD

**Issue by vietxuan-nguyen** [DuendeArchive/IdentityModel#407]
Hi,

I want to perform the OAuth 2.0 authentication flow with Azure AD. Does this library support MVC 4 ? If yes, how to implement it on MVC 4 web application? Many thanks for your advice

Thanks & Best regards

Nguyen Xuan Viet

**Comment by leastprivilege** [comment]
This library provides the protocol primitives for implementing OAuth 2.0 spec-compliant flows. It also works on .NET Framework.

**Comment by vietxuan-nguyen** [comment]
Can I use IdentityModel libarry and OWIN as middleware for MVC 4 like that Thinktecture.IdentityModel.Owin ? Many thanks for your advice

**Comment by leastprivilege** [comment]
If you can use OWIN - then I would use Microsoft's OIDC authentication middleware.
