### ISSUE TITLE
signed assembly

### ISSUE THREAD

**Issue by andy-miracl** [DuendeArchive/IdentityModel#41]
Hi,

I was wondering if there was any chance that the assembly distributed in nuget can be signed with a strong name? I need to install it in the GAC, but in order to do this I am having to decompile and resign it, which is something Id like to avoid if possible.

Thanks

Andy

**Comment by leastprivilege** [comment]
We won't strong name it.

No need to decompile - just build from source.

**Comment by alexdrl** [comment]
Why have you decided to not strong name it?
There are a lot of benefits, and .NET Core packages are all signed. See: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

Signing the assembly is an easy task, but if we do not want to take on this, you should public sign the assembly.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md

We have looked at this issue, and we are stunned about your harsh response 😞

**Comment by leastprivilege** [comment]
So the first link you mention says

>>Warning - Do not rely on strong names for security. They provide a unique identity only.

What other benefits are you seeing?

In any case - we don't do SN - have a look at this if you need it
https://github.com/dsplaisted/strongnamer

**Comment by alexdrl** [comment]
Yeah, we are aware that strong names are not a security measure, they are only for identifying the assembly. We requested this for compatibility only.

Thank you for sharing StrongNamer.

**Comment by Suriman** [comment]
@leastprivilege Many development companies sign their assemblies, Microsoft does. I do not see the problem of having one signed version and another not, for example.

**Comment by leastprivilege** [comment]
I deeply believe that strong naming is wrong and doesn't solve any problem -  but rather adds complexity. Maintaining signed and unsigned versions of an assembly is more work.

This is free software - if you need that feature sign it yourself.

This isn't meant to be rude - just a reality.

**Comment by buybackoff** [comment]
It solves a lot of problems - when there are many strong-named assemblies and I suddenly see an error with this one, while it takes just one line of code in Assembly.info `[assembly: AssemblyKeyFile("../PrivateKey.snk")]` and the private key should live publicly in repo. This is what MSFT, StackExchange and many other repos do. This is the best practice - not for security, but for convenience.

> Maintaining signed and unsigned versions of an assembly is more work.

No need to maintain two versions, just publish the private key inside the repo and keep only signed one - they could be used from unsigned assemblies, but not vice versa.


> This is free software - if you need that feature sign it yourself.

You maintain NuGet which is a part of a common toolchain. Signing is near zero-cost and one-time thing that has no single disadvantage for you other than spending that couple of minutes initially. Not that it is hard to build from the source or to fire `ildasm/ilasm` commands, but it wastes people's time for no reason. And couple of issues here clearly indicate that some people do need this.

**Comment by buybackoff** [comment]
To whom it may concern. Four commands from Developer Command Prompt for VS2017

```
sn -k PrivateKey.snk
> Key pair written to PrivateKey.snk

ildasm IdentityModel.dll /out:out.il

ilasm out.il /res:out.res /dll /key:PrivateKey.snk /out:IdentityModel.dll
> .... Signing file with strong name... Operation completed successfully

sn -vf IdentityModel.dll
> Assembly 'IdentityModel.dll' is valid

```

To get public tokens:

```
sn -p PrivateKey.snk PublicKey.snk
sn -tp PublicKey.snk
```

(had to do this several times today, created a cheat sheet for myself as well 😄 )

**Comment by the4thamigo-uk** [comment]
Yes thats what we are doing, but unfortunately we use the linux Mono buildchain and the equivalent commands dont work with this library, so having to perform this periodically with VS is a bit of a chore.

**Comment by Talegen** [comment]
It's not about whether you like something or don't. It's a matter of convenience for the end user. I don't like building installers when a zip file will do, but it's convenient for the end user.

The assumption here is people will know what to do with this library and sign it themselves. What about those developers without the skill set to research and understand the issue? I'd rather my libraries be compatible with all other libraries (signed/unsigned), then to force developers to go back and undo their strong-named signing, or put signing commands into a tool chain.

All you've done is removed some minimal "complexity" for you, and multiplied the complexity for your end users. 

I would suggest you again reconsider simply adding the auto-generated signing certificate snk into the source and strong/sign the project.

Thanks,
Rob
