### ISSUE TITLE
.NET 4.5 support dropped on version 2.7.0

### ISSUE THREAD

**Issue by hasanayan** [DuendeArchive/IdentityModel#42]
Is there any specific reason to drop.NET 4.5 support?

I understand .NET 4.5 is kind of ancient and MS has stopped the support but I am working on a project where I need to develop plugin for a .NET 4.5. I would appreciate it if you could keep supporting .NET 4.5 as long as it doesn't make things harder for you.

**Comment by leastprivilege** [comment]
NET45 is not supported anymore. We also had some issues with HttpClient which might be fixed by dropping the old version.
