### ISSUE TITLE
PCL support?

### ISSUE THREAD

**Issue by xplatsolutions** [DuendeArchive/IdentityModel#43]
I want to use the client side of IdentityServer which is the IdentityModel nuget package. It looks like PCL support is dropped. Do I have to go back to version 1.13.1 to use it with Xamarin applications?

https://www.nuget.org/packages/IdentityModel/1.13.1

**Comment by leastprivilege** [comment]
Xamarin supports netstandard now.

**Comment by xplatsolutions** [comment]
But not all projects started using it.

**Comment by leastprivilege** [comment]
IdentityModel 1.x is PCL - 2.x is netstandard.

**Comment by leastprivilege** [comment]
I don't have the cycles to maintain both - so all new stuff goes into v2.

**Comment by weitzhandler** [comment]
@leastprivilege 
Hi, due to restrictions of a library I'm using in my Xamarin project ([Prism](/PrismLibrary/Prism)), I can't switch to Standard.
So I installed 1.13.1, but what address do I provide the `TokenClient` with? Can I consume an IdentityServer4 with this version of client?

**Comment by leastprivilege** [comment]
Yes you can.
