### ISSUE TITLE
Proper way to refer to IdentityModel2 in a .netstandared2.0 library.

### ISSUE THREAD

**Issue by weliwita** [DuendeArchive/IdentityModel#49]
This issue is related to this StackOverflow question. https://stackoverflow.com/questions/44211741/how-to-resolve-httpclient-exists-in-multiple-libs/44299428.

We need to refer IdentityModel library which is targeting `.netstandared1.4` from our library targeting `.netstandared2.0`. But we also refer to `HttpClient` in our library as well. Ideally .netstandared1.4 targeted library is callable from higher version targeted library. But IdentityModel also references `System.Net.Http` outside of the standard library. So we ended up with 2 `HttpClient`s  and failed to build our project. What is the proper way to fix this? Should we wait until newer version targeting `.netstandared2.0`?

**Comment by leastprivilege** [comment]
I actually don't know - we had various problem reports because of that.

Maybe open an issue on the dotnet repo asking for right way to deal with HttpClient. Would be interested in the result.
