### ISSUE TITLE
Issue with adding IdentityModel2 package to precompiled AzureFunctions 

### ISSUE THREAD

**Issue by GreenAirplane** [DuendeArchive/IdentityModel#54]
Hello,

It looks like there is an issue related to [HttpClientExtensions.cs](https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/HttpClientExtensions.cs) and precompiled Azure Functions.

I'm receiving `System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task'1<!!0> System.Net.Http.HttpContentExtensions.ReadAsAsync(System.Net.Http.HttpContent)'` error once IdentityModel package added.

It happens in both cases during debug session and in Azure itself.

Example repository: https://github.com/GreenAirplane/IdentityModelAzureFunctionIssue
Commit which introduces the issue: https://github.com/GreenAirplane/IdentityModelAzureFunctionIssue/commit/f48e5303ab42ebba48c4e4b542ee5cad8e5bc2e2

**Comment by leastprivilege** [comment]
Sorry - don't know anything about Azure Functions. When you find the reason for the issue, let us know.

**Comment by GreenAirplane** [comment]
It looks like it happens because [HttpClientExtensions class](https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/HttpClientExtensions.cs) in IdentityModel package hides HttpContentExtensions from System.Net.Http.Formatting.dll

As a result, all standard extensions from HttpContentExtensions don't work in Azure Function once IdentityModel package added. It doesn't happen in other types of applications as far as I know. I guess, it can be related to the way how Azure Functions load types from libraries. Also, as far as I understand, the easiest solution to this issue is to rename HtppClientExtensions class to something else in order to avoid this conflict. Let me know if it makes sense for you.

**Comment by GreenAirplane** [comment]
I did some more research and found that it is a conflict between dependencies in Microsoft.NET.Sdk.Functions and IdentityModel packages. To be more specific, this issue happens because of System.Net.Http package.

There is a workaround:
Add System.Net.Http explicitly to the project and downgrade it to v.4.3.1 or 4.3.0

Hope this would help someone else.
