### ISSUE TITLE
DiscoveryResponse class can't be used independently

### ISSUE THREAD

**Issue by RickyLin** [DuendeArchive/IdentityModel#56]
If I have a discovery response string, it's quite useful to pass it to `DiscoveryResponse` class then I get all kinds of information easily.

However, currently `DiscoveryResponse` class can't be used directly because of `DiscoveryPolicy.Authority` property, it's an internal property, no way to set its value outside the assembly, I can instantiate `DiscoveryResponse` class with this constructor `public DiscoveryResponse(string raw, DiscoveryPolicy policy = null)`, pass in my raw response string, but it's `IsError` property will be true because exception will be thrown in code `allowedHosts.Add(new Uri(policy.Authority).Authority);` in `DiscoveryResponse` class.

My suggestion is:

- make `DiscoveryPolicy.Authority` property public or add a constructor `public DiscoveryPolicy(string authority)`
- `public DiscoveryResponse(string raw, DiscoveryPolicy policy = null)` will not validate the `raw` string if `policy` is null.
- tweak the `ValidateEndpoints` method, handle the situation `policy.Authority == null`

**Comment by leastprivilege** [comment]
I made Authority public - that should be enough to enable your scenario.

**Comment by leastprivilege** [comment]
give it a try. The build is available from the nuget feed

https://www.myget.org/F/identity/

**Comment by RickyLin** [comment]
@leastprivilege Thanks.
But could you please generate a higher version, e.g. 2.10.1-buildxxxxx? I got this error when adding the package from myget feed because my project has a reference to IdentityServer4:
> Detected package downgrade: IdentityModel from 2.10.0 to 2.10.0-build00141. Reference the package directly from the project to select a different version. 
> 
> MyProject.Test (>= 1.0.0) -> MyProject(>= 1.0.0) -> IdentityServer4 (>= 2.0.0-preview4) -> IdentityModel (>= 2.10.0)

**Comment by leastprivilege** [comment]
done - it's 2.11.0-build0014

**Comment by RickyLin** [comment]
I tried it out and it works very well.
Thank you.

**Comment by leastprivilege** [comment]
nuget pushed
