### ISSUE TITLE
Support for dotnet framework < 4.5.2

### ISSUE THREAD

**Issue by amitt0488** [DuendeArchive/IdentityModel#57]
Hi,
Currently this library supports dotnet framework 4.5.2 
Does it support previous versions like 4.5
Otherwise I will have to change all other projects of my solution to 4.5.2
Please let me know.
Thanks

**Comment by leastprivilege** [comment]
.NET < 4.5.2 is not supported anymore by Microsoft - so yeah maybe it is time for an upgrade ;)
