### ISSUE TITLE
DiscoveryClient doesn't obey DiscoveryPolicy.Authority

### ISSUE THREAD

**Issue by tillig** [DuendeArchive/IdentityModel#58]
`DiscoveryClient` allows you to specify a `DiscoveryPolicy` to aid in validation. However, the first thing it does in `DiscoveryClient.GetAsync` is [overwrite the policy `Authority`](https://github.com/IdentityModel/IdentityModel2/blob/2.11.0/src/IdentityModel/Client/DiscoveryClient.cs#L134) so there's no way to cause validation to obey the specified `Authority`.

The use case in which I'm hitting this is multitenancy. I have a multitenant OIDC provider [much like Azure AD](http://www.cloudidentity.com/blog/2014/08/26/the-common-endpoint-walks-like-a-tenant-talks-like-a-tenant-but-is-not-a-tenant/) where the tenant ID in the URL is case-sensitive and contains upper-case letters - `https://my.identity.server/TenantIdHere/.well-known/openid-configuration`

However, Identity Server forces the base URL to lowercase as the issuer like `https://my.identity.server/tenantidhere`. I wanted to set the authority in the validation policy to be the "normalized lowercase" version of the URL so validation would work, but that gets overwritten. I also can't address it by adding to the `AdditionalEndpointBaseAddresses` [because only the authority is used for issuer validation](https://github.com/IdentityModel/IdentityModel2/blob/2.11.0/src/IdentityModel/Client/DiscoveryResponse.cs#L184)

My current workaround is to disable issuer validation entirely.

**Comment by leastprivilege** [comment]
Authority was only made publicly writable because of https://github.com/IdentityModel/IdentityModel2/issues/56

Because of another issue, I will remove the case-sensitive comparison (or at least make it optional).

**Comment by leastprivilege** [comment]
..or if you want to make a PR for that - this would probably speed up the process.

**Comment by tillig** [comment]
Cool. Here's the design I'm thinking about, let me know if this will work:

- Add a property to `DiscoveryPolicy` called `IssuerNameComparison` that defaults to `StringComparison.Ordinal` - this will be used during comparison. It can be set to `StringComparison.OrdinalIgnoreCase` for case insensitivity, but by default will retain current behavior.
- Update `DiscoveryResponse.ValidateIssuerName` to use the `DiscoveryPolicy.IssuerNameComparison` value.
- Update `DiscoveryClient.GetAsync` to only change the `Policy.Authority` _if it's null or empty_. If the Policy already has an authority, allow validation to run against that.

Would that work?

**Comment by leastprivilege** [comment]
yes - sounds good! thanks
