### ISSUE TITLE
Introspection - Consider supporting different authentication methods

### ISSUE THREAD

**Issue by ycrumeyrolle** [DuendeArchive/IdentityModel#61]
The introspection client only support the client authentication method `client_secret_post`.
The introspection endpoint may also support other methods:
- `client_secret_basic`
- `client_secret_jwt`
- `private_key_jwt`

The discovery endpoint should be used for retrieving the following [metadata](https://tools.ietf.org/html/draft-ietf-oauth-discovery-07):
- `introspection_endpoint_auth_methods_supported`
- `introspection_endpoint_auth_signing_alg_values_supported`

Related IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#21

**Comment by leastprivilege** [comment]
moved to https://github.com/IdentityModel/IdentityModel2/issues/66
