### ISSUE TITLE
Should IntrospectionClient parameter be clientId or"scope_name" ?

### ISSUE THREAD

**Issue by MNF** [DuendeArchive/IdentityModel#62]
In the documentation example  http://docs.identityserver.io/en/release/endpoints/introspection.html 
IntrospectionClient constructor parameters are shown as for scope( is it the same asAPI?)
```
var introspectionClient = new IntrospectionClient(
    doc.IntrospectionEndpoint,
    "scope_name",
    "scope_secret");
```
However intellisense and actual code in 
https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/IntrospectionClient.cs uses clientId/clientSecret parameter names.

It causing confusion as scope, API and client are very different actors in OIdC.  

Can you make  the code/documentation  consistent, or add explanation, which parameters can be passed to IntrospectionClient.

**Comment by leastprivilege** [comment]
Well - from an identityserver point of view it is the api name and secret. 

From a pure introspection protocol point of view it is a client/secret. I updated the IS docs. thanks!

**Comment by fredvaliant** [comment]
As mention it was updated, but still the class IntrospectionClient are accepting different parameters when instantiating.

![image](https://user-images.githubusercontent.com/18463251/85091997-53eb1d80-b21b-11ea-90d1-978dedcccdff.png)


@leastprivilege ,
