### ISSUE TITLE
issue with System.ValueTuple dependency in version 2.12

### ISSUE THREAD

**Issue by MovGP0** [DuendeArchive/IdentityModel#64]
When calling the `DiscoveryClient` from an `.NET Framework 4.6.1` project with `System.ValueTuple 4.3.1` referenced, I get an exception: 

**Exception**
```
=== Pre-bind state information ===
LOG: DisplayName = System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Users/johann/AppData/Local/Azure.Functions.Cli/1.0.4/
LOG: Initial PrivatePath = NULL
Calling assembly : IdentityModel, Version=2.12.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\johann\AppData\Local\Azure.Functions.Cli\1.0.4\func.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
```

**Stack Trace**
```
   at IdentityModel.Client.DiscoveryClient..ctor(String authority, HttpMessageHandler innerHandler)
   at IdentityModel.Client.DiscoveryClient.<GetAsync>d__1.MoveNext()
```

**Comment by leastprivilege** [comment]
Any update on this?

**Comment by pixelbadger** [comment]
I have an update to this. It appears that the BCL team [added System.ValueTuple to .NET 4.7](https://github.com/dotnet/announcements/issues/25). 

In my VS2017, these BCL assemblies override any nuget packages they conflict with during build. So in my build output folder, there is a v4.0.2.0 assembly with a public key of 'b77a5c561934e089'. The nuget package assembly has a different key, so it's not just a case of setting up an assembly binding redirect.

It looks like we need a net4.7 target that drops the System.ValueTuple nuget dependency in favour of the once from the BCL.

My workaround has been to downgrade to the IdentityModel 2.0.7 nuget package - the latest that doesn't include the System.ValueTuple dependency.

**Comment by MovGP0** [comment]
@leastprivilege  I am currently using a fork of the repo in my own project instead of the NuGet package in my .net core build. this solved the issue. didn't find the time till now to create a PR. 

@pixelbadger  We should not target .NET 4.7, since it is a superset of .NET Standard 2.0. Targeting .NET Standard 2.0. would be the proper approach.

**Comment by leastprivilege** [comment]
I have a .NET Standard 2.0 target since the last update.
