### ISSUE TITLE
Token caching?

### ISSUE THREAD

**Issue by rramer-web-com** [DuendeArchive/IdentityModel#68]
The TokenClient works as expected, but do you foresee adding support for caching of that token, or is that outside the scope of the library?

For example, if the token expiration is in 3600 seconds, you could call something like client.GetOrRequestClientCredentialsAsync() and until close to expiration, you would continue to get the same response.AccessToken?

**Comment by leastprivilege** [comment]
token caching is out of scope. This is a protocol library.
