### ISSUE TITLE
Set HttpStatusCode when there is exception

### ISSUE THREAD

**Issue by momansouri** [DuendeArchive/IdentityModel#69]
Hi 
Would it not be better to set HttpStatusCode to 500 when there is an exception? 
At the moment TokenClient.RequestAsyncMethod() catches exceptions and create a new TokenReposne(exception) which results in a call to Response(exception) where I think HTTP status code may be set to 500

**Comment by leastprivilege** [comment]
Exceptions are for client side errors only - like not being able to connect to a server (e.g. TLS errors).
500 are server errors and get returned as 500.

Are you seeing different behavior?

**Comment by momansouri** [comment]
Hi, 
thanks for the reply. In my case, the OAuth server is returning an exception, however, the token response that I get contains the correct exception message but HTTP status code is 0.

**Comment by leastprivilege** [comment]
> the OAuth server is returning an exception,

You cannot return an exception over HTTP, only a status code.

**Comment by momansouri** [comment]
OAuth server returning 500 with the exception message in the content of the response. Parsing the response is throwing an exception as it is not json formatted response.

**Comment by leastprivilege** [comment]
I see - well - have a look at the code. If you have a solution we can discuss this.

**Comment by leastprivilege** [comment]
This might work now - give it a try and open a new issue with more specifics.
