### ISSUE TITLE
Please create a .net 4.7.1 dependency

### ISSUE THREAD

**Issue by ksmithRenweb** [DuendeArchive/IdentityModel#70]
What this entails is for 4.7.1 you would remove the System.ValueTuple nuget package. Allowing it to use the System.ValueTuple contained in 4.7.1.

This is a blocker for our project to go to 4.7.1, without this a runtime error occurs. Yours is the only library we are using with the issue. If need be I'll fork, and maintain it myself. But. It'd be nice if I didn't have to.

The runtime error is something like: "Method not found: ValueTuple(string,string) SomeMethod(variables)"
Which is caused because the System.ValueTuple version in .net 4.7.1 is a higher version than the nuget, so the 4.7.1 version is used. But your code is compiled against the nuget version that has a different signature. Thereby their signatures don't match and the run time error occurs.

Thanks!

**Comment by leastprivilege** [comment]
I ran into similar problems before - my understanding is that targeting .net standard 2.0 should be all thats needed. 

A similar problem is the reference to `System.Net.Http` - should the net452 reference the HttpClient from the old BCL - or the package?

Hope I can get some help @terrajobst or @davidfowl - [project file](https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/IdentityModel.csproj).

**Comment by terrajobst** [comment]
Yes, it’s a known issue. We’ll publish an announcement next week.

**Comment by ksmithRenweb** [comment]
@leastprivilege True, but that is only if you are in a position you can switch over to .net standard and .net core app. We have to wait for "other" stuff to become available in .net standard.

I spent 3 days trying to remove 4.7.1 before giving up an resetting computer. That this overrides other v4 frameworks was a bad thing. Might have been the time to put it in it's own versioned directory.

**Comment by leastprivilege** [comment]
Well - as you can see from @terrajobst reply - this is a bug in .NET. Waiting for their official statement on how to fix/workaround.

**Comment by terrajobst** [comment]
We just [published the announcement](https://github.com/dotnet/standard/issues/567).

**Comment by leastprivilege** [comment]
@terrajobst thanks - now what workaround would you recommend for this library?

**Comment by leastprivilege** [comment]
based on Microsoft's recommendation I added a net461 target

https://www.nuget.org/packages/IdentityModel/2.15.0-preview1

Can you give that a try and let me know if that fixes your problem?

**Comment by tstojecki** [comment]
Hi @leastprivilege 
Are you suggesting that using IdentityModel (2.15.0) should resolve this issue?  
We are running into The Method not found: System.ValueTuple issue in an aspnet core 2 project that targets net461 and references IdentityServer4.AccessTokenValidation package for  AddIdentityServerAuthentication() in Startup.cs.

I have just installed IdentityModel (2.15.0). The dependencies look ok to me, including the dependent packages, but the error is still happening. 

![image](https://user-images.githubusercontent.com/1306272/32544780-d7b0a9a6-c479-11e7-8df1-84b919b25560.png)

Any suggestions?

**Comment by leastprivilege** [comment]
Good question - according to Microsoft this should be fine.

Can you please add a comment here: 

https://github.com/dotnet/standard/issues/567

**Comment by leastprivilege** [comment]
Long story short: the .NET tooling is broken for the time being. Check the MS issue above for possible workarounds.
