### ISSUE TITLE
RefreshTokenHandler refresh event

### ISSUE THREAD

**Issue by swisszeni** [DuendeArchive/IdentityModel#71]
Maybe I am missing some method that already allows for this but I came along the following:

With a native app, you'd store the refresh token in a secure storage (KeyChain or whatever) and cane use the token on the next start to request a new access token.
Now if `RefreshTokenHandler` also has to refresh the access token during the lifetime of the app, there is no way for the app to know of this. If the IDP is configured to allow only for one time usage of the refresh token, this leads to an expired refresh token stored in the clients storage.

Now you could keep a reference to the `RefreshTokenHandler` and store the then-current refresh token on app suspension. But this seems somewhat hacky.

IMO it would be more elegant to raise an event when the token is actually refreshed by the `RefreshTokenHandler` allowing for the app to do what ever must be done.

Is there interest in a PR adding this or would this be out of scope for the project?

**Comment by leastprivilege** [comment]
Yes the even would be useful. Please PR

**Comment by leastprivilege** [comment]
I pushed a new nuget.
