### ISSUE TITLE
Please use framework reference to System.Net.Http in .net framework builds

### ISSUE THREAD

**Issue by maximpashuk** [DuendeArchive/IdentityModel#76]
now .csproj file have for net452 and net 461
```msbuild
  <ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">
    <PackageReference Include="System.Net.Http" Version="4.3.3" />
  </ItemGroup>
```

can you please use
```msbuild
  <ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
```

So resulting nuget package will have less package dependencies for .net framework.

@leastprivilege are you agree with this?

**Comment by leastprivilege** [comment]
No I don't.

There are other people who say this creates problems when you add other packages that depend on the nuget in the same project.

**Comment by maximpashuk** [comment]
@leastprivilege 
Popular **Refit** library (https://www.nuget.org/packages/refit)
Is an example of using framework reference to System.Net.Http for net45 profile.

csproj file
https://github.com/paulcbetts/refit/blob/master/Refit/Refit.csproj

 @onovotny edited refit .csproj file and he ```<Reference>``` to System.Net.Http for net45 and not ```<PackageReference>```, so I think this is a correct way.

@leastprivilege when you said about problems with this way - are you meaning https://github.com/IdentityModel/IdentityModel2/issues/31 issue ?
@MikaelGRA in that issue also supposed to keep System.Net.Http as framework reference for full .net framework builds.

**Comment by leastprivilege** [comment]
I honestly don't know what the right answer is.

@onovotny can you comment on that?

**Comment by clairernovotny** [comment]
There are two issues here --

The nuget version of System.Net.Http prior to 4.3.2 may have issues when used on the .net framework. If you have any .NET Standard library references, you may opt to force 4.3.2 to prevent issues since NETStandard.Library 1.6.1 uses a lower version, IIRC. I'm not sure what version the NETStandard 2.0 metapackages bring in (just haven't looked).

The alternate approach is to forgo all .NET Standard references in your .NET Framework builds and pass that problem on to someone else :) That's what we did for Refit.

The main reason was actually for people using Packages.config, which many existing projects do. Bringing in the .NET Standard deps causes 20-30 entries to be added to Packages.config (even if most are blank placeholders).

As packages.config should 🔥, I'm less inclined to care about that now.

**Comment by leastprivilege** [comment]
IOW - what do you recommend for the net452 target?

**Comment by clairernovotny** [comment]
If you don't need any other .NET Standard references for your net452 target, no reason to use the system.net.http package, just continue to use the in-box reference. I don't think there's any real reason to bring in .NET Standard for that.

**Comment by clairernovotny** [comment]
You may be hosed by `ValueTuple` anyway. Looking at its dependency graph, it has a net461 empty group, but then a netstandard1.0 that brings in netstandard.library 1.6.1.

For a net452 project, that means it'll fallback to the netstandard1.0 and thus bring in netstandard.library. That being the case, you may also want the http nuget ref to force a working 4.3.3 version.

**Comment by clairernovotny** [comment]
You can also get rid of most of the junk re documentation files. The IDE does a poor job of adding those.

Just use `GenerateDocumentationFile` and you don't need a per config path:
https://github.com/onovotny/Zeroconf/blob/dev/Zeroconf/Zeroconf.csproj#L14

**Comment by leastprivilege** [comment]
OK - whatever that means. It seems .NET is fucked ;)

**Comment by leastprivilege** [comment]
@maximpashuk feel free to PR

**Comment by clairernovotny** [comment]
@leastprivilege if your net452 dependency graph pulls in netstandard.library, which yours appears to do, I would keep the http NuGet package since the 4.3.3 version fixes the previous issues people had.

**Comment by leastprivilege** [comment]
IOW - nothing changes in the csproj, right?

**Comment by clairernovotny** [comment]
Right, looks good as-is aside from cleaning up the generate documentation entries I mentioned.

**Comment by leastprivilege** [comment]
or IOW - if I would remove ValueTuple - I could avoid the whole netstandard madness for plain old .NET...

**Comment by clairernovotny** [comment]
Yes, if you remove that, it would not bring in netstandard for .NET.

You could also bump your .NET version up to 4.6.1 and use the ValueTuple package since that also does not bring in the whole netstandard.

It's .NET < 4.6.1 that has the netstandard.library dependency. I don't know why.

**Comment by leastprivilege** [comment]
I did some cleanup - does that look right @onovotny ?

https://github.com/IdentityModel/IdentityModel2/blob/v3/src/IdentityModel/IdentityModel.csproj

**Comment by leastprivilege** [comment]
I pushed it to nuget

https://www.nuget.org/packages/IdentityModel/3.0.0-aberfeldy

@maximpashuk give it a try.

**Comment by maximpashuk** [comment]
@leastprivilege I will, thnks!

**Comment by clairernovotny** [comment]
LGTM. Only question for you to answer for yourself is what is the benefit of supporting both `net452` and `net461`. I haven't looked at your codebase, but if there aren't any ifdef's in there, what would adding `net461` add? If it's just to force the `4.3.3` http library...maybe? it's questionable though it may help people avoid subtle issues later.

**Comment by leastprivilege** [comment]
That was the advice from the .NET team for the time being until they fix a bug they have in tooling.

**Comment by leastprivilege** [comment]
https://github.com/dotnet/standard/issues/567#issuecomment-341615176

**Comment by leastprivilege** [comment]
@maximpashuk did you try it?

**Comment by maximpashuk** [comment]
@leastprivilege Yes I tried, version **3.0.0-aberfeldy** works ok for me.
Sorry, I forget to provide feedback just after I tried.

**Comment by leastprivilege** [comment]
I just pushed 3.0.0
