### ISSUE TITLE
RefreshTokenHandler timeout after so many requests due to non-disposed response

### ISSUE THREAD

**Issue by marcinbelczewski** [DuendeArchive/IdentityModel#78]
I'm using RefreshTokenHandler in a long running application targeting .NET 4.7 that makes the same HTTP call over and over again in certain intervals. After as many attempts, during which access tokens expired at least once the next call fails with timeout. 
After digging into this for a while I've found this [article](http://byterot.blogspot.com/2013/10/beware-of-undisposed-or-unconsumed-httpresponsemessage-aspnetwebapi.html)

It seems to be required to dispose of first unconsumed response - the one that resulted in 401. 
After adding "Dispose" call to RefreshTokenHandler's SendAsync method the problem no longer occurs. 

I'm not sure I've dug deep enough and what I've found is truly a problem experienced by some others and whether first response disposal is the right solution.

**Comment by leastprivilege** [comment]
can you do a PR?

**Comment by marcinbelczewski** [comment]
Sure will do. Fix would be quite simple, automated test for it not so much. Will think of something anyways.

**Comment by leastprivilege** [comment]
merged and nuget pushed- thanks!
