### ISSUE TITLE
Cannot connect to identity over Proxy server

### ISSUE THREAD

**Issue by ghost** [DuendeArchive/IdentityModel#80]
Hi,

This is more of a question and much less of an issue. I have been trying to connect to Identity Server endpoint using DiscoveryClient and it works all good however when i connect to the same endpoint over any network which uses a Proxy, i get an error which says The remote server returned an error: (407) Proxy Authentication Required. Is there a way i can get around this ?

Many Thanks 👍

**Comment by leastprivilege** [comment]
You can pass and HttpMessageHandler to the ctor. On that you can configure proxy settings.

**Comment by ghost** [comment]
@leastprivilege Thanks so very much
