### ISSUE TITLE
Provide ExpiresIn from RefreshTokenHandler.TokenRefreshed event

### ISSUE THREAD

**Issue by xperiandri** [DuendeArchive/IdentityModel#81]
If I want to use this event to update my ClaimsPrincipal I don't have expires in to save it.

**Comment by leastprivilege** [comment]
PR?

**Comment by leastprivilege** [comment]
done

**Comment by xperiandri** [comment]
Thanks!
Looks perfect.
I just wonder why its type changed from long to int. Why not uint then 😊?
