### ISSUE TITLE
Update the README for the change from AuthorizeRequest to RequestUrl

### ISSUE THREAD

**Issue by dskornalijnslijper** [DuendeArchive/IdentityModel#83]
AuthorizeRequest class was renamed to RequestUrl in [commit bd01cfaab1652f982864b3f38e2b47935a50e12d](https://github.com/IdentityModel/IdentityModel2/commit/bd01cfaab1652f982864b3f38e2b47935a50e12d#diff-4141101a2af5729a7b78ecb63db95f3d)

**Comment by leastprivilege** [comment]
thanks!
