### ISSUE TITLE
Missing AuthorizeRequest.cs

### ISSUE THREAD

**Issue by Meldow** [DuendeArchive/IdentityModel#84]
From what I can tell, AuthorizeRequest.cs is missing from release 3.0.0, or am I missing something..?

Cant RequestUrl using 

var request = new AuthorizeRequest(doc.AuthorizationEndpoint);
var url = request.CreateAuthorizeUrl(
    clientId:     "client",
    responseType: OidcConstants.ResponseTypes.CodeIdToken,
    responseMode: OidcConstants.ResponseModes.FormPost,
    redirectUri: "https://myapp.com/callback",
    state:       CryptoRandom.CreateUniqueId(),
    nonce:       CryptoRandom.CreateUniqueId());

**Comment by Meldow** [comment]
The class name was updated, but documentation was not
in README.md, where it reads 

var request = new **AuthorizeRequest**(doc.AuthorizationEndpoint);
var url = request.CreateAuthorizeUrl(
    clientId:     "client",
    responseType: OidcConstants.ResponseTypes.CodeIdToken,
    responseMode: OidcConstants.ResponseModes.FormPost,
    redirectUri: "https://myapp.com/callback",
    state:       CryptoRandom.CreateUniqueId(),
    nonce:       CryptoRandom.CreateUniqueId());

should be

var request = new **RequestUrl**(doc.AuthorizeEndpoint);
            var url = request.CreateAuthorizeUrl(
                 clientId:     "client",
    responseType: OidcConstants.ResponseTypes.CodeIdToken,
    responseMode: OidcConstants.ResponseModes.FormPost,
    redirectUri: "https://myapp.com/callback",
    state:       CryptoRandom.CreateUniqueId(),
    nonce:       CryptoRandom.CreateUniqueId());

**Comment by leastprivilege** [comment]
send a PR please
