### ISSUE TITLE
How is the TokenClient.RequestAssertionAsync used?

### ISSUE THREAD

**Issue by kevinlo** [DuendeArchive/IdentityModel#86]
TokenClient has the [RequestAssertionAsync](https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/TokenClientExtensions.cs#L113) function which set the OidcConstants.TokenRequest.Assertion field.    Where is that assertion field used?

>             var fields = new Dictionary<string, string>
>             {
>                 { OidcConstants.TokenRequest.GrantType, assertionType },
>                 { OidcConstants.TokenRequest.Assertion, assertion },
>             };

The [ConsolePrivateKeyJwtClient ](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/ConsolePrivateKeyJwtClient/Program.cs#L29) sample, on the other hand, need to set the client_assertion_type and client_assertion request parameters as an object:

```
            var assertion = new
            {
                client_assertion_type = OidcConstants.ClientAssertionTypes.JwtBearer,
                client_assertion = clientToken
            };
```

Also, the sample is calling the RequestClientCredentialsAsync, not RequestAssertionAsync that I would expect.  

When is the RequestAssertionAsync used then?   I expect that sample will call the RequestAssertionAsync and there are parameters to the RequestAssertionAsync function that will set the e client_assertion_type and client_assertion request parameters inside that function to make these two parameters mandatory, not passed as the assertion just like the sample does.

Is that RequestAssertionAsync used for another purpose?   I search the sample and can't find how it is used.

**Comment by leastprivilege** [comment]
You are right - the client sample could use the assertion method. I will change that (or send a PR if you want).

**Comment by kevinlo** [comment]
@leastprivilege 

For the OidcConstants.TokenRequest.Assertion field,[ RFC7523 Section 2.1 Using JWTs as Authorization Grants](https://tools.ietf.org/html/rfc7523#section-2.1) states this:

> The value of the "assertion" parameter MUST contain a single JWT.

So, it seems the RequestAssertionAsync is for the  "Using JWTs as Authorization Grants" only?

For the [Section 2.2 Using JWTs for Client Authentication](https://tools.ietf.org/html/rfc7523#section-2.2), it should use the RequestClientCredentialsAsync because it does not need the OidcConstants.TokenRequest.Assertion parameter and it does not need the "assertion" parameter.

I think the current sample using RequestClientCredentialsAsync may be correct.   It is just missing the sample using the RequestAssertionAsync for the Using JWTs as Authorization Grants case.   It is better to update the comment of the RequestAssertionAsync to state what it is for.

On the other hand, is it better to separate the RequestAssertionAsync into two functions RequestAssertionGrantTypeAsync and RequestAssertionClientCredentialAsync?

client_assertion_type and client-assertion-type are the mandatory parameters for the "Using JWTs for Client Authentication":

>    The value of the "client_assertion_type" is
>    "urn:ietf:params:oauth:client-assertion-type:jwt-bearer".
> 
>    The value of the "client_assertion" parameter contains a single JWT.
>    It MUST NOT contain more than one JWT.

I believe they should be set inside the RequestAssertionClientCredentialAsync function like this, instead of passing them from the caller of the function:

```
        var fields = new Dictionary<string, string>
        {
            { OidcConstants.TokenRequest.ClientAssertionType, OidcConstants.ClientAssertionTypes.JwtBearer},
            { OidcConstants.TokenRequest.ClientAssertion, assertion },
        };
```

Please update the sample and the comment to clarify it.

**Comment by leastprivilege** [comment]
You are right I was confused.

I don't want to create extension methods for all kinds of grant_type/client secret combinations. But you can create your own if you want to.

**Comment by kevinlo** [comment]
@leastprivilege 

In that case, the RequestAssertionAsync can be removed.

Firstly, it should not take the assertionType parameter as the grant_type must be this value according to the spec and the function does not validate the input parameter assertion:

>    The value of the "grant_type" is "urn:ietf:params:oauth:grant-
>    type:jwt-bearer".

Secondly, like the sample calling the RequestClientCredentialsAsync for the "Using JWTs for Client Authentication,", the "Using JWTs as Authorization Grants" can be done by calling the RequestCustomGrantAsync as shown below (I have not tested it, just write it based on the codes)

        static async Task<TokenResponse> RequestTokenAsync()
        {
            var disco = await DiscoveryClient.GetAsync(Constants.Authority);
            if (disco.IsError) throw new Exception(disco.Error);

            var clientToken = CreateClientToken("client.jwt", disco.TokenEndpoint);
            var client = new TokenClient(disco.TokenEndpoint);

           // Instead of calling RequestAssertionAsync, call the RequestCustomGrantAsync as below
           //    return await client.RequestAssertionAsync(OidcConstants.GrantTypes.JwtBearer, clientToken, "api1", );

            var assertion = new
            {
                OidcConstants.TokenRequest.Assertion = clientToken
            };
            return await client.RequestCustomGrantAsync( OidcConstants.GrantTypes.JwtBearer, "api1", assertion);
        }

Anyway, I can create my own extension to do it.
