### ISSUE TITLE
RefreshTokenHandler 401 unauthorized due to lock timeout

### ISSUE THREAD

**Issue by ammahmoud-eng** [DuendeArchive/IdentityModel#87]
In some cases `RefreshTokenHandler` will use old `access token` due to `Lock Timeout` being so small.

ex. when `client` has expired `access token` but valid `refresh token` and the server is stopped by IIS due to inactivity, a multiple calls from `client` to the `server` will delay for more than `timeout seconds (2 seconds now)` which causes at least one request to fail with 401 unauthorized due to using old access token, refresh token

**Comment by leastprivilege** [comment]
OK - then please test if higher timeout value fix the problem - then we can adjust and a config setting.

**Comment by ammahmoud-eng** [comment]
i did a simple test in my app and it did fix the problem.  for both slow internet connection and iis restart scenario

**Comment by leastprivilege** [comment]
Added the feature on dev branch
