### ISSUE TITLE
Client Credentials header creation encodes +

### ISSUE THREAD

**Issue by mantasaudickas** [DuendeArchive/IdentityModel#90]
Hi,

I have + symbols in my client secret.
When I try to call client.RequestClientCredentialsAsync method, it looks like + symbols are encoded as %2B.
So instead of "very+secret" I get "very%2Bsecret". 
When IdentityServer gets this value, validation fails and it responds with "invalid_client".

**Comment by leastprivilege** [comment]
Make sure you are on both IdentityModel 3.10 and IdentityServer 2.1.2 - there was a bug fix recently that affected client secret encoding.

According to this test - it should work
https://github.com/IdentityModel/IdentityModel2/blob/dev/test/UnitTests/BasicAuthenticationEncodingTests.cs#L16

**Comment by mantasaudickas** [comment]
Yep, I upgraded only client..
But then another question, if I upgrade IdentityServer, will older clients still work fine with it?

**Comment by leastprivilege** [comment]
Depends on the characters you are using. Most (non special) characters work fine.

**Comment by mantasaudickas** [comment]
Ok, seems like its working.. with both clients. Thank you for clarifications.

**Comment by mantasaudickas** [comment]
Still wondering.. why this encoding is needed as BASE64 ensures correct data transfer in this case.

**Comment by leastprivilege** [comment]
The OAuth spec uses additional encoding to work around the problem of not being able to use a ":" in the client id - and for consistency with the form post method of transmitting secrets.

https://tools.ietf.org/html/rfc6749#section-2.3.1
