### ISSUE TITLE
RefreshTokenHandler clearing refresh token when token endpoint returns only access token

### ISSUE THREAD

**Issue by maskati** [DuendeArchive/IdentityModel#91]
It seems like `RefreshTokenHandler` overwrites the refresh token on each token refresh:
https://github.com/IdentityModel/IdentityModel2/blob/b2a31252c863a5ae9c0e64a204f1f9dbd73c7701/src/IdentityModel/Client/RefreshTokenHandler.cs#L177

However the authorization server may choose to return only a new access token without an updated refresh token:
https://tools.ietf.org/html/rfc6749#section-5.1

This causes the refresh token to be cleared and subsequent token refreshes to fail.

**Comment by leastprivilege** [comment]
good catch. PR?

**Comment by leastprivilege** [comment]
fixed
