### ISSUE TITLE
Support POST for UserInfo request?

### ISSUE THREAD

**Issue by KevinDockx** [DuendeArchive/IdentityModel#93]
According to the OICD standard, the recommended approach for calling the UserInfo endpoint is with the GET method.  However, I sometimes encounter IDPs that don't support GET but require a POST to the UserInfo endpoint (for example: the one used by ItsMe, the Belgian Mobile ID provider).  

Would this be something you'd consider adding support for?  I'd be happy to submit a PR for this :)

**Comment by leastprivilege** [comment]
Should work already - shouldn't it?

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Endpoints/UserInfoEndpoint.cs#L54

**Comment by leastprivilege** [comment]
Ah - wrong repo.. you want client support for it...

**Comment by leastprivilege** [comment]
Probably easiest to add a PostAsync method..feel free to PR.

**Comment by KevinDockx** [comment]
Great, PR coming up!

**Comment by leastprivilege** [comment]
done
