### ISSUE TITLE
URL Encoding on Authorisation Header resulting in invalid_client

### ISSUE THREAD

**Issue by reach4thelasers** [DuendeArchive/IdentityModel#96]
We have been having authentication issues with certain credentials.  e.g.

ClientID: CL5678
Secret: IzPUVgzkGm=I7T/rOBoWVzUxX6+Ndq/dMwrsokLLF7+kg=

I've tracked this down to ClientID and Secret being individually URL Encoded, before being Base64 encoded for the Authorisation header.

There is no requirement for these properties or any aspect of the Authorisation header to be URL Encoded.

See RFC2617:
https://tools.ietf.org/html/rfc2617#section-2

As such, Identity Server was not performing URL Decoding on the Auth header and this resulted in invalid_client.

Pull Request with the fix is here:
https://github.com/IdentityModel/IdentityModel2/pull/95

**Comment by anderaus** [comment]
I believe this was changed intentionally to comply with RFC6749. See the corresponding PR for IdentityServer: https://github.com/IdentityServer/IdentityServer4/pull/2052

**Comment by slafave** [comment]
Perhaps this can be made an option to disable?  We're running IdSrv3 and can't update this package past 3.0.0 due to this.

**Comment by anderaus** [comment]
Not sure if it's the best option, but you can inherit from `TokenClient` and override `RequestAsync` to use `BasicAuthenticationHeaderValue` instead of the new `BasicAuthenticationOAuthHeaderValue`.

**Comment by slafave** [comment]
Thanks for the tip, might try that to get past the upgrade blocker

**Comment by leastprivilege** [comment]
Let me know if this doesn’t work for you.

**Comment by reach4thelasers** [comment]
Why on earth? I'm sure this must be a glaring error in RFC6749. There is no value in Url encoding and then Base64 encoding. Postman works IdentityModel doesn't work. great. HttpClient here I come.

Client Password

   Clients in possession of a client password MAY use the HTTP Basic
   authentication scheme as defined in [RFC2617] to authenticate with
   the authorization server.  The client identifier is encoded using the
   "application/x-www-form-urlencoded" encoding algorithm per
   Appendix B, and the encoded value is used as the username; the client
   password is encoded using the same algorithm and used as the
   password.  The authorization server MUST support the HTTP Basic
   authentication scheme for authenticating clients that were issued a
   client password.

**Comment by anderaus** [comment]
It's to avoid the issue occuring when the client id or secret contains a colon

**Comment by leastprivilege** [comment]
That and for consistency with the form body method where the values are also url encoded.

I guess we all have misread the OAuth2 spec - and I can see the problem. I think I will add a switch to the relevant clients to allow switching between RFC6749 and RFC2617.

**Comment by brockallen** [comment]
Could we have both client secret validators in DI? One for the correct mechanism and one for incorrect basic auth. And we'd remove the basic auth one in v3.

**Comment by leastprivilege** [comment]
I published a new version of IdentityModel - there's a new property on TokenClient that let's you choose the encoding style - it defaults to Rfc6749 behavior.

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/TokenClient.cs#L133

**Comment by leastprivilege** [comment]
Let me know if there are any issues.
