### ISSUE TITLE
Build warnings when referencing IdentityModel from a .NET 4.7.1 project

### ISSUE THREAD

**Issue by camp-007** [DuendeArchive/IdentityModel#98]
I'm having an issue when trying to consume IdentityModel from a project that targets .NET 4.7.1.  I strongly suspect the issue is more of a corefx or tooling problem.  I've created an issue in the corefx repo, but I'm posting a link to it here just to make you aware, and in hope that perhaps you may have insight you can share or have influence in helping me find a resolution.

https://github.com/dotnet/corefx/issues/27592

For reference, the issue linked above has the following problem repo:

1. Using VS 2017 15.5.7 create a new project using the template "Console App (.NET Framework) targeting .net 4.7.1
2. Add a nuget package reference for the package "IdentityModel" v3.3.1. Use the 'packages.config' package manager format when prompted. Several other System.* nuget package dependencies are also added.
3. Compile the project. No build errors or warnings.
4. Close and re-open the solution
5. Compile the project. Several build warnings like "The referenced component 'System.IO' could not be found" appear. Many of the references in the solution explorer appear with an exclamation mark. The project seems to build successfully, but the warnings cause concern that something is wrong.

These build warnings don't seem like they should be expected or desirable. Is there something obvious I'm doing wrong or misunderstanding?

**Comment by camp-007** [comment]
Also, I should mention that this isn't the first issue I've encountered with the nuget dependencies for IdentityModel when targeting .net framework (instead of .net standard).  

I agree with the previous issue (https://github.com/IdentityModel/IdentityModel2/issues/76) that suggested some problems would be avoided if you were not using the nuget package reference when targeting the full framework.  I have several projects that end up with System.Net.Http binding redirect hell and my problems typically stem from IdentityModel forcing me into using nuget packages that I don't think I need when targeting .net framework.  Admittedly, my understanding of all this stuff is very limited, so forgive my naive observation.  It is quite possible you are 'doing everything right' and the .NET framework is just in a really screwed up state these days.

**Comment by leastprivilege** [comment]
I don't know either. I am still waiting for someone telling me how to do it better.

Keep me posted on what happens on the Microsoft issue you opened.

**Comment by leastprivilege** [comment]
any update?
